/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUsersWithListInputData, CreateUsersWithListInputResponse, CreateUsersWithListInputStatus200 } from "../../types/CreateUsersWithListInput.ts";
import { user } from "../user.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Successful operation
 */
export function createUsersWithListInputStatus200(data?: Partial<CreateUsersWithListInputStatus200>): CreateUsersWithListInputStatus200 {

  return user(data)
}

/**
 * @description successful operation
 */
export function createUsersWithListInputStatusDefault() {

  return undefined
}

export function createUsersWithListInputData(data?: CreateUsersWithListInputData): CreateUsersWithListInputData {

  return [
    ...faker.helpers.multiple(() => (user())),
    ...(data || [])
  ]
}

export function createUsersWithListInputResponse(_data?: CreateUsersWithListInputResponse): CreateUsersWithListInputResponse {

  return faker.helpers.arrayElement<any>([createUsersWithListInputStatus200(), createUsersWithListInputStatusDefault()])
}