/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdateUserData } from "../../types/UpdateUser.ts";
import { createUser } from "../createUser.ts";
import { faker } from "@faker-js/faker";

export function createUpdateUserPathUsername(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createUpdateUserStatusDefault() {
  return undefined
}

/**
 * @description Update an existent user in the store
 */
export function createUpdateUserData(data?: Partial<UpdateUserData>): UpdateUserData {
  return createUser(data)
}

export function createUpdateUserResponse() {
  return undefined
}