/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserData, CreateUserResponse, CreateUserStatusDefault } from "../../types/CreateUser.ts";
import { user } from "../user.ts";

/**
 * @description successful operation
 */
export function createUserStatusDefault(data?: Partial<CreateUserStatusDefault>): CreateUserStatusDefault {

  return user(data)
}

/**
 * @description Created user object
 */
export function createUserData(data?: Partial<CreateUserData>): CreateUserData {

  return user(data)
}

export function createUserResponse(data?: Partial<CreateUserResponse>): CreateUserResponse {

  return createUserStatusDefault(data)
}