/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { TreeNode } from './types/TreeNode'
import { faker } from '@faker-js/faker'

export function createTreeNode<TData extends Partial<TreeNode> = object>(data?: TData) {
  const defaultFakeData = {
    value: faker.string.alpha(),
    left: undefined as unknown as NonNullable<TreeNode>['left'],
    right: undefined as unknown as NonNullable<TreeNode>['right'],
  }
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}
