/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Address } from './Address'
import type { CustomerParamsStatusEnumKey } from './CustomerParamsStatusEnum'

export type Customer = {
  /**
   * @description
   * Format: `int64`
   * @example 100000
   * @type integer | undefined
   */
  id?: bigint
  params?: {
    /**
     * @description Order Status
     * @example approved
     */
    status: CustomerParamsStatusEnumKey
    type: string
  }
  /**
   * @example fehguy
   * @type string | undefined
   */
  username?: string
  address?: Array<Address>
}
