/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const deletePetStatus200Enum = {
  TYPE1: 'TYPE1',
  TYPE2: 'TYPE2',
  TYPE3: 'TYPE3',
} as const

export type DeletePetStatus200EnumKey = (typeof deletePetStatus200Enum)[keyof typeof deletePetStatus200Enum]
