/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const orderStatus = {
    accepted: "accepted"
} as const;

export type OrderStatusKey = (typeof orderStatus)[keyof typeof orderStatus];