/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OrderParams } from './OrderParams.ts'

export const orderStatus = {
  accepted: 'accepted',
} as const

export type OrderStatusKey = (typeof orderStatus)[keyof typeof orderStatus]

export const orderHttpStatusEnum = {
  OrderHttpStatusEnum_200: 200,
  OrderHttpStatusEnum_400: 400,
  OrderHttpStatusEnum_500: 500,
} as const

export type OrderHttpStatusEnumKey = (typeof orderHttpStatusEnum)[keyof typeof orderHttpStatusEnum]

/**
 * @type object
 */
export type Order = {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @description
   * Format: `int64`
   * @example 198772
   * @type integer | undefined
   */
  petId?: bigint
  params?: OrderParams
  /**
   * @description
   * Format: `int32`
   * @example 7
   * @type integer | undefined
   */
  quantity?: number
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  shipDate?: string
  /**
   * @description Order Status
   */
  status?: OrderStatusKey | (string & {})
  /**
   * @description HTTP Status
   * @example 200
   * @type number | undefined
   */
  http_status?: OrderHttpStatusEnumKey
  /**
   * @type boolean | undefined
   */
  complete?: boolean
}
