/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OrderHttpStatusEnumKey } from './OrderHttpStatusEnum'
import type { OrderParamsStatusEnumKey } from './OrderParamsStatusEnum'
import type { OrderStatusKey } from './OrderStatus'

/**
 * @type object
 */
export type Order = {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @description
   * Format: `int64`
   * @example 198772
   * @type integer | undefined
   */
  petId?: bigint
  /**
   * @type object | undefined
   */
  params?: {
    /**
     * @description Order Status
     * @example approved
     */
    status: OrderParamsStatusEnumKey
    /**
     * @type string
     */
    type: string
  }
  /**
   * @description
   * Format: `int32`
   * @example 7
   * @type integer | undefined
   */
  quantity?: number
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  shipDate?: string
  /**
   * @description Order Status
   */
  status?: OrderStatusKey | string
  /**
   * @description HTTP Status
   * @example 200
   */
  http_status?: OrderHttpStatusEnumKey
  /**
   * @type boolean | undefined
   */
  complete?: boolean
}
