/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from './Pet'

export type UpdatePetStatus200Json = Pet

export type UpdatePetStatus200Xml = Pet

export type UpdatePetStatus200 = UpdatePetStatus200Json | UpdatePetStatus200Xml

/**
 * @type unknown
 */
export type UpdatePetStatus400 = unknown

/**
 * @type unknown
 */
export type UpdatePetStatus404 = unknown

/**
 * @type unknown
 */
export type UpdatePetStatus405 = unknown

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetBodyJson = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetBodyXml = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetBodyFormUrlEncoded = Omit<NonNullable<Pet>, 'type' | 'tags'>

export type UpdatePetBody = UpdatePetBodyJson | UpdatePetBodyXml | UpdatePetBodyFormUrlEncoded

/**
 * @type object
 */
export type UpdatePetOptions = {
  body: UpdatePetBody
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type UpdatePetResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: UpdatePetStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: UpdatePetStatus200Xml
      }
  '400': UpdatePetStatus400
  '404': UpdatePetStatus404
  '405': UpdatePetStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetResponse = UpdatePetStatus200 | UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405
