/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from './Pet.ts'

export type UpdatePetStatus200Json = Pet;

export type UpdatePetStatus200Xml = Pet;

export type UpdatePetStatus200 = (UpdatePetStatus200Json | UpdatePetStatus200Xml);

/**
 * @type any
*/
export type UpdatePetStatus400 = any;

/**
 * @type any
*/
export type UpdatePetStatus404 = any;

/**
 * @type any
*/
export type UpdatePetStatus405 = any;

/**
 * @description Update an existent pet in the store
*/
export type UpdatePetJsonData = Omit<NonNullable<Pet>, "type" | "tags">;

/**
 * @description Update an existent pet in the store
*/
export type UpdatePetXmlData = Omit<NonNullable<Pet>, "type" | "tags">;

/**
 * @description Update an existent pet in the store
*/
export type UpdatePetFormUrlEncodedData = Omit<NonNullable<Pet>, "type" | "tags">;

export type UpdatePetData = (UpdatePetJsonData | UpdatePetXmlData | UpdatePetFormUrlEncodedData);

/**
 * @type object
*/
export type UpdatePetRequestConfig = {
    body: UpdatePetData;
    path?: never;
    query?: never;
    headers?: never;
};

/**
 * @type object
*/
export type UpdatePetResponses = {
    "200": UpdatePetStatus200;
    "400": UpdatePetStatus400;
    "404": UpdatePetStatus404;
    "405": UpdatePetStatus405;
};

/**
 * @description Union of all possible responses
*/
export type UpdatePetResponse = (UpdatePetStatus200 | UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405);