/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@kubb/plugin-client/clients/axios";
import type { AddPetData, AddPetStatus405 } from "../../types/AddPet.ts";
import type { Pet } from "../../types/Pet.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { UseMutationOptions, UseMutationResult, QueryClient } from "@tanstack/react-query";
import { mutationOptions, useMutation } from "@tanstack/react-query";

export const addPetMutationKey = () => [{ url: '/pet' }] as const

/**
 * @description Add a new pet to the store
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export async function addPet(data: AddPetData, config: Partial<RequestConfig<AddPetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = "application/json", ...requestConfig } = config


  const requestData = data


  const res = await request<Pet, ResponseErrorConfig<AddPetStatus405>, AddPetData>({ method: "POST", url: `/pet`, data: requestData, contentType, ...requestConfig })

  return res.data
}

export function addPetMutationOptions<TContext = unknown>(config: Partial<RequestConfig<AddPetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {

        const mutationKey = addPetMutationKey()
        return mutationOptions<Pet, ResponseErrorConfig<AddPetStatus405>, {data: AddPetData}, TContext>({
          mutationKey,
          mutationFn: async({ data }) => {
            return addPet(data, config)
          },
        })

}

/**
 * @description Add a new pet to the store
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export function useAddPet<TContext>(options: {
  mutation?: UseMutationOptions<Pet, ResponseErrorConfig<AddPetStatus405>, {data: AddPetData}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<AddPetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" },
} = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions.mutationKey ?? addPetMutationKey()

          const baseOptions = addPetMutationOptions(config) as UseMutationOptions<Pet, ResponseErrorConfig<AddPetStatus405>, {data: AddPetData}, TContext>


          return useMutation<Pet, ResponseErrorConfig<AddPetStatus405>, {data: AddPetData}, TContext>({
            ...baseOptions,
            mutationKey,
            ...mutationOptions,
          }, queryClient) as UseMutationResult<Pet, ResponseErrorConfig<AddPetStatus405>, {data: AddPetData}, TContext>

}