/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from 'swr/mutation'
import type { RequestConfig, ResponseErrorConfig } from './.kubb/client.ts'
import type { CreatePetOptions, CreatePetResponse } from './CreatePet.ts'
import type { SWRMutationConfiguration } from 'swr/mutation'
import { createPet } from './clients/createPet.ts'

export const createPetMutationKey = () => [{ url: '/pet' }] as const

export type CreatePetMutationKey = ReturnType<typeof createPetMutationKey>

export type CreatePetMutationArg = CreatePetOptions

/**
 * {@link /pet}
 */
export function useCreatePet(
  options: {
    mutation?: SWRMutationConfiguration<CreatePetResponse, ResponseErrorConfig<Error>, CreatePetMutationKey | null, CreatePetMutationArg> & {
      throwOnError?: boolean
    }
    client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
    shouldFetch?: boolean
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = createPetMutationKey()

  return useSWRMutation<CreatePetResponse, ResponseErrorConfig<Error>, CreatePetMutationKey | null, CreatePetMutationArg>(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: { body } }) => {
      const { data } = await createPet({ ...config, body, throwOnError: true })
      return data
    },
    mutationOptions,
  )
}
