/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/fetch'
import type { DeletePetResponse, DeletePetPathPetId, DeletePetHeaderApiKey } from './DeletePet'
import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import { fetch } from './.kubb/fetch'
import { DeletePetResponse } from './DeletePet'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const deletePetMutationKey = () => [{ url: '/pet/:petId' }] as const

/**
 * {@link /pet/:petId}
 */
export async function deletePet(
  { petId }: { petId: DeletePetPathPetId },
  headers?: { api_key?: DeletePetHeaderApiKey },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<DeletePetResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'DELETE',
    url: `/pet/${petId}`,
    ...requestConfig,
    headers: { ...headers, ...requestConfig.headers },
  })

  return DeletePetResponse.parse(res.data)
}

export function deletePetMutationOptions<TContext = unknown>(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const mutationKey = deletePetMutationKey()
  return mutationOptions<DeletePetResponse, ResponseErrorConfig<Error>, { petId: DeletePetPathPetId; headers?: { api_key?: DeletePetHeaderApiKey } }, TContext>(
    {
      mutationKey,
      mutationFn: async ({ petId, headers }) => {
        return deletePet({ petId }, headers, config)
      },
    },
  )
}

/**
 * {@link /pet/:petId}
 */
export function useDeletePet<TContext>(
  options: {
    mutation?: UseMutationOptions<
      DeletePetResponse,
      ResponseErrorConfig<Error>,
      { petId: DeletePetPathPetId; headers?: { api_key?: DeletePetHeaderApiKey } },
      TContext
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? deletePetMutationKey()

  const baseOptions = deletePetMutationOptions(config) as UseMutationOptions<
    DeletePetResponse,
    ResponseErrorConfig<Error>,
    { petId: DeletePetPathPetId; headers?: { api_key?: DeletePetHeaderApiKey } },
    TContext
  >

  return useMutation<DeletePetResponse, ResponseErrorConfig<Error>, { petId: DeletePetPathPetId; headers?: { api_key?: DeletePetHeaderApiKey } }, TContext>(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<DeletePetResponse, ResponseErrorConfig<Error>, { petId: DeletePetPathPetId; headers?: { api_key?: DeletePetHeaderApiKey } }, TContext>
}
