/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @type object
*/
export type Tag = {
    /**
     * @description Format: `int64`
     * @type integer | undefined
    */
    id?: bigint;
    /**
     * @type string | undefined
    */
    name?: string;
};