/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { UploadFileData, UploadFileResponse, UploadFilePathPetId, UploadFileStatus200 } from './UploadFile'
import type { UseMutationOptions, UseMutationResult, QueryClient } from '@tanstack/react-query'
import type { z } from 'zod'
import { client } from './.kubb/client'
import { buildFormData } from './.kubb/config'
import { UploadFileResponse, UploadFileData } from './UploadFile'
import { mutationOptions, useMutation } from '@tanstack/react-query'

export const uploadFileMutationKey = () => [{ url: '/pet/:petId/uploadImage' }] as const

/**
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile(
  petId: UploadFilePathPetId,
  data?: UploadFileData,
  config: Partial<RequestConfig<UploadFileData>> & { client?: Client; contentType?: 'application/json' | 'multipart/form-data' } = {},
) {
  const { client: request = client, contentType = 'application/json', ...requestConfig } = config

  const requestData = UploadFileData.parse(data)
  const formData = buildFormData(requestData)

  const res = await request<UploadFileStatus200, ResponseErrorConfig<Error>, z.output<typeof UploadFileData>>({
    method: 'POST',
    url: `/pet/${petId}/uploadImage`,
    data: contentType === 'multipart/form-data' ? (formData as FormData) : requestData,
    contentType,
    ...requestConfig,
  })

  return UploadFileResponse.parse(res.data)
}

export function uploadFileMutationOptions<TContext = unknown>(
  config: Partial<RequestConfig<UploadFileData>> & { client?: Client; contentType?: 'application/json' | 'multipart/form-data' } = {},
) {
  const mutationKey = uploadFileMutationKey()
  return mutationOptions<UploadFileStatus200, ResponseErrorConfig<Error>, { petId: UploadFilePathPetId; data?: UploadFileData }, TContext>({
    mutationKey,
    mutationFn: async ({ petId, data }) => {
      return uploadFile(petId, data, config)
    },
  })
}

/**
 * {@link /pet/:petId/uploadImage}
 */
export function useUploadFile<TContext>(
  options: {
    mutation?: UseMutationOptions<UploadFileStatus200, ResponseErrorConfig<Error>, { petId: UploadFilePathPetId; data?: UploadFileData }, TContext> & {
      client?: QueryClient
    }
    client?: Partial<RequestConfig<UploadFileData>> & { client?: Client; contentType?: 'application/json' | 'multipart/form-data' }
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions.mutationKey ?? uploadFileMutationKey()

  const baseOptions = uploadFileMutationOptions(config) as UseMutationOptions<
    UploadFileStatus200,
    ResponseErrorConfig<Error>,
    { petId: UploadFilePathPetId; data?: UploadFileData },
    TContext
  >

  return useMutation<UploadFileStatus200, ResponseErrorConfig<Error>, { petId: UploadFilePathPetId; data?: UploadFileData }, TContext>(
    {
      ...baseOptions,
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  ) as UseMutationResult<UploadFileStatus200, ResponseErrorConfig<Error>, { petId: UploadFilePathPetId; data?: UploadFileData }, TContext>
}
