/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cat } from './types/Cat'
import { faker } from '@faker-js/faker'

export function cat<TOverwriteData extends Partial<Cat> = {}>(data?: TOverwriteData): Required<Cat> {
  const defaultFakeData = {
    id: faker.number.int(),
    get archEnemy() {
      return faker.helpers.arrayElement<any>([null, pet()])
    },
    get friends() {
      return faker.helpers.multiple(() => pet())
    },
  }
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<Cat>
}
