/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export const proxyHostALPN = {
  '': '',
  h3: 'h3',
  h2: 'h2',
  'http/1.1': 'http/1.1',
} as const

export type ProxyHostALPNKey = (typeof proxyHostALPN)[keyof typeof proxyHostALPN]
