/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from '../Pet.ts'
import type { PetStatusEnum } from '../PetStatusEnum.ts'

/**
 * @description Status values that need to be considered for filter
 * @default available
 */
export type FindPetsByStatusQueryStatus = PetStatusEnum | undefined

/**
 * @type array
 */
export type FindPetsByStatusStatus200Json = Array<Pet>

/**
 * @type array
 */
export type FindPetsByStatusStatus200Xml = Array<Pet>

export type FindPetsByStatusStatus200 = FindPetsByStatusStatus200Json | FindPetsByStatusStatus200Xml

/**
 * @type any
 */
export type FindPetsByStatusStatus400 = any

/**
 * @type object
 */
export type FindPetsByStatusRequestConfig = {
  data?: never
  pathParams?: never
  /**
   * @type object | undefined
   */
  queryParams?: {
    status?: FindPetsByStatusQueryStatus
  }
  headerParams?: never
  /**
   * @type string
   */
  url: '/pet/findByStatus'
}

/**
 * @type object
 */
export type FindPetsByStatusResponses = {
  '200': FindPetsByStatusStatus200
  '400': FindPetsByStatusStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByStatusResponse = FindPetsByStatusStatus200 | FindPetsByStatusStatus400
