/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from '../Pet.ts'

/**
 * @description ID of pet to return
 *
 * Format: `int64`
 * @type integer
 */
export type GetPetByIdPathPetId = bigint

export type GetPetByIdStatus200Json = Pet

export type GetPetByIdStatus200Xml = Pet

export type GetPetByIdStatus200 = GetPetByIdStatus200Json | GetPetByIdStatus200Xml

/**
 * @type unknown
 */
export type GetPetByIdStatus400 = unknown

/**
 * @type unknown
 */
export type GetPetByIdStatus404 = unknown

/**
 * @type object
 */
export type GetPetByIdRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    petId: GetPetByIdPathPetId
  }
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type GetPetByIdResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: GetPetByIdStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: GetPetByIdStatus200Xml
      }
  '400': GetPetByIdStatus400
  '404': GetPetByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetPetByIdResponse = GetPetByIdStatus200 | GetPetByIdStatus400 | GetPetByIdStatus404
