export type {
  AddPetBody,
  AddPetBodyFormUrlEncoded,
  AddPetBodyJson,
  AddPetBodyXml,
  AddPetOptions,
  AddPetResponse,
  AddPetResponses,
  AddPetStatus200,
  AddPetStatus200Json,
  AddPetStatus200Xml,
  AddPetStatus405,
} from './AddPet.ts'
export type {
  DeletePetHeaders,
  DeletePetOptions,
  DeletePetPath,
  DeletePetResponse,
  DeletePetResponses,
  DeletePetStatus200,
  DeletePetStatus400,
} from './DeletePet.ts'
export type {
  FindPetsByStatusOptions,
  FindPetsByStatusQuery,
  FindPetsByStatusResponse,
  FindPetsByStatusResponses,
  FindPetsByStatusStatus200,
  FindPetsByStatusStatus200Json,
  FindPetsByStatusStatus200Xml,
  FindPetsByStatusStatus400,
} from './FindPetsByStatus.ts'
export type {
  FindPetsByTagsOptions,
  FindPetsByTagsQuery,
  FindPetsByTagsResponse,
  FindPetsByTagsResponses,
  FindPetsByTagsStatus200,
  FindPetsByTagsStatus200Json,
  FindPetsByTagsStatus200Xml,
  FindPetsByTagsStatus400,
} from './FindPetsByTags.ts'
export type {
  GetPetByIdOptions,
  GetPetByIdPath,
  GetPetByIdResponse,
  GetPetByIdResponses,
  GetPetByIdStatus200,
  GetPetByIdStatus200Json,
  GetPetByIdStatus200Xml,
  GetPetByIdStatus400,
  GetPetByIdStatus404,
} from './GetPetById.ts'
export type {
  UpdatePetBody,
  UpdatePetBodyFormUrlEncoded,
  UpdatePetBodyJson,
  UpdatePetBodyXml,
  UpdatePetOptions,
  UpdatePetResponse,
  UpdatePetResponses,
  UpdatePetStatus200,
  UpdatePetStatus200Json,
  UpdatePetStatus200Xml,
  UpdatePetStatus400,
  UpdatePetStatus404,
  UpdatePetStatus405,
} from './UpdatePet.ts'
export type {
  UpdatePetWithFormOptions,
  UpdatePetWithFormPath,
  UpdatePetWithFormQuery,
  UpdatePetWithFormResponse,
  UpdatePetWithFormResponses,
  UpdatePetWithFormStatus405,
} from './UpdatePetWithForm.ts'
export type {
  UploadFileBody,
  UploadFileOptions,
  UploadFilePath,
  UploadFileQuery,
  UploadFileResponse,
  UploadFileResponses,
  UploadFileStatus200,
} from './UploadFile.ts'
