/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const arrayOfObjectStatusEnum = {
  active: 'active',
  inactive: 'inactive',
} as const

export type ArrayOfObjectStatusEnumKey = (typeof arrayOfObjectStatusEnum)[keyof typeof arrayOfObjectStatusEnum]

/**
 * @type array
 */
export type GetArrayOfObjectStatus200 = {
  /**
   * @type number
   */
  id: number
  /**
   * @type string
   */
  status: ArrayOfObjectStatusEnumKey
}[]

/**
 * @type object
 */
export type GetArrayOfObjectRequestConfig = {
  body?: never
  path?: never
  query?: never
  headers?: never
  cookie?: never
}

/**
 * @type object
 */
export type GetArrayOfObjectResponses = {
  '200': GetArrayOfObjectStatus200
}

/**
 * @description Union of all possible responses
 */
export type GetArrayOfObjectResponse = GetArrayOfObjectStatus200
