/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export type GetPetByIdPath = {
  petId: string
}

export type GetPetByIdStatus200Json = {
  name: string
}

export type GetPetByIdStatus200Xml = {
  id: number
}

export type GetPetByIdStatus200 = GetPetByIdStatus200Json | GetPetByIdStatus200Xml

export type GetPetByIdOptions = {
  body?: never
  path: GetPetByIdPath
  query?: never
  headers?: never
}

export type GetPetByIdResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: GetPetByIdStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: GetPetByIdStatus200Xml
      }
}

/**
 * @description Union of all possible responses
 */
export type GetPetByIdResponse = GetPetByIdStatus200
