/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from '../Pet.ts'

/**
 * @type object
 */
export type AddPetStatus200 = Pet

/**
 * @type any
 */
export type AddPetStatus405 = any

/**
 * @description Create a new pet in the store
 * @type object
 */
export type AddPetData = Pet

/**
 * @type object
 */
export type AddPetRequestConfig = {
  body: AddPetData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type AddPetResponses = {
  '200': AddPetStatus200
  '405': AddPetStatus405
}

/**
 * @description Union of all possible responses
 */
export type AddPetResponse = AddPetStatus200 | AddPetStatus405
