/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { orderInputSchema, orderSchema } from './orderSchema'

export const placeOrderStatus200Schema = orderSchema

export const placeOrderStatus405Schema = z.any()

export const placeOrderResponseSchema = placeOrderStatus200Schema

export const placeOrderErrorSchema = placeOrderStatus405Schema

export const placeOrderBodySchemaJson = orderInputSchema.optional()

export const placeOrderBodySchemaXml = orderInputSchema.optional()

export const placeOrderBodySchemaFormUrlEncoded = orderInputSchema.optional()

export const placeOrderBodySchema = z.union([placeOrderBodySchemaJson, placeOrderBodySchemaXml, placeOrderBodySchemaFormUrlEncoded])