/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import { faker } from '@faker-js/faker'

export function createNullableName(data?: string | null): string | null {
  return data !== undefined ? data : faker.string.alpha()
}
