/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { findPetsByStatusHandler } from './findPetsByStatus'
import { getInventoryHandler } from './getInventory'
import { getPetByIdHandler } from './getPetById'
import { placeOrderHandler } from './placeOrder'
import { uploadFileHandler } from './uploadFile'
import { findPetsByStatusQueryStatusSchema, findPetsByStatusStatus200Schema } from '../zod/findPetsByStatusSchema'
import { getInventoryStatus200Schema } from '../zod/getInventorySchema'
import { getPetByIdPathPetIdSchema, getPetByIdStatus200Schema } from '../zod/getPetByIdSchema'
import { placeOrderBodySchema, placeOrderStatus200Schema } from '../zod/placeOrderSchema'
import { uploadFileBodySchema, uploadFilePathPetIdSchema, uploadFileQueryAdditionalMetadataSchema, uploadFileStatus200Schema } from '../zod/uploadFileSchema'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio'
import { z } from 'zod'

export function getServer() {
  const server = new McpServer({
    name: 'Swagger PetStore - OpenAPI 3.0',
    version: '1.0.11',
  })

  server.registerTool("findPetsByStatus", {
    title: "Finds Pets by status",
    description: "Multiple status values can be provided with comma separated strings",
    outputSchema: { data: findPetsByStatusStatus200Schema },
    inputSchema: { query: z.object({ "status": findPetsByStatusQueryStatusSchema }) },
  }, async ({ query }, request) => {
    return findPetsByStatusHandler({ query }, request)
  })


  server.registerTool("getPetById", {
    title: "Find pet by ID",
    description: "Returns a single pet",
    outputSchema: { data: getPetByIdStatus200Schema },
    inputSchema: { path: z.object({ "petId": getPetByIdPathPetIdSchema }) },
  }, async ({ path }, request) => {
    return getPetByIdHandler({ path }, request)
  })


  server.registerTool("uploadFile", {
    title: "uploads an image",
    description: "Make a POST request to /pet/{petId}/uploadImage",
    outputSchema: { data: uploadFileStatus200Schema },
    inputSchema: { path: z.object({ "petId": uploadFilePathPetIdSchema }), query: z.object({ "additionalMetadata": uploadFileQueryAdditionalMetadataSchema }), body: uploadFileBodySchema },
  }, async ({ path, query, body }, request) => {
    return uploadFileHandler({ path, query, body }, request)
  })


  server.registerTool("getInventory", {
    title: "Returns pet inventories by status",
    description: "Returns a map of status codes to quantities",
    outputSchema: { data: getInventoryStatus200Schema },
  }, async (request) => {
    return getInventoryHandler(request)
  })


  server.registerTool("placeOrder", {
    title: "Place an order for a pet",
    description: "Place a new order in the store",
    outputSchema: { data: placeOrderStatus200Schema },
    inputSchema: { body: placeOrderBodySchema },
  }, async ({ body }, request) => {
    return placeOrderHandler({ body }, request)
  })

  return server
}

export const server = getServer()

export async function startServer() {
  try {
      const transport = new StdioServerTransport()
      await server.connect(transport)

    } catch (error) {
      console.error('Failed to start server:', error)
      process.exit(1)
    }
}