/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { orderStatusEnumSchema } from './orderStatusEnumSchema'

export const orderSchema = z.object({
  id: z.coerce.bigint().optional().meta({ examples: [10] }),
  petId: z.coerce.bigint().optional().meta({ examples: [198772] }),
  quantity: z.int32().optional().meta({ examples: [7] }),
  shipDate: z.iso.datetime().transform((value) => Temporal.Instant.from(value)).optional(),
  status: orderStatusEnumSchema.optional().describe('Order Status').meta({ examples: ['approved'] }),
  complete: z.boolean().optional(),
})

export const orderInputSchema = z.object({
  id: z.coerce.bigint().optional().meta({ examples: [10] }),
  petId: z.coerce.bigint().optional().meta({ examples: [198772] }),
  quantity: z.int32().optional().meta({ examples: [7] }),
  shipDate: z.instanceof(Temporal.Instant).transform((value) => value.toString()).optional(),
  status: orderStatusEnumSchema.optional().describe('Order Status').meta({ examples: ['approved'] }),
  complete: z.boolean().optional(),
})
