/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@kubb/plugin-client/clients/axios";
import useSWR from "swr";
import type { FindPetsByTagsResponse, FindPetsByTagsQueryTags, FindPetsByTagsStatus200, FindPetsByTagsStatus400 } from "../types/FindPetsByTags.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { SWRConfiguration } from "swr";

export const findPetsByTagsQueryKey = (params?: { tags?: FindPetsByTagsQueryTags }) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export async function findPetsByTags({ params }: { params?: { tags?: FindPetsByTagsQueryTags } } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config




  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<FindPetsByTagsStatus400>, unknown>({ method: "GET", url: `/pet/findByTags`, params, ...requestConfig })

  return res.data
}

export function findPetsByTagsQueryOptions({ params }: { params?: { tags?: FindPetsByTagsQueryTags } } = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {

        return {
          fetcher: async () => {
            return findPetsByTags({ params }, config)
          },
        }

}

/**
 * @description Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.
 * @summary Finds Pets by tags
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags({ params }: { params?: { tags?: FindPetsByTagsQueryTags } } = {}, options: {
  query?: SWRConfiguration<FindPetsByTagsResponse, ResponseErrorConfig<FindPetsByTagsStatus400>>,
  client?: Partial<RequestConfig> & { client?: Client },
  shouldFetch?: boolean,
  immutable?: boolean
} = {}) {

         const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

         const queryKey = findPetsByTagsQueryKey(params)

         return useSWR<FindPetsByTagsResponse, ResponseErrorConfig<FindPetsByTagsStatus400>, FindPetsByTagsQueryKey | null>(
          shouldFetch ? queryKey : null,
          {
            ...findPetsByTagsQueryOptions({ params }, config),
            ...(immutable ? {
                revalidateIfStale: false,
                revalidateOnFocus: false,
                revalidateOnReconnect: false
              } : { }),
            ...queryOptions,
          }
         )

}