/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";

export const deleteOrderPathOrderIdSchema = v.pipe(v.pipe(v.number(), v.integer()), v.description("ID of the order that needs to be deleted"))

export type DeleteOrderPathOrderIdSchema = v.InferOutput<typeof deleteOrderPathOrderIdSchema>

export const deleteOrderStatus400Schema = v.any()

export type DeleteOrderStatus400Schema = v.InferOutput<typeof deleteOrderStatus400Schema>

export const deleteOrderStatus404Schema = v.any()

export type DeleteOrderStatus404Schema = v.InferOutput<typeof deleteOrderStatus404Schema>

export const deleteOrderResponseSchema = v.union([deleteOrderStatus400Schema, deleteOrderStatus404Schema])

export type DeleteOrderResponseSchema = v.InferOutput<typeof deleteOrderResponseSchema>