/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { orderSchema } from "./orderSchema.ts";

export const getOrderByIdPathOrderIdSchema = v.pipe(v.pipe(v.number(), v.integer()), v.description("ID of order that needs to be fetched"))

export type GetOrderByIdPathOrderIdSchema = v.InferOutput<typeof getOrderByIdPathOrderIdSchema>

export const getOrderByIdStatus200Schema = orderSchema

export type GetOrderByIdStatus200Schema = v.InferOutput<typeof getOrderByIdStatus200Schema>

export const getOrderByIdStatus400Schema = v.any()

export type GetOrderByIdStatus400Schema = v.InferOutput<typeof getOrderByIdStatus400Schema>

export const getOrderByIdStatus404Schema = v.any()

export type GetOrderByIdStatus404Schema = v.InferOutput<typeof getOrderByIdStatus404Schema>

export const getOrderByIdResponseSchema = v.union([getOrderByIdStatus200Schema, getOrderByIdStatus400Schema, getOrderByIdStatus404Schema])

export type GetOrderByIdResponseSchema = v.InferOutput<typeof getOrderByIdResponseSchema>