/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";

export const logoutUserStatusDefaultSchema = v.any()

export type LogoutUserStatusDefaultSchema = v.InferOutput<typeof logoutUserStatusDefaultSchema>

export const logoutUserResponseSchema = logoutUserStatusDefaultSchema

export type LogoutUserResponseSchema = v.InferOutput<typeof logoutUserResponseSchema>