/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { phoneNumberSchema } from "./phoneNumberSchema.ts";

export const phoneWithMaxLengthSchema = v.intersect([phoneNumberSchema, v.pipe(v.string(), v.maxLength(15))])

export type PhoneWithMaxLengthSchema = v.InferOutput<typeof phoneWithMaxLengthSchema>