packages:
  - packages/*
  - internals/*
  - examples/*
  - tests/**

allowBuilds:
  cypress: true
  es5-ext: true
  esbuild: true
  msw: true
  vue-demi: true

pmOnFail: warn
minimumReleaseAge: 1440

catalog:
  '@kubb/adapter-oas': 5.0.0-beta.6
  '@kubb/agent': 5.0.0-beta.6
  '@kubb/core': 5.0.0-beta.6
  '@kubb/middleware-barrel': 5.0.0-beta.6
  '@kubb/parser-ts': 5.0.0-beta.6
  '@kubb/renderer-jsx': 5.0.0-beta.6
  kubb: 5.0.0-beta.6
  unplugin-kubb: 5.0.0-beta.6
  '@types/node': ^22.19.19
  prettier: ^3.8.3
  '@types/react': ^19.2.14
  '@size-limit/file': ^12.1.0
  'size-limit': ^12.1.0
  remeda: ^2.34.0
  tsdown: ^0.22.0
  typescript: ^6.0.3
  vitest: ^4.1.6
  '@vitest/coverage-v8': ^4.1.6
  '@vitest/ui': ^4.1.6
  oxfmt: ^0.47.0
  oxlint: ^1.64.0
