packages:
  - packages/*
  - internals/*
  - examples/*
  - tests/**

allowBuilds:
  cypress: false
  es5-ext: true
  esbuild: true
  msw: true
  vue-demi: true

catalog:
  '@kubb/adapter-oas': 5.0.0-beta.93
  '@kubb/core': 5.0.0-beta.93
  '@kubb/kit': 5.0.0-beta.93
  '@kubb/plugin-barrel': 5.0.0-beta.93
  '@kubb/parser-ts': 5.0.0-beta.93
  '@types/node': ^22.20.1
  '@types/react': ^19.2.17
  '@vitest/coverage-v8': ^4.1.10
  '@vitest/ui': ^4.1.10
  kubb: 5.0.0-beta.93
  oxfmt: ^0.58.0
  oxlint: ^1.73.0
  prettier: ^3.9.4
  tsdown: ^0.22.3
  typescript: ^6.0.3
  unplugin-kubb: 5.0.0-beta.93
  vitest: ^4.1.10
#
#overrides:
#  '@kubb/adapter-oas': link:../kubb/packages/adapter-oas
#  '@kubb/ast': link:../kubb/packages/ast
#  '@kubb/cli': link:../kubb/packages/cli
#  '@kubb/core': link:../kubb/packages/core
#  '@kubb/kit': link:../kubb/packages/kit
#  '@kubb/mcp': link:../kubb/packages/mcp
#  '@kubb/plugin-barrel': link:../kubb/packages/plugin-barrel
#  '@kubb/parser-md': link:../kubb/packages/parser-md
#  '@kubb/parser-ts': link:../kubb/packages/parser-ts
#  '@kubb/renderer-jsx': link:../kubb/packages/renderer-jsx
#  '@kubb/tui': link:../kubb/packages/tui
#  kubb: link:../kubb/packages/kubb
#  unplugin-kubb: link:../kubb/packages/unplugin-kubb

minimumReleaseAge: 4320 # 72 hours, matches .npmrc min-package-age
minimumReleaseAgeExclude:
  - '@kubb/*'
  - 'kubb'
  - 'unplugin-kubb'
  - '@types/*'
  - '@clack/core'
pmOnFail: warn
resolutionMode: highest
