/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { addPetRequestSchema } from "./addPetRequestSchema.ts";
import { petSchema } from "./petSchema.ts";

export const addPetStatus200Schema = petSchema

export const addPetStatus405Schema = z.any()

export const addPetResponseSchema = z.union([addPetStatus200Schema, addPetStatus405Schema])

export const addPetDataSchema = addPetRequestSchema.describe("Create a new pet in the store")