/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { petSchema } from './petSchema.ts'

export const getPetByIdPathPetIdSchema = z.bigint().describe('ID of pet to return')

export const getPetByIdStatus200SchemaJson = petSchema

export const getPetByIdStatus200SchemaXml = petSchema

export const getPetByIdStatus200Schema = z.union([getPetByIdStatus200SchemaJson, getPetByIdStatus200SchemaXml])

export const getPetByIdStatus400Schema = z.any()

export const getPetByIdStatus404Schema = z.any()

export const getPetByIdResponseSchema = getPetByIdStatus200Schema

export const getPetByIdErrorSchema = z.union([getPetByIdStatus400Schema, getPetByIdStatus404Schema])