/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { orderSchema } from "../orderSchema.ts";

export const getOrderByIdPathOrderIdSchema = v.pipe(v.pipe(v.number(), v.integer()), v.description("ID of order that needs to be fetched"))

export const getOrderByIdStatus200Schema = orderSchema

export const getOrderByIdStatus400Schema = v.any()

export const getOrderByIdStatus404Schema = v.any()

export const getOrderByIdResponseSchema = v.union([getOrderByIdStatus200Schema, getOrderByIdStatus400Schema, getOrderByIdStatus404Schema])