/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { CreateUserData, CreateUserResponse } from "../../types/CreateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const createUserMutationKey = () => [{ url: '/user' }] as const

/**
 * @description This can only be done by the logged in user.
 * @summary Create user
 * {@link /user}
 */
export async function createUser(data?: CreateUserData, contentType: "application/json" | "application/xml" | "application/x-www-form-urlencoded" = "application/json", config: Partial<RequestConfig<CreateUserData>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config


  const requestData = data


  const res = await request<CreateUserResponse, ResponseErrorConfig<Error>, CreateUserData>({ method: "POST", url: `/user`, data: requestData, ...requestConfig })

  return res.data
}

/**
 * @description This can only be done by the logged in user.
 * @summary Create user
 * {@link /user}
 */
export function useCreateUser<TContext>(options: {
  mutation?: MutationObserverOptions<CreateUserResponse, ResponseErrorConfig<Error>, {data?: MaybeRefOrGetter<CreateUserData>, contentType?: MaybeRefOrGetter<"application/json" | "application/xml" | "application/x-www-form-urlencoded">}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<CreateUserData>> & { client?: Client },
} = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? createUserMutationKey()

          return useMutation<CreateUserResponse, ResponseErrorConfig<Error>, {data?: CreateUserData, contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded"}, TContext>({
            mutationFn: async({ data, contentType }) => {
              return createUser(data, contentType, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)

}