/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { AddPetData, AddPetStatus200, AddPetStatus405 } from '../types/AddPet.ts'
import { client } from '../.kubb/client.ts'

export const addPetQueryKey = (data?: AddPetData) => [{ url: '/pet' }, ...(data ? [data] : [])] as const

type AddPetQueryKey = ReturnType<typeof addPetQueryKey>

/**
 * @description Add a new pet to the store
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export async function addPet(data: AddPetData, config: Partial<RequestConfig<AddPetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = 'application/json', ...requestConfig } = config

  const requestData = data

  const res = await request<AddPetStatus200, ResponseErrorConfig<AddPetStatus405>, AddPetData>({ method: 'POST', url: `/pet`, data: requestData, contentType, ...requestConfig })

  return res.data
}

export function addPetQueryOptions(data?: AddPetData, config: Partial<RequestConfig<AddPetData>> & { client?: Client } = {}) {
  return {
    fetcher: async () => {
      return addPet(data!, config)
    },
  }
}