/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { DeleteUserResponse, DeleteUserPathUsername, DeleteUserStatus400, DeleteUserStatus404 } from '../types/DeleteUser.ts'
import { client } from '../.kubb/client.ts'

export const deleteUserQueryKey = (username?: DeleteUserPathUsername) => [{ url: '/user/:username', params: {username:username} }] as const

type DeleteUserQueryKey = ReturnType<typeof deleteUserQueryKey>

/**
 * @description This can only be done by the logged in user.
 * @summary Delete user
 * {@link /user/:username}
 */
export async function deleteUser(username: DeleteUserPathUsername, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<DeleteUserResponse, ResponseErrorConfig<DeleteUserStatus400 | DeleteUserStatus404>, unknown>({ method: 'DELETE', url: `/user/${username}`, ...requestConfig })

  return res.data
}

export function deleteUserQueryOptions(username?: DeleteUserPathUsername, config: Partial<RequestConfig> & { client?: Client } = {}) {
  return {
    fetcher: async () => {
      return deleteUser(username!, config)
    },
  }
}