/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { RequestConfig } from '../.kubb/client.ts'
import type { FindPetsByStatusOptions } from '../types/FindPetsByStatus.ts'
import { findPetsByStatus } from '../clients/findPetsByStatus.ts'

export const findPetsByStatusQueryKey = ({ query }: Omit<FindPetsByStatusOptions, 'headers'> = {}) => [{ url: '/pet/findByStatus' }, ...(query ? [query] : [])] as const

type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>

export function findPetsByStatusQueryOptions({ query }: FindPetsByStatusOptions = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  return {
    fetcher: async () => {
      const { data } = await findPetsByStatus({ ...config, query, throwOnError: true })
      return data
    },
  }
}