/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult, RequestConfig } from '../.kubb/client.ts'
import type { GetInventoryRequestConfig, GetInventoryResponses, GetInventoryResponse } from '../types/GetInventory.ts'
import { client } from '../.kubb/client.ts'

export const getInventoryQueryKey = () => [{ url: '/store/inventory' }] as const

type GetInventoryQueryKey = ReturnType<typeof getInventoryQueryKey>

/**
 * @description Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 * {@link /store/inventory}
 */
export function getInventory<ThrowOnError extends boolean = true>(options: Options<GetInventoryRequestConfig, ThrowOnError>): Promise<RequestResult<GetInventoryResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/store/inventory', ...config }) as Promise<RequestResult<GetInventoryResponses, ThrowOnError>>
}

export function getInventoryQueryOptions(config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  return {
    fetcher: async () => {
      const { data } = await getInventory({ ...config, throwOnError: true })
      return data
    },
  }
}