/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import type { UploadFilePathPetId, UploadFileQueryAdditionalMetadata, UploadFileStatus200 } from '../types/UploadFile.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'

export const uploadFileQueryKey = (petId?: UploadFilePathPetId, params?: { additionalMetadata?: UploadFileQueryAdditionalMetadata }) => [{ url: '/pet/:petId/uploadImage', params: {petId:petId} }, ...(params ? [params] : [])] as const

type UploadFileQueryKey = ReturnType<typeof uploadFileQueryKey>

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile(petId: UploadFilePathPetId, params?: { additionalMetadata?: UploadFileQueryAdditionalMetadata }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<UploadFileStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'POST', url: `/pet/${petId}/uploadImage`, params, ...requestConfig })

  return res.data
}

export function uploadFileQueryOptions(petId?: UploadFilePathPetId, params?: { additionalMetadata?: UploadFileQueryAdditionalMetadata }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  return {
    fetcher: async () => {
      return uploadFile(petId!, params, config)
    },
  }
}