/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from './Pet.ts'
import type { PetUpdate } from './PetUpdate.ts'

/**
 * @type string
*/
export type UpdatePetPathPetId = string;

/**
 * @type boolean | undefined
*/
export type UpdatePetQueryIncludeDeleted = boolean | undefined;

/**
 * @type string | undefined
*/
export type UpdatePetQueryRequestSource = string | undefined;

/**
 * @type object
*/
export type UpdatePetStatus200 = Pet;

/**
 * @type object
*/
export type UpdatePetData = PetUpdate;

/**
 * @type object
*/
export type UpdatePetRequestConfig = {
    body: UpdatePetData;
    /**
     * @type object | undefined
    */
    path?: {
        petId: UpdatePetPathPetId;
    };
    /**
     * @type object | undefined
    */
    query?: {
        includeDeleted?: UpdatePetQueryIncludeDeleted;
        requestSource?: UpdatePetQueryRequestSource;
    };
    headers?: never;
    /**
     * @type string
    */
    url: `/pets/${string}`;
};

/**
 * @type object
*/
export type UpdatePetResponses = {
    "200": UpdatePetStatus200;
};

/**
 * @description Union of all possible responses
*/
export type UpdatePetResponse = UpdatePetStatus200;