/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type any
 */
export type GetInventoryStatus200 = any

/**
 * @type object
 */
export type GetInventoryRequestConfig = {
  body?: never
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type GetInventoryResponses = {
  '200': GetInventoryStatus200
}

/**
 * @description Union of all possible responses
 */
export type GetInventoryResponse = GetInventoryStatus200
