/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddPetRequestStatusEnumKey } from '../types/AddPetRequestStatusEnum'
import { fakerEN as faker } from '@faker-js/faker'

/**
 * @description pet status in the store
 */
export function createAddPetRequestStatusEnum(data?: AddPetRequestStatusEnumKey): AddPetRequestStatusEnumKey {
  return data ?? faker.helpers.arrayElement<AddPetRequestStatusEnumKey>(['available', 'pending', 'sold'])
}