/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserData, CreateUserResponse } from "../types/CreateUser.ts";
import type { User } from "../types/User.ts";

export function createUser(data?: CreateUserData, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<CreateUserResponse> {
  return cy.request<CreateUserResponse>({
    method: 'POST',
    url: `/user`,
    body: data,
    ...options
  }).then((res) => res.body)
}