/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FindPetsByStatusRequestConfig, FindPetsByStatusResponse } from '../types/FindPetsByStatus.ts'

export function findPetsByStatus({ query }: Omit<FindPetsByStatusRequestConfig, 'url'> = {}, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<FindPetsByStatusResponse> {
  return cy.request<FindPetsByStatusResponse>({
    method: 'GET',
    url: `/pet/findByStatus`,
    qs: query,
    ...options
  }).then((res) => res.body)
}