/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPetByIdOptions, GetPetByIdResponse } from '../types/GetPetById.ts'

export function getPetById({ path }: GetPetByIdOptions, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<GetPetByIdResponse> {
  return cy.request<GetPetByIdResponse>({
    method: 'GET',
    url: `/pet/${path.petId}`,
    ...options
  }).then((res) => res.body)
}