/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPetByIdRequestConfig, GetPetByIdResponse } from '../types/GetPetById.ts'

export function getPetById({ path }: Omit<GetPetByIdRequestConfig, 'url'>, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<GetPetByIdResponse> {
  const { petId } = path

  return cy.request<GetPetByIdResponse>({
    method: 'GET',
    url: `/pet/${petId}`,
    ...options
  }).then((res) => res.body)
}