/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/fetch'
import type { FindPetsByStatusResponse, FindPetsByStatusQueryStatus } from './FindPetsByStatus'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { fetch } from './.kubb/fetch'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const findPetsByStatusQueryKey = (params?: { status?: FindPetsByStatusQueryStatus }) =>
  [{ url: '/pet/findByStatus' }, ...(params ? [params] : [])] as const

export type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>

/**
 * {@link /pet/findByStatus}
 */
export async function findPetsByStatus(
  { params }: { params?: { status?: FindPetsByStatusQueryStatus } } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindPetsByStatusResponse, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/pet/findByStatus`,
    params,
    ...requestConfig,
  })
}

export function findPetsByStatusQueryOptions(
  { params }: { params?: { status?: FindPetsByStatusQueryStatus } } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = findPetsByStatusQueryKey(params)
  return queryOptions<FindPetsByStatusResponse, ResponseErrorConfig<Error>, FindPetsByStatusResponse, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByStatus({ params }, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /pet/findByStatus}
 */
export function useFindPetsByStatus<
  TData = FindPetsByStatusResponse,
  TQueryData = FindPetsByStatusResponse,
  TQueryKey extends QueryKey = FindPetsByStatusQueryKey,
>(
  { params }: { params?: { status?: FindPetsByStatusQueryStatus } } = {},
  options: {
    query?: Partial<QueryObserverOptions<FindPetsByStatusResponse, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? findPetsByStatusQueryKey(params)

  const query = useQuery(
    {
      ...findPetsByStatusQueryOptions({ params }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
