/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";

export const orderSchema = v.object({
    "id": v.optional(v.pipe(v.number(), v.integer())),
    "petId": v.optional(v.pipe(v.number(), v.integer())),
    "quantity": v.optional(v.pipe(v.number(), v.integer())),
    "shipDate": v.optional(v.pipe(v.string(), v.isoDateTime())),
    "status": v.pipe(v.optional(v.picklist(["placed", "approved", "delivered"])), v.description("Order Status")),
    "complete": v.optional(v.boolean())
    })