/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import * as z from 'zod'

export const deletePetPathPetIdSchema = z.string()

export const deletePetStatus204Schema = z.void()

export const deletePetResponseSchema = deletePetStatus204Schema
