/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const getInventoryStatus200Schema = z.object({}).catchall(z.int())

export const getInventoryResponseSchema = getInventoryStatus200Schema

export const getInventorySuccessResponseSchema = getInventoryStatus200Schema