/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Category } from "../types/Category.ts";
import { faker } from "@faker-js/faker";

export function category(data?: Partial<Category>): typeof _defaults & Omit<Category, keyof typeof _defaults> {
  const _defaults = {"id": faker.number.int(),"name": faker.string.alpha()}
  const result = { ..._defaults, ...(data || {}) } as typeof _defaults & Omit<Category, keyof typeof _defaults>
  return result
}