/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description pet status in the store
 * @type string
 */
export type AddPetRequestStatusEnum = 'available' | 'pending' | 'sold' | 'in store'
