/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { AddPetRequestStatusEnum } from './AddPetRequestStatusEnum'
import type { Category } from './Category'
import type { Tag } from './Tag'

/**
 * @type object
 */
export type AddPetRequest = {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category
  /**
   * @type array
   */
  photoUrls: Array<string>
  /**
   * @type array | undefined
   */
  tags?: Array<Tag>
  /**
   * @description pet status in the store
   */
  status?: AddPetRequestStatusEnum
}
