/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { OrderParamsStatusEnum } from './OrderParamsStatusEnum.ts'

/**
 * @type object
 */
export type OrderParams = {
  /**
   * @description Order Status
   * @example approved
   */
  status: OrderParamsStatusEnum
  /**
   * @type string
   */
  type: string
}
