/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description Order Status
 * @example approved
 * @type string
 */
export type OrderParamsStatusEnum = 'placed' | 'approved' | 'delivered'
