/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Cat } from './Cat.ts'
import type { Category1 } from './Category1.ts'
import type { Dog } from './Dog.ts'
import type { PetStatusEnum } from './PetStatusEnum.ts'
import type { PetTypeEnum } from './PetTypeEnum.ts'
import type { Tag } from './Tag.ts'

export type Pet = (
  | (Dog & {
      /**
       * @type string
       */
      readonly type: 'dog'
    })
  | (Cat & {
      /**
       * @type string
       */
      readonly type: 'cat'
    })
) & {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  readonly type: PetTypeEnum
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category1
  /**
   * @type array
   */
  photoUrls: Array<string>
  /**
   * @type array | undefined
   */
  readonly tags?: Array<Tag>
  /**
   * @description pet status in the store
   */
  status?: PetStatusEnum
}
