/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Customer } from './Customer'

export type UnhappyCustomer = Customer & {
  reasonToBeUnhappy?: string
  isHappy?: false
}
