export type { AddPetData, AddPetFormUrlEncodedData, AddPetJsonData, AddPetRequestConfig, AddPetResponse, AddPetResponses, AddPetStatus200, AddPetStatus200Json, AddPetStatus200Xml, AddPetStatus405, AddPetXmlData } from './ts/models/AddPet.ts'
export type { AddPetRequest } from './ts/models/AddPetRequest.ts'
export type { AddPetRequestStatusEnumKey } from './ts/models/AddPetRequestStatusEnum.ts'
export type { Address } from './ts/models/Address.ts'
export type { ApiResponse } from './ts/models/ApiResponse.ts'
export type { Cat } from './ts/models/Cat.ts'
export type { Category } from './ts/models/Category.ts'
export type { Customer } from './ts/models/Customer.ts'
export type { CustomerParamsStatusEnumKey } from './ts/models/CustomerParamsStatusEnum.ts'
export type { DeleteOrderPathOrderId, DeleteOrderRequestConfig, DeleteOrderResponse, DeleteOrderResponses, DeleteOrderStatus400, DeleteOrderStatus404 } from './ts/models/DeleteOrder.ts'
export type { DeletePetHeaderApiKey, DeletePetPathPetId, DeletePetRequestConfig, DeletePetResponse, DeletePetResponses, DeletePetStatus200, DeletePetStatus400 } from './ts/models/DeletePet.ts'
export type { DeletePetStatus200EnumKey } from './ts/models/DeletePetStatus200Enum.ts'
export type { Dog } from './ts/models/Dog.ts'
export type { FindPetsByStatusQueryStatus, FindPetsByStatusRequestConfig, FindPetsByStatusResponse, FindPetsByStatusResponses, FindPetsByStatusStatus200, FindPetsByStatusStatus200Json, FindPetsByStatusStatus200Xml, FindPetsByStatusStatus400 } from './ts/models/FindPetsByStatus.ts'
export type { FindPetsByStatusStatusKey } from './ts/models/FindPetsByStatusStatus.ts'
export type { FindPetsByTagsQueryPage, FindPetsByTagsQueryPageSize, FindPetsByTagsQueryTags, FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsResponses, FindPetsByTagsStatus200, FindPetsByTagsStatus200Json, FindPetsByTagsStatus200Xml, FindPetsByTagsStatus400 } from './ts/models/FindPetsByTags.ts'
export type { FullAddress } from './ts/models/FullAddress.ts'
export type { GetInventoryRequestConfig, GetInventoryResponse, GetInventoryResponses, GetInventoryStatus200 } from './ts/models/GetInventory.ts'
export type { GetOrderByIdPathOrderId, GetOrderByIdRequestConfig, GetOrderByIdResponse, GetOrderByIdResponses, GetOrderByIdStatus200, GetOrderByIdStatus200Json, GetOrderByIdStatus200Xml, GetOrderByIdStatus400, GetOrderByIdStatus404 } from './ts/models/GetOrderById.ts'
export type { GetPetByIdPathPetId, GetPetByIdRequestConfig, GetPetByIdResponse, GetPetByIdResponses, GetPetByIdStatus200, GetPetByIdStatus200Json, GetPetByIdStatus200Xml, GetPetByIdStatus400, GetPetByIdStatus404 } from './ts/models/GetPetById.ts'
export type { HappyCustomer } from './ts/models/HappyCustomer.ts'
export type { Order } from './ts/models/Order.ts'
export type { OrderHttpStatusEnumKey } from './ts/models/OrderHttpStatusEnum.ts'
export type { OrderParamsStatusEnumKey } from './ts/models/OrderParamsStatusEnum.ts'
export type { OrderStatusKey } from './ts/models/OrderStatus.ts'
export type { Pet } from './ts/models/Pet.ts'
export type { PetNotFound } from './ts/models/PetNotFound.ts'
export type { PetStatusEnumKey } from './ts/models/PetStatusEnum.ts'
export type { PetTypeEnumKey } from './ts/models/PetTypeEnum.ts'
export type { PlaceOrderData, PlaceOrderFormUrlEncodedData, PlaceOrderJsonData, PlaceOrderRequestConfig, PlaceOrderResponse, PlaceOrderResponses, PlaceOrderStatus200, PlaceOrderStatus405, PlaceOrderXmlData } from './ts/models/PlaceOrder.ts'
export type { PlaceOrderPatchData, PlaceOrderPatchFormUrlEncodedData, PlaceOrderPatchJsonData, PlaceOrderPatchRequestConfig, PlaceOrderPatchResponse, PlaceOrderPatchResponses, PlaceOrderPatchStatus200, PlaceOrderPatchStatus405, PlaceOrderPatchXmlData } from './ts/models/PlaceOrderPatch.ts'
export type { Tag } from './ts/models/Tag.ts'
export type { UnhappyCustomer } from './ts/models/UnhappyCustomer.ts'
export type { UpdatePetData, UpdatePetFormUrlEncodedData, UpdatePetJsonData, UpdatePetRequestConfig, UpdatePetResponse, UpdatePetResponses, UpdatePetStatus200, UpdatePetStatus200Json, UpdatePetStatus200Xml, UpdatePetStatus400, UpdatePetStatus404, UpdatePetStatus405, UpdatePetXmlData } from './ts/models/UpdatePet.ts'
export type { UpdatePetWithFormPathPetId, UpdatePetWithFormQueryName, UpdatePetWithFormQueryStatus, UpdatePetWithFormRequestConfig, UpdatePetWithFormResponse, UpdatePetWithFormResponses, UpdatePetWithFormStatus405 } from './ts/models/UpdatePetWithForm.ts'
export type { UploadFileData, UploadFilePathPetId, UploadFileQueryAdditionalMetadata, UploadFileRequestConfig, UploadFileResponse, UploadFileResponses, UploadFileStatus200 } from './ts/models/UploadFile.ts'
export { addPetRequestStatusEnum } from './ts/models/AddPetRequestStatusEnum.ts'
export { customerParamsStatusEnum } from './ts/models/CustomerParamsStatusEnum.ts'
export { deletePetStatus200Enum } from './ts/models/DeletePetStatus200Enum.ts'
export { findPetsByStatusStatus } from './ts/models/FindPetsByStatusStatus.ts'
export { orderHttpStatusEnum } from './ts/models/OrderHttpStatusEnum.ts'
export { orderParamsStatusEnum } from './ts/models/OrderParamsStatusEnum.ts'
export { orderStatus } from './ts/models/OrderStatus.ts'
export { petStatusEnum } from './ts/models/PetStatusEnum.ts'
export { petTypeEnum } from './ts/models/PetTypeEnum.ts'