/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { userSchema } from "../userSchema.ts";

export const createUserStatusDefaultSchema = userSchema

export const createUserResponseSchema = createUserStatusDefaultSchema

export const createUserDataSchema = v.pipe(v.optional(userSchema), v.description("Created user object"))