/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddPetResponse, AddPetStatus405, AddPetBody } from '../types/AddPet'
import type { HttpResponseResolver } from 'msw'
import { getBaseURL } from '../client'
import { http } from 'msw'

export function addPetHandlerResponse200(data: AddPetResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
    headers: {
      'Content-Type': 'application/json'
    },
  })
}

export function addPetHandlerResponse405(data?: AddPetStatus405) {
  return new Response(JSON.stringify(data), {
    status: 405,
  })
}

export function addPetHandler(data?: AddPetResponse | HttpResponseResolver<Record<string, string>, AddPetBody>, options?: { baseURL?: string }) {
  return http.post<Record<string, string>, AddPetBody>(`${options?.baseURL ?? getBaseURL() ?? ''}/pet`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
        headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}
