/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type {
  FindPetsByTagsResponse,
  FindPetsByTagsQueryTags,
  FindPetsByTagsQueryStatus,
  FindPetsByTagsQueryPageSize,
  FindPetsByTagsStatus200,
} from './FindPetsByTags'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import { client } from './.kubb/client'
import { FindPetsByTagsResponse } from './FindPetsByTags'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const findPetsByTagsQueryKey = (params?: {
  tags: FindPetsByTagsQueryTags
  status?: FindPetsByTagsQueryStatus
  pageSize?: FindPetsByTagsQueryPageSize
}) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTags(
  params: { tags: FindPetsByTagsQueryTags; status?: FindPetsByTagsQueryStatus; pageSize?: FindPetsByTagsQueryPageSize },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, params, ...requestConfig })

  return { ...res, data: FindPetsByTagsResponse.parse(res.data) } as { status: 200; data: FindPetsByTagsStatus200; statusText: string }
}

export function findPetsByTagsQueryOptions(
  params?: { tags: FindPetsByTagsQueryTags; status?: FindPetsByTagsQueryStatus; pageSize?: FindPetsByTagsQueryPageSize },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = findPetsByTagsQueryKey(params)
  return queryOptions<
    { status: 200; data: FindPetsByTagsStatus200; statusText: string },
    ResponseErrorConfig<Error>,
    { status: 200; data: FindPetsByTagsStatus200; statusText: string },
    typeof queryKey
  >({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByTags(params!, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags<
  TData = { status: 200; data: FindPetsByTagsStatus200; statusText: string },
  TQueryData = { status: 200; data: FindPetsByTagsStatus200; statusText: string },
  TQueryKey extends QueryKey = FindPetsByTagsQueryKey,
>(
  params?: { tags: FindPetsByTagsQueryTags; status?: FindPetsByTagsQueryStatus; pageSize?: FindPetsByTagsQueryPageSize },
  options: {
    query?: Partial<
      QueryObserverOptions<{ status: 200; data: FindPetsByTagsStatus200; statusText: string }, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>
    > & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? findPetsByTagsQueryKey(params)

  const query = useQuery(
    {
      ...findPetsByTagsQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
