/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWRMutation from 'swr/mutation'
import type { Options, RequestResult, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { DeletePetRequestConfig, DeletePetResponses, DeletePetResponse } from './DeletePet'
import type { SWRMutationConfiguration } from 'swr/mutation'
import { client } from './.kubb/client'

export const deletePetMutationKey = () => [{ url: '/pet/:petId' }] as const

export type DeletePetMutationKey = ReturnType<typeof deletePetMutationKey>

/**
 * {@link /pet/:petId}
 */
export function deletePet<ThrowOnError extends boolean = true>(
  options: Options<DeletePetRequestConfig, ThrowOnError>,
): Promise<RequestResult<DeletePetResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'DELETE', url: '/pet/{petId}', ...config }) as Promise<RequestResult<DeletePetResponses, ThrowOnError>>
}

export type DeletePetMutationArg = DeletePetRequestConfig

/**
 * {@link /pet/:petId}
 */
export function useDeletePet(
  options: {
    mutation?: SWRMutationConfiguration<DeletePetResponse, ResponseErrorConfig<Error>, DeletePetMutationKey | null, DeletePetMutationArg> & {
      throwOnError?: boolean
    }
    client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
    shouldFetch?: boolean
  } = {},
) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = deletePetMutationKey()

  return useSWRMutation<DeletePetResponse, ResponseErrorConfig<Error>, DeletePetMutationKey | null, DeletePetMutationArg>(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: { path, headers } }) => {
      const { data } = await deletePet({ ...config, path, headers, throwOnError: true })
      return data
    },
    mutationOptions,
  )
}
