/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetOrderByIdResponse, GetOrderByIdStatus200, GetOrderByIdStatus200Json, GetOrderByIdStatus200Xml, GetOrderByIdStatus400, GetOrderByIdStatus404 } from "../types/GetOrderById.ts";
import { createOrder } from "./createOrder.ts";
import { faker } from "@faker-js/faker";

export function createGetOrderByIdPathOrderId(data?: bigint): bigint {
  faker.seed([42])

  return data ?? faker.number.bigInt()
}

/**
 * @description successful operation
 */
export function createGetOrderByIdStatus200Json(data?: Partial<GetOrderByIdStatus200Json>): GetOrderByIdStatus200Json {
  faker.seed([42])

  return createOrder(data) as GetOrderByIdStatus200Json
}

/**
 * @description successful operation
 */
export function createGetOrderByIdStatus200Xml(data?: Partial<GetOrderByIdStatus200Xml>): GetOrderByIdStatus200Xml {
  faker.seed([42])

  return createOrder(data) as GetOrderByIdStatus200Xml
}

/**
 * @description successful operation
 */
export function createGetOrderByIdStatus200(_data?: GetOrderByIdStatus200): GetOrderByIdStatus200 {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createGetOrderByIdStatus200Json(), createGetOrderByIdStatus200Xml()])
}

/**
 * @description Invalid ID supplied
 */
export function createGetOrderByIdStatus400() {
  faker.seed([42])

  return undefined
}

/**
 * @description Order not found
 */
export function createGetOrderByIdStatus404() {
  faker.seed([42])

  return undefined
}

export function createGetOrderByIdResponse(_data?: GetOrderByIdResponse): GetOrderByIdResponse {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createGetOrderByIdStatus200(), createGetOrderByIdStatus400(), createGetOrderByIdStatus404()])
}