/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserData, CreateUserResponse, CreateUserStatusDefault } from "../types/CreateUser.ts";
import { createUser } from "./createUser.ts";
import { faker } from "@faker-js/faker";

/**
 * @description successful operation
 */
export function createCreateUserStatusDefault(data?: Partial<CreateUserStatusDefault>): CreateUserStatusDefault {
  faker.seed([42])

  return createUser(data)
}

/**
 * @description Created user object
 */
export function createCreateUserData(data?: Partial<CreateUserData>): CreateUserData {
  faker.seed([42])

  return createUser(data)
}

export function createCreateUserResponse(data?: Partial<CreateUserResponse>): CreateUserResponse {
  faker.seed([42])

  return createCreateUserStatusDefault(data)
}