/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetInventoryResponse, GetInventoryStatus200 } from '../types/GetInventory'
import { fakerEN as faker } from '@faker-js/faker'

/**
   * @description successful operation
   */
  export function createGetInventoryStatus200<TData extends Partial<GetInventoryStatus200> = object>(data?: TData)

{
  faker.seed([42])
  const defaultFakeData = {}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}

export function createGetInventoryResponse(data?: Partial<GetInventoryResponse>): GetInventoryResponse {
  faker.seed([42])

  return createGetInventoryStatus200(data) as GetInventoryResponse
}