/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { FindPetsByTagsQueryTags, FindPetsByTagsResponse, FindPetsByTagsStatus200, FindPetsByTagsStatus200Json, FindPetsByTagsStatus200Xml, FindPetsByTagsStatus400 } from "../types/FindPetsByTags.ts";
import { createPet } from "./createPet.ts";
import { faker } from "@faker-js/faker";

export function createFindPetsByTagsQueryTags(data?: FindPetsByTagsQueryTags): FindPetsByTagsQueryTags {
  faker.seed([42])

  return [
    ...faker.helpers.multiple(() => (faker.string.alpha())),
    ...(data || [])
  ]
}

/**
 * @description successful operation
 */
export function createFindPetsByTagsStatus200Json(data?: FindPetsByTagsStatus200Json): FindPetsByTagsStatus200Json {
  faker.seed([42])

  return [
    ...faker.helpers.multiple(() => (createPet())),
    ...(data || [])
  ]
}

/**
 * @description successful operation
 */
export function createFindPetsByTagsStatus200Xml(data?: FindPetsByTagsStatus200Xml): FindPetsByTagsStatus200Xml {
  faker.seed([42])

  return [
    ...faker.helpers.multiple(() => (createPet())),
    ...(data || [])
  ]
}

/**
 * @description successful operation
 */
export function createFindPetsByTagsStatus200(_data?: FindPetsByTagsStatus200): FindPetsByTagsStatus200 {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createFindPetsByTagsStatus200Json(), createFindPetsByTagsStatus200Xml()])
}

/**
 * @description Invalid tag value
 */
export function createFindPetsByTagsStatus400() {
  faker.seed([42])

  return undefined
}

export function createFindPetsByTagsResponse(_data?: FindPetsByTagsResponse): FindPetsByTagsResponse {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createFindPetsByTagsStatus200(), createFindPetsByTagsStatus400()])
}