/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlaceOrderData, PlaceOrderFormUrlEncodedData, PlaceOrderJsonData, PlaceOrderResponse, PlaceOrderStatus200, PlaceOrderStatus405, PlaceOrderXmlData } from "../types/PlaceOrder.ts";
import { createOrder } from "./createOrder.ts";
import { faker } from "@faker-js/faker";

/**
 * @description successful operation
 */
export function createPlaceOrderStatus200(data?: Partial<PlaceOrderStatus200>): PlaceOrderStatus200 {
  faker.seed([42])

  return createOrder(data)
}

/**
 * @description Invalid input
 */
export function createPlaceOrderStatus405() {
  faker.seed([42])

  return undefined
}

export function createPlaceOrderJsonData(data?: Partial<PlaceOrderJsonData>): PlaceOrderJsonData {
  faker.seed([42])

  return createOrder(data)
}

export function createPlaceOrderXmlData(data?: Partial<PlaceOrderXmlData>): PlaceOrderXmlData {
  faker.seed([42])

  return createOrder(data)
}

export function createPlaceOrderFormUrlEncodedData(data?: Partial<PlaceOrderFormUrlEncodedData>): PlaceOrderFormUrlEncodedData {
  faker.seed([42])

  return createOrder(data)
}

export function createPlaceOrderData(_data?: PlaceOrderData): PlaceOrderData {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createPlaceOrderJsonData(), createPlaceOrderXmlData(), createPlaceOrderFormUrlEncodedData()])
}

export function createPlaceOrderResponse(_data?: PlaceOrderResponse): PlaceOrderResponse {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([createPlaceOrderStatus200(), createPlaceOrderStatus405()])
}