/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Tag } from '../types/Tag'
import { fakerEN as faker } from '@faker-js/faker'

faker.seed([42])

export function createTag<TData extends Partial<Tag> = object>(data?: TData)

{
  const defaultFakeData = {
  id: faker.number.bigInt(),
  name: faker.string.alpha(),
}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}
