/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { CreateUserData, CreateUserResponse, CreateUserStatusDefault } from "../types/CreateUser.ts";
import { user } from "./user.ts";
import { faker } from "@faker-js/faker";

/**
 * @description successful operation
 */
export function createUserStatusDefault(data?: Partial<CreateUserStatusDefault>): CreateUserStatusDefault {
  faker.seed([42])

  return user(data)
}

/**
 * @description Created user object
 */
export function createUserData(data?: Partial<CreateUserData>): CreateUserData {
  faker.seed([42])

  return user(data)
}

export function createUserResponse(data?: Partial<CreateUserResponse>): CreateUserResponse {
  faker.seed([42])

  return createUserStatusDefault(data)
}