/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "../types/User.ts";
import { fakerEN as faker } from "@faker-js/faker";

export function createUser<TData extends Partial<User> = object>(data?: TData)
{
  faker.seed([42])
  const defaultFakeData = {"id": faker.number.bigInt(),"username": faker.string.alpha(),"firstName": faker.string.alpha(),"lastName": faker.string.alpha(),"email": faker.string.alpha(),"password": faker.string.alpha(),"phone": faker.string.alpha(),"userStatus": faker.number.int()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}