/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Category } from "../types/Category.ts";
import { faker } from "@faker-js/faker";

export function createCategory<TData extends Partial<Category> = object>(data?: TData)
{
  faker.seed([42])
  const defaultFakeData = {"id": faker.number.bigInt(),"name": faker.string.alpha()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}