/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteUserResponse } from "../types/DeleteUser.ts";
import { faker } from "@faker-js/faker";

export function deleteUserPathUsername(data?: string): string {
  faker.seed([42])

  return data ?? faker.string.alpha()
}

/**
 * @description Invalid username supplied
 */
export function deleteUserStatus400() {
  faker.seed([42])

  return undefined
}

/**
 * @description User not found
 */
export function deleteUserStatus404() {
  faker.seed([42])

  return undefined
}

export function deleteUserResponse(_data?: DeleteUserResponse): DeleteUserResponse {
  faker.seed([42])

  return faker.helpers.arrayElement<any>([deleteUserStatus400(), deleteUserStatus404()])
}