/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { faker } from "@faker-js/faker";

/**
 * @description successful operation
 */
export function logoutUserStatusDefault() {
  faker.seed([42])

  return undefined
}

export function logoutUserResponse() {
  faker.seed([42])

  return undefined
}