/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { faker } from "@faker-js/faker";

export function updatePetWithFormPathPetId(data?: number): number {
  faker.seed([42])

  return data ?? faker.number.int()
}

export function updatePetWithFormQueryName(data?: string): string {
  faker.seed([42])

  return data ?? faker.string.alpha()
}

export function updatePetWithFormQueryStatus(data?: string): string {
  faker.seed([42])

  return data ?? faker.string.alpha()
}

/**
 * @description Invalid input
 */
export function updatePetWithFormStatus405() {
  faker.seed([42])

  return undefined
}

export function updatePetWithFormResponse() {
  faker.seed([42])

  return undefined
}