/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { parcelSchema } from './parcelSchema.ts'
import { resultStateEnumSchema } from './resultStateEnumSchema.ts'

export const resultSchema = z.object({
  returnId: z.string(),
  state: resultStateEnumSchema,
  parcels: z.array(parcelSchema).optional(),
})