/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { contactDetailsTypeSchema } from './contactDetailsTypeSchema'
import { productDetailsSchema } from './productDetailsSchema'

export const typeARequestSchema = z.object({
  actorId: z.string(),
  contactDetails: contactDetailsTypeSchema,
  productDetails: productDetailsSchema,
})