/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from 'axios'
import useSWR from 'swr'
import type { FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsStatus200 } from './FindPetsByTags'
import type { Client, RequestConfig, ResponseErrorConfig } from 'axios'
import type { SWRConfiguration } from 'swr'

export const findPetsByTagsQueryKey = ({ query }: Omit<FindPetsByTagsRequestConfig, 'url' | 'headers'>) =>
  [{ url: '/pet/findByTags' }, ...(query ? [query] : [])] as const

type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTags({ query }: Omit<FindPetsByTagsRequestConfig, 'url'>, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, query, ...requestConfig })

  return res.data
}

export function findPetsByTagsQueryOptions({ query }: Omit<FindPetsByTagsRequestConfig, 'url'>, config: Partial<RequestConfig> & { client?: Client } = {}) {
  return {
    fetcher: async () => {
      return findPetsByTags({ query }, config)
    },
  }
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags(
  { query }: Omit<FindPetsByTagsRequestConfig, 'url'>,
  options: {
    query?: SWRConfiguration<FindPetsByTagsResponse, ResponseErrorConfig<Error>>
    client?: Partial<RequestConfig> & { client?: Client }
    shouldFetch?: boolean
    immutable?: boolean
  } = {},
) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

  const queryKey = findPetsByTagsQueryKey({ query })

  return useSWR<FindPetsByTagsResponse, ResponseErrorConfig<Error>, FindPetsByTagsQueryKey | null>(shouldFetch ? queryKey : null, {
    ...findPetsByTagsQueryOptions({ query }, config),
    ...(immutable
      ? {
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false,
        }
      : {}),
    ...queryOptions,
  })
}
