/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatePetData, CreatePetResponse, CreatePetStatus201 } from './types/CreatePet'
import { faker } from '@faker-js/faker'

/**
 * @description Created pet
 */
export function createCreatePetStatus201(data?: Partial<CreatePetStatus201>): CreatePetStatus201 {
  return createPet(data)
}

/**
 * @description Pet to add
 */
export function createCreatePetData(data?: Partial<CreatePetData>): Required<CreatePetData> {
  const defaultFakeData = { name: faker.string.alpha(), category: createCategory() }
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<CreatePetData>
}

export function createCreatePetResponse(data?: Partial<CreatePetResponse>): CreatePetResponse {
  return createCreatePetStatus201(data)
}
