/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TypeEnum3Key } from './TypeEnum3.ts'
import type { Vehicle } from './Vehicle.ts'

export type ElectricCar = (Vehicle & {
    type?: TypeEnum3Key;
    /**
     * @description Battery capacity in kWh
     *
     * Format: `float`
     * @type number | undefined
    */
    batteryCapacity?: number;
});