/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { TypeEnumKey } from "./TypeEnum.ts";
import type { Vehicle } from "./Vehicle.ts";

export type Sedan = (Vehicle & {
    type?: TypeEnumKey;
    /**
     * @description Number of seats
     * @type integer | undefined
    */
    seats?: number;
});