/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { typeEnumSchema } from './typeEnumSchema'
import { vehicleSchema } from './vehicleSchema'

export const SUVSchema = vehicleSchema.extend({
  type: typeEnumSchema.optional(),
  offroadCapability: z.boolean().optional().describe('Can handle offroad terrain'),
})