/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaymentMethod } from "./PaymentMethod.ts";
import type { WalletPayment2 } from "./WalletPayment2.ts";

export type WalletPayment = (PaymentMethod & WalletPayment2);