/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PaymentMethod } from './PaymentMethod'

export type WalletPayment = (PaymentMethod & {
    /**
     * @type string | undefined
    */
    walletId?: string;
});