/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export type DeletePetPath = {
  petId: string
}

export type DeletePetStatus204 = void

export type DeletePetOptions = {
  body?: never
  path: DeletePetPath
  query?: never
  headers?: never
}

export type DeletePetResponses = {
  '204': DeletePetStatus204
}

/**
 * @description Union of all possible responses
 */
export type DeletePetResponse = DeletePetStatus204
