/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export type FindPetsByStatusQuery = {
  status?: 'available' | 'pending' | 'sold'
}

export type FindPetsByStatusStatus200 = object

export type FindPetsByStatusOptions = {
  body?: never
  path?: never
  query?: FindPetsByStatusQuery
  headers?: never
}

export type FindPetsByStatusResponses = {
  '200': FindPetsByStatusStatus200
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByStatusResponse = FindPetsByStatusStatus200
