/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const catSchema: z.ZodType = z.object({
  id: z.int(),
  archEnemy: z.union([z.null(), petSchema]).optional(),
  friends: z.array(petSchema).optional(),
})
