/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import useSWRMutation from 'swr/mutation'
import type { UploadFileRequestConfig, UploadFileData, UploadFileResponse } from '../types/UploadFile.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { SWRMutationConfiguration } from 'swr/mutation'
import { uploadFile } from '../clients/uploadFile.ts'

export const uploadFileMutationKey = () => [{ url: '/pet/:petId/uploadImage' }] as const

export type UploadFileMutationKey = ReturnType<typeof uploadFileMutationKey>

export type UploadFileMutationArg = UploadFileRequestConfig

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export function useUploadFile(options: {
  mutation?: SWRMutationConfiguration<UploadFileResponse, ResponseErrorConfig<Error>, UploadFileMutationKey | null, UploadFileMutationArg> & { throwOnError?: boolean },
  client?: Partial<RequestConfig<UploadFileData>> & { client?: Client },
  shouldFetch?: boolean,
} = {}) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = uploadFileMutationKey()

  return useSWRMutation<UploadFileResponse, ResponseErrorConfig<Error>, UploadFileMutationKey | null, UploadFileMutationArg>(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: { path, query, body } }) => {
      return uploadFile({ path, query, body }, config)
    },
    mutationOptions
  )
}