/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { petSchema } from '../petSchema.ts'
import { petStatusEnumSchema } from '../petStatusEnumSchema.ts'

export const findPetsByStatusQueryStatusSchema = petStatusEnumSchema.optional().default("available").describe("Status values that need to be considered for filter")

export const findPetsByStatusStatus200SchemaJson = z.array(petSchema)

export const findPetsByStatusStatus200SchemaXml = z.array(petSchema)

export const findPetsByStatusStatus200Schema = z.union([findPetsByStatusStatus200SchemaJson, findPetsByStatusStatus200SchemaXml])

export const findPetsByStatusStatus400Schema = z.any()

export const findPetsByStatusResponseSchema = z.union([findPetsByStatusStatus200Schema, findPetsByStatusStatus400Schema])