/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsStatus200 } from './FindPetsByTags'
import type { InfiniteData, QueryKey, QueryClient, UseInfiniteQueryOptions, UseInfiniteQueryReturnType } from '@tanstack/react-query'
import type { MaybeRefOrGetter } from 'vue'
import { client } from './.kubb/client'
import { FindPetsByTagsResponse } from './FindPetsByTags'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'
import { toValue } from 'vue'

export const findPetsByTagsInfiniteQueryKey = ({ query }: { query: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url' | 'headers'>['query']> }) =>
  [{ url: '/pet/findByTags' }, ...(query ? [query] : [])] as const

export type FindPetsByTagsInfiniteQueryKey = ReturnType<typeof findPetsByTagsInfiniteQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTagsInfinite({ query }: Omit<FindPetsByTagsRequestConfig, 'url'>, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, query, ...requestConfig })

  return FindPetsByTagsResponse.parse(res.data)
}

export function findPetsByTagsInfiniteQueryOptions(
  { query }: { query: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url'>['query']> },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = findPetsByTagsInfiniteQueryKey({ query })
  return infiniteQueryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, InfiniteData<FindPetsByTagsStatus200>, QueryKey, number>({
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByTagsInfinite({ query: toValue(query) }, { ...config, signal: config.signal ?? signal })
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage, _allPages, lastPageParam) => (Array.isArray(lastPage) && lastPage.length === 0 ? undefined : lastPageParam + 1),
    getPreviousPageParam: (_firstPage, _allPages, firstPageParam) => (firstPageParam <= 1 ? undefined : firstPageParam - 1),
  })
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTagsInfinite<
  TData = InfiniteData<FindPetsByTagsStatus200>,
  TQueryData = FindPetsByTagsStatus200,
  TQueryKey extends QueryKey = FindPetsByTagsInfiniteQueryKey,
>(
  { query }: { query: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url'>['query']> },
  options: {
    query?: Partial<UseInfiniteQueryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? findPetsByTagsInfiniteQueryKey({ query })

  const queryResult = useInfiniteQuery(
    {
      ...findPetsByTagsInfiniteQueryOptions({ query }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseInfiniteQueryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, FindPetsByTagsStatus200, TQueryKey, FindPetsByTagsStatus200>,
    toValue(queryClient),
  ) as UseInfiniteQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
