/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddPetRequestConfig, AddPetResponses } from '../types/AddPet.ts'
import type { DeletePetRequestConfig, DeletePetResponses } from '../types/DeletePet.ts'
import type { FindPetsByStatusRequestConfig, FindPetsByStatusResponses } from '../types/FindPetsByStatus.ts'
import type { GetPetByIdRequestConfig, GetPetByIdResponses } from '../types/GetPetById.ts'
import type { UploadFileRequestConfig, UploadFileResponses } from '../types/UploadFile.ts'
import type { ClientInstance, Options, RequestConfig, RequestResult } from '@kubb/plugin-client/clients/axios'
import { client } from '@kubb/plugin-client/clients/axios'

export class PetClient {
  #config: Partial<RequestConfig> & { client?: ClientInstance }

  constructor(config: Partial<RequestConfig> & { client?: ClientInstance } = {}) {
    this.#config = config
  }

/**
   * @description Add a new pet to the store
   * @summary Add a new pet to the store
   * {@link /pet}
   */
  async addPet<ThrowOnError extends boolean = true>(options: Options<AddPetRequestConfig, ThrowOnError>): Promise<RequestResult<AddPetResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'POST', url: '/pet', ...config }) as Promise<RequestResult<AddPetResponses, ThrowOnError>>
  }

/**
   * @description Multiple status values can be provided with comma separated strings
   * @summary Finds Pets by status
   * {@link /pet/findByStatus}
   */
  async findPetsByStatus<ThrowOnError extends boolean = true>(options: Options<FindPetsByStatusRequestConfig, ThrowOnError>): Promise<RequestResult<FindPetsByStatusResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'GET', url: '/pet/findByStatus', ...config }) as Promise<RequestResult<FindPetsByStatusResponses, ThrowOnError>>
  }

/**
   * @description Returns a single pet
   * @summary Find pet by ID
   * {@link /pet/:petId}
   */
  async getPetById<ThrowOnError extends boolean = true>(options: Options<GetPetByIdRequestConfig, ThrowOnError>): Promise<RequestResult<GetPetByIdResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'GET', url: '/pet/{petId}', ...config }) as Promise<RequestResult<GetPetByIdResponses, ThrowOnError>>
  }

/**
   * @description delete a pet
   * @summary Deletes a pet
   * {@link /pet/:petId}
   */
  async deletePet<ThrowOnError extends boolean = true>(options: Options<DeletePetRequestConfig, ThrowOnError>): Promise<RequestResult<DeletePetResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'DELETE', url: '/pet/{petId}', ...config }) as Promise<RequestResult<DeletePetResponses, ThrowOnError>>
  }

/**
   * @summary uploads an image
   * {@link /pet/:petId/uploadImage}
   */
  async uploadFile<ThrowOnError extends boolean = true>(options: Options<UploadFileRequestConfig, ThrowOnError>): Promise<RequestResult<UploadFileResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'POST', url: '/pet/{petId}/uploadImage', ...config }) as Promise<RequestResult<UploadFileResponses, ThrowOnError>>
  }
}