/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetInventoryRequestConfig, GetInventoryResponses } from '../types/GetInventory.ts'
import type { PlaceOrderRequestConfig, PlaceOrderResponses } from '../types/PlaceOrder.ts'
import type { ClientInstance, Options, RequestConfig, RequestResult } from '@kubb/plugin-client/clients/axios'
import { client } from '@kubb/plugin-client/clients/axios'

export class StoreClient {
  #config: Partial<RequestConfig> & { client?: ClientInstance }

  constructor(config: Partial<RequestConfig> & { client?: ClientInstance } = {}) {
    this.#config = config
  }

/**
   * @description Returns a map of status codes to quantities
   * @summary Returns pet inventories by status
   * {@link /store/inventory}
   */
  async getInventory<ThrowOnError extends boolean = true>(options: Options<GetInventoryRequestConfig, ThrowOnError>): Promise<RequestResult<GetInventoryResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'GET', url: '/store/inventory', ...config }) as Promise<RequestResult<GetInventoryResponses, ThrowOnError>>
  }

/**
   * @description Place a new order in the store
   * @summary Place an order for a pet
   * {@link /store/order}
   */
  async placeOrder<ThrowOnError extends boolean = true>(options: Options<PlaceOrderRequestConfig, ThrowOnError>): Promise<RequestResult<PlaceOrderResponses, ThrowOnError>> {
    const { client: request = client, ...config } = { ...this.#config, ...options }
    return request({ method: 'POST', url: '/store/order', ...config }) as Promise<RequestResult<PlaceOrderResponses, ThrowOnError>>
  }
}