/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { GetOrderByIdPathOrderId, GetOrderByIdStatus200, GetOrderByIdStatus400, GetOrderByIdStatus404 } from '../types/GetOrderById.ts'
import { client } from '../.kubb/client.ts'
import { getOrderByIdResponseSchema } from '../zod/getOrderByIdSchema.ts'

function getGetOrderByIdUrl(orderId: GetOrderByIdPathOrderId) {
  const res = { method: 'GET', url: `/store/order/${orderId}` as const }

  return res
}

/**
 * @description For valid response try integer IDs with value <= 5 or > 10. Other values will generate exceptions.
 * @summary Find purchase order by ID
 * {@link /store/order/:orderId}
 */
export async function getOrderById(orderId: GetOrderByIdPathOrderId, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetOrderByIdStatus200, ResponseErrorConfig<GetOrderByIdStatus400 | GetOrderByIdStatus404>, unknown>({ method: 'GET', url: getGetOrderByIdUrl(orderId).url.toString(), ...requestConfig })

  return getOrderByIdResponseSchema.parse(res.data)
}