/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { LoginUserQueryUsername, LoginUserQueryPassword, LoginUserStatus200, LoginUserStatus400 } from '../types/LoginUser.ts'
import { client } from '../.kubb/client.ts'
import { loginUserResponseSchema } from '../zod/loginUserSchema.ts'

function getLoginUserUrl() {
  const res = { method: 'GET', url: `/user/login` as const }

  return res
}

/**
 * @summary Logs user into the system
 * {@link /user/login}
 */
export async function loginUser(params?: { username?: LoginUserQueryUsername; password?: LoginUserQueryPassword }, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<LoginUserStatus200, ResponseErrorConfig<LoginUserStatus400>, unknown>({ method: 'GET', url: getLoginUserUrl().url.toString(), params, ...requestConfig })

  return loginUserResponseSchema.parse(res.data)
}