/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import type { PlaceOrderData, PlaceOrderStatus200, PlaceOrderStatus405 } from '../types/PlaceOrder.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import { placeOrderResponseSchema, placeOrderDataSchema } from '../zod/placeOrderSchema.ts'

function getPlaceOrderUrl() {
  const res = { method: 'POST', url: `/store/order` as const }

  return res
}

/**
 * @description Place a new order in the store
 * @summary Place an order for a pet
 * {@link /store/order}
 */
export async function placeOrder(data?: PlaceOrderData, config: Partial<RequestConfig<PlaceOrderData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = "application/json", ...requestConfig } = config


  const requestData = placeOrderDataSchema.parse(data)


  const res = await request<PlaceOrderStatus200, ResponseErrorConfig<PlaceOrderStatus405>, PlaceOrderData>({ method: "POST", url: getPlaceOrderUrl().url.toString(), data: requestData, contentType, ...requestConfig })

  return placeOrderResponseSchema.parse(res.data)
}