/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

export const electricCarTypeEnum = {
    ElectricCar: "ElectricCar"
} as const;

export type ElectricCarTypeEnumKey = (typeof electricCarTypeEnum)[keyof typeof electricCarTypeEnum];