/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { SUVTypeEnumKey } from './SUVTypeEnum'
import type { Vehicle } from './Vehicle'

export type SUV = (Vehicle & {
    type?: SUVTypeEnumKey;
    /**
     * @description Can handle offroad terrain
     * @type boolean | undefined
    */
    offroadCapability?: boolean;
});