/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Options, RequestResult } from '../.kubb/client'
import type { UpdatePetOptions, UpdatePetResponses } from '../types/UpdatePet'
import { client } from '../.kubb/client'

/**
 * {@link /pets/:pet_id}
 */
export function updatePet<ThrowOnError extends boolean = true>(options: Options<UpdatePetOptions, ThrowOnError>): Promise<RequestResult<UpdatePetResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'POST', url: '/pets/{petId}', ...config, query: config.query ? { "include_deleted": config.query.includeDeleted, "request_source": config.query.requestSource } : config.query, headers: config.headers ? { "X-Request-ID": config.headers.xRequestID } : config.headers }) as Promise<RequestResult<UpdatePetResponses, ThrowOnError>>
}