/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @description UUID
 * @type string
 */
export type CreatePetsPathUuid = string

/**
 * @description Offset
 * @type integer | undefined
 */
export type CreatePetsQueryOffset = number | undefined

export const createPetsXEXAMPLE = {
  ONE: 'ONE',
  TWO: 'TWO',
  THREE: 'THREE',
} as const

export type CreatePetsXEXAMPLEKey = (typeof createPetsXEXAMPLE)[keyof typeof createPetsXEXAMPLE]

/**
 * @description Header parameters
 * @type string
 */
export type CreatePetsHeaderXEXAMPLE = CreatePetsXEXAMPLEKey

/**
 * @type object
 */
export type CreatePetsData = {
  /**
   * @type string
   */
  name: string
  /**
   * @type string
   */
  tag: string
}

/**
 * @type object
 */
export type CreatePetsRequestConfig = {
  data?: CreatePetsData
  /**
   * @type object
   */
  pathParams: {
    uuid: CreatePetsPathUuid
  }
  /**
   * @type object | undefined
   */
  queryParams?: {
    offset?: CreatePetsQueryOffset
  }
  /**
   * @type object | undefined
   */
  headerParams?: {
    'X-EXAMPLE': CreatePetsHeaderXEXAMPLE
  }
  /**
   * @type string
   */
  url: `/pets/${string}`
}

/**
 * @type object
 */
export type CreatePetsResponses = {
  '201': CreatePetsStatus201
  default: CreatePetsStatusDefault
}
