/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Pet } from './Pet.ts'

/**
 * @description ID of pet to return
 *
 * Format: `int64`
 * @type integer
 */
export type GetPetByIdPathPetId = bigint

/**
 * @type any
 */
export type GetPetByIdStatus400 = any

/**
 * @type any
 */
export type GetPetByIdStatus404 = any

/**
 * @type object
 */
export type GetPetByIdRequestConfig = {
  data?: never
  /**
   * @type object
   */
  pathParams: {
    petId: GetPetByIdPathPetId
  }
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: `/pet/${string}`
}

/**
 * @type object
 */
export type GetPetByIdResponses = {
  /**
   * @type object
   */
  '200': Pet
  '400': GetPetByIdStatus400
  '404': GetPetByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetPetByIdResponse = Pet | GetPetByIdStatus400 | GetPetByIdStatus404
