export type { AddPetData, AddPetFormUrlEncodedData, AddPetJsonData, AddPetRequestConfig, AddPetResponse, AddPetResponses, AddPetStatus200, AddPetStatus200Json, AddPetStatus200Xml, AddPetStatus405, AddPetXmlData } from './AddPet.ts'
export type { AddPetRequest, AddPetRequestStatusEnumKey } from './AddPetRequest.ts'
export type { ApiResponse } from './ApiResponse.ts'
export type { Category } from './Category.ts'
export type { CreatePetsData, CreatePetsHeaderXEXAMPLE, CreatePetsPathUuid, CreatePetsQueryOffset, CreatePetsRequestConfig, CreatePetsResponse, CreatePetsResponses, CreatePetsStatus201, CreatePetsStatusDefault, CreatePetsXEXAMPLEKey } from './CreatePets.ts'
export type { DeleteOrderPathOrderId, DeleteOrderRequestConfig, DeleteOrderResponse, DeleteOrderResponses, DeleteOrderStatus400, DeleteOrderStatus404 } from './DeleteOrder.ts'
export type { DeletePetHeaderApiKey, DeletePetPathPetId, DeletePetRequestConfig, DeletePetResponse, DeletePetResponses, DeletePetStatus400 } from './DeletePet.ts'
export type { FindPetsByStatusQueryStatus, FindPetsByStatusRequestConfig, FindPetsByStatusResponse, FindPetsByStatusResponses, FindPetsByStatusStatus200, FindPetsByStatusStatus200Json, FindPetsByStatusStatus200Xml, FindPetsByStatusStatus400, FindPetsByStatusStatusKey } from './FindPetsByStatus.ts'
export type { FindPetsByTagsHeaderXEXAMPLE, FindPetsByTagsQueryPage, FindPetsByTagsQueryPageSize, FindPetsByTagsQueryTags, FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsResponses, FindPetsByTagsStatus200, FindPetsByTagsStatus200Json, FindPetsByTagsStatus200Xml, FindPetsByTagsStatus400, FindPetsByTagsXEXAMPLEKey } from './FindPetsByTags.ts'
export type { GetInventoryRequestConfig, GetInventoryResponse, GetInventoryResponses, GetInventoryStatus200 } from './GetInventory.ts'
export type { GetOrderByIdPathOrderId, GetOrderByIdRequestConfig, GetOrderByIdResponse, GetOrderByIdResponses, GetOrderByIdStatus200, GetOrderByIdStatus200Json, GetOrderByIdStatus200Xml, GetOrderByIdStatus400, GetOrderByIdStatus404 } from './GetOrderById.ts'
export type { GetPetByIdPathPetId, GetPetByIdRequestConfig, GetPetByIdResponse, GetPetByIdResponses, GetPetByIdStatus200, GetPetByIdStatus200Json, GetPetByIdStatus200Xml, GetPetByIdStatus400, GetPetByIdStatus404 } from './GetPetById.ts'
export type { GetThingsQueryLimit, GetThingsQuerySkip, GetThingsRequestConfig, GetThingsResponse, GetThingsResponses, GetThingsStatus201, GetThingsStatusDefault } from './GetThings.ts'
export type { Order, OrderHttpStatusEnumKey, OrderStatusEnumKey, OrderValueEnumKey } from './Order.ts'
export type { Pet, PetStatusEnumKey } from './Pet.ts'
export type { PetNotFound } from './PetNotFound.ts'
export type { PhoneNumber } from './PhoneNumber.ts'
export type { PhoneWithMaxLength } from './PhoneWithMaxLength.ts'
export type { PhoneWithMaxLengthExplicit } from './PhoneWithMaxLengthExplicit.ts'
export type { PlaceOrderData, PlaceOrderFormUrlEncodedData, PlaceOrderJsonData, PlaceOrderRequestConfig, PlaceOrderResponse, PlaceOrderResponses, PlaceOrderStatus200, PlaceOrderStatus405, PlaceOrderXmlData } from './PlaceOrder.ts'
export type { PlaceOrderPatchData, PlaceOrderPatchFormUrlEncodedData, PlaceOrderPatchJsonData, PlaceOrderPatchRequestConfig, PlaceOrderPatchResponse, PlaceOrderPatchResponses, PlaceOrderPatchStatus200, PlaceOrderPatchStatus405, PlaceOrderPatchXmlData } from './PlaceOrderPatch.ts'
export type { Tag } from './Tag.ts'
export type { UpdatePetData, UpdatePetFormUrlEncodedData, UpdatePetJsonData, UpdatePetRequestConfig, UpdatePetResponse, UpdatePetResponses, UpdatePetStatus200, UpdatePetStatus200Json, UpdatePetStatus200Xml, UpdatePetStatus400, UpdatePetStatus404, UpdatePetStatus405, UpdatePetXmlData } from './UpdatePet.ts'
export type { UpdatePetWithFormPathPetId, UpdatePetWithFormQueryName, UpdatePetWithFormQueryStatus, UpdatePetWithFormRequestConfig, UpdatePetWithFormResponse, UpdatePetWithFormResponses, UpdatePetWithFormStatus405 } from './UpdatePetWithForm.ts'
export type { UploadFileData, UploadFilePathPetId, UploadFileQueryAdditionalMetadata, UploadFileRequestConfig, UploadFileResponse, UploadFileResponses, UploadFileStatus200 } from './UploadFile.ts'
export { addPetRequestStatusEnum } from './AddPetRequest.ts'
export { createPetsXEXAMPLE } from './CreatePets.ts'
export { findPetsByStatusStatus } from './FindPetsByStatus.ts'
export { findPetsByTagsXEXAMPLE } from './FindPetsByTags.ts'
export { orderHttpStatusEnum, orderStatusEnum, orderValueEnum } from './Order.ts'
export { petStatusEnum } from './Pet.ts'