/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { ApiResponse } from './ApiResponse.ts'

/**
 * @description ID of pet to update
 * @type integer
 */
export type UploadFilePathPetId = bigint

/**
 * @description Additional Metadata
 * @type string | undefined
 */
export type UploadFileQueryAdditionalMetadata = string | undefined

/**
 * @type string | undefined
 */
export type UploadFileData = Blob | undefined

/**
 * @type object
 */
export type UploadFileRequestConfig = {
  data?: UploadFileData
  /**
   * @type object
   */
  pathParams: {
    petId: UploadFilePathPetId
  }
  /**
   * @type object | undefined
   */
  queryParams?: {
    additionalMetadata?: UploadFileQueryAdditionalMetadata
  }
  headerParams?: never
  /**
   * @type string
   */
  url: `/pet/${string}/uploadImage`
}

/**
 * @type object
 */
export type UploadFileResponses = {
  /**
   * @type object
   */
  '200': ApiResponse
}

/**
 * @description Union of all possible responses
 */
export type UploadFileResponse = ApiResponse
