/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { categorySchema } from './categorySchema.ts'
import { petStatusEnumSchema } from './petStatusEnumSchema.ts'

export const addPetRequestSchema = z.object({
  id: z.coerce.bigint().optional(),
  name: z.coerce.string(),
  category: categorySchema.optional(),
  photoUrls: z.array(z.coerce.string()),
  tags: z.array(categorySchema).optional(),
  status: petStatusEnumSchema.optional().describe('pet status in the store'),
})