/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from 'swr'
import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { FindPetsByStatusRequestConfig, FindPetsByStatusResponse, FindPetsByStatusStatus200 } from './FindPetsByStatus'
import type { SWRConfiguration } from 'swr'
import { client } from './.kubb/client'

export const findPetsByStatusQueryKey = ({ query }: Omit<FindPetsByStatusRequestConfig, 'headers'> = {}) =>
  [{ url: '/pet/findByStatus' }, ...(query ? [query] : [])] as const

type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>

/**
 * {@link /pet/findByStatus}
 */
export async function findPetsByStatus({ query }: FindPetsByStatusRequestConfig = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByStatusStatus200, ResponseErrorConfig<Error>, unknown>({
    method: 'GET',
    url: `/pet/findByStatus`,
    query,
    ...requestConfig,
  })

  return res.data
}

export function findPetsByStatusQueryOptions({ query }: FindPetsByStatusRequestConfig = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  return {
    fetcher: async () => {
      return findPetsByStatus({ query }, config)
    },
  }
}

/**
 * {@link /pet/findByStatus}
 */
export function useFindPetsByStatus(
  { query }: FindPetsByStatusRequestConfig = {},
  options: {
    query?: SWRConfiguration<FindPetsByStatusResponse, ResponseErrorConfig<Error>>
    client?: Partial<RequestConfig> & { client?: Client }
    shouldFetch?: boolean
    immutable?: boolean
  } = {},
) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

  const queryKey = findPetsByStatusQueryKey({ query })

  return useSWR<FindPetsByStatusResponse, ResponseErrorConfig<Error>, FindPetsByStatusQueryKey | null>(shouldFetch ? queryKey : null, {
    ...findPetsByStatusQueryOptions({ query }, config),
    ...(immutable
      ? {
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false,
        }
      : {}),
    ...queryOptions,
  })
}
