/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import dayjs from 'dayjs'
import type { Pet } from './types/Pet.ts'
import { faker } from '@faker-js/faker'

export function createPet<TData extends Partial<Pet> = object>(data?: TData) {
  const defaultFakeData = {
    id: faker.number.int(),
    name: faker.string.alpha(),
    code: faker.helpers.fromRegExp('^[A-Z]{3}$'),
    shipDate: dayjs(faker.date.anytime()).format('YYYY-MM-DD'),
    category: createCategory(),
    status: faker.helpers.arrayElement<NonNullable<Pet>['status']>(['available', 'pending', 'sold']),
  }
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}
