/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ClientConfig } from '../.kubb/client.ts'
import { PetClient } from './petClient.ts'
import { StoreClient } from './storeClient.ts'

export class PetStore {
  readonly petClient: PetClient
  readonly storeClient: StoreClient

  constructor(config: ClientConfig = {}) {
    this.petClient = new PetClient(config)
    this.storeClient = new StoreClient(config)
  }
}