/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddPetBody, AddPetBodyFormUrlEncoded, AddPetBodyJson, AddPetBodyXml, AddPetResponse, AddPetStatus200, AddPetStatus200Json, AddPetStatus200Xml, AddPetStatus405 } from '../types/AddPet'
import { createAddPetRequest } from './createAddPetRequest'
import { createPet } from './createPet'
import { fakerEN as faker } from '@faker-js/faker'

/**
 * @description Successful operation
 */
export function createAddPetStatus200Json(data?: Partial<AddPetStatus200Json>): AddPetStatus200Json {
  return createPet(data) as AddPetStatus200Json
}

/**
 * @description Successful operation
 */
export function createAddPetStatus200Xml(data?: Partial<AddPetStatus200Xml>): AddPetStatus200Xml {
  return createPet(data) as AddPetStatus200Xml
}

/**
 * @description Successful operation
 */
export function createAddPetStatus200(data?: Partial<AddPetStatus200>): AddPetStatus200 {
  return (data ?? faker.helpers.arrayElement([createAddPetStatus200Json(), createAddPetStatus200Xml()])) as AddPetStatus200
}

/**
 * @description Invalid input
 */
export function createAddPetStatus405() {
  return undefined
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyJson(data?: Partial<AddPetBodyJson>): AddPetBodyJson {
  return createAddPetRequest(data) as AddPetBodyJson
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyXml(data?: Partial<AddPetBodyXml>): AddPetBodyXml {
  return createPet(data) as AddPetBodyXml
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyFormUrlEncoded(data?: Partial<AddPetBodyFormUrlEncoded>): AddPetBodyFormUrlEncoded {
  return createPet(data) as AddPetBodyFormUrlEncoded
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBody(data?: Partial<AddPetBody>): AddPetBody {
  return (data ?? faker.helpers.arrayElement([createAddPetBodyJson(), createAddPetBodyXml(), createAddPetBodyFormUrlEncoded()])) as AddPetBody
}

export function createAddPetResponse(data?: Partial<AddPetResponse>): AddPetResponse {
  return (data ?? faker.helpers.arrayElement([createAddPetStatus200(), createAddPetStatus405()])) as AddPetResponse
}
