/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import RandExp from 'randexp'
import type { Pet } from '../types/Pet'
import { createCategory } from './createCategory'
import { createPetStatusEnum } from './createPetStatusEnum'
import { createTag } from './createTag'
import { fakerEN as faker } from '@faker-js/faker'

export function createPet<TData extends Partial<Pet> = object>(data?: TData)

{
  const defaultFakeData = {
  id: faker.number.bigInt(),
  name: faker.string.alpha(),
  log: new RandExp("^[A-Za-z0-9()\\[\\]'\"][-A-Za-z0-9_. \\/()\\[\\]]{0,40}[A-Za-z0-9()\\[\\]'\"]$").gen(),
  category: createCategory(),
  photoUrls: faker.helpers.multiple(() => (faker.string.alpha())),
  tags: faker.helpers.multiple(() => (createTag())),
  status: createPetStatusEnum(),
}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Omit<typeof defaultFakeData, keyof TData> & TData
}