/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type object
 */
export type AddPetStatus500 = object

/**
 * @type object
 */
export type AddPetRequestConfig = {
  data?: Pet
  pathParams?: never
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: '/pet'
}

/**
 * @type object
 */
export type AddPetResponses = {
  '200': Pet
  '422': HttpValidationError
  '500': AddPetStatus500
}

/**
 * @description Union of all possible responses
 */
export type AddPetResponse = Pet | HttpValidationError | AddPetStatus500
