/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type object
 */
export type CreateUserStatus200 = Omit<
  NonNullable<{
    /**
     * @type string
     */
    readonly id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    password: string
  }>,
  'password'
>

/**
 * @description The user to create
 * @type object
 */
export type CreateUserData = Omit<
  NonNullable<{
    /**
     * @type string
     */
    readonly id: string
    /**
     * @type string
     */
    name: string
    /**
     * @type string
     */
    password: string
  }>,
  'id'
>

/**
 * @type object
 */
export type CreateUserRequestConfig = {
  body: CreateUserData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type CreateUserResponses = {
  '200': CreateUserStatus200
}

/**
 * @description Union of all possible responses
 */
export type CreateUserResponse = CreateUserStatus200
