/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import useSWR from 'swr'
import type { Options, RequestResult, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { FindPetsByTagsRequestConfig, FindPetsByTagsResponses, FindPetsByTagsResponse } from './FindPetsByTags'
import type { SWRConfiguration } from 'swr'
import { client } from './.kubb/client'

export const findPetsByTagsQueryKey = ({ query }: Omit<FindPetsByTagsRequestConfig, 'headers'>) =>
  [{ url: '/pet/findByTags' }, ...(query ? [query] : [])] as const

type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * {@link /pet/findByTags}
 */
export function findPetsByTags<ThrowOnError extends boolean = true>(
  options: Options<FindPetsByTagsRequestConfig, ThrowOnError>,
): Promise<RequestResult<FindPetsByTagsResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/pet/findByTags', ...config }) as Promise<RequestResult<FindPetsByTagsResponses, ThrowOnError>>
}

export function findPetsByTagsQueryOptions(
  { query }: FindPetsByTagsRequestConfig,
  config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {},
) {
  return {
    fetcher: async () => {
      const { data } = await findPetsByTags({ ...config, query, throwOnError: true })
      return data
    },
  }
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags(
  { query }: FindPetsByTagsRequestConfig,
  options: {
    query?: SWRConfiguration<FindPetsByTagsResponse, ResponseErrorConfig<Error>>
    client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
    shouldFetch?: boolean
    immutable?: boolean
  } = {},
) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

  const queryKey = findPetsByTagsQueryKey({ query })

  return useSWR<FindPetsByTagsResponse, ResponseErrorConfig<Error>, FindPetsByTagsQueryKey | null>(shouldFetch ? queryKey : null, {
    ...findPetsByTagsQueryOptions({ query }, config),
    ...(immutable
      ? {
          revalidateIfStale: false,
          revalidateOnFocus: false,
          revalidateOnReconnect: false,
        }
      : {}),
    ...queryOptions,
  })
}
