/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Category } from './Category'
import type { PetStatusEnumKey } from './PetStatusEnum'
import type { Tag } from './Tag'

export type Pet = {
    /**
     * @description
     * Format: `int64`
     * @example 10
     * @type integer | undefined
    */
    id?: bigint;
    /**
     * @example doggie
     * @type string
    */
    name: string;
    /**
     * @minLength 2
     * @maxLength 42
     * @pattern ^[A-Za-z0-9()\[\]'"][-A-Za-z0-9_. \/()\[\]]{0,40}[A-Za-z0-9()\[\]'"]$
     * @example my_log_destination
     * @type string | undefined
    */
    log?: string;
    category?: Category;
    photoUrls: string[];
    tags?: Tag[];
    /**
     * @description pet status in the store
    */
    status?: PetStatusEnumKey;
};