/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import useSWR from 'swr'
import type { Options, RequestResult, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { FindPetsByStatusRequestConfig, FindPetsByStatusResponses, FindPetsByStatusResponse, FindPetsByStatusStatus400 } from '../types/FindPetsByStatus.ts'
import type { SWRConfiguration } from 'swr'
import { client } from '../.kubb/client.ts'
import { findPetsByStatusResponseSchema } from '../zod/findPetsByStatusSchema.ts'

export const findPetsByStatusQueryKey = ({ query }: Omit<FindPetsByStatusRequestConfig, 'headers'> = {}) => [{ url: '/pet/findByStatus' }, ...(query ? [query] : [])] as const

type FindPetsByStatusQueryKey = ReturnType<typeof findPetsByStatusQueryKey>

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export function findPetsByStatus<ThrowOnError extends boolean = true>(options: Options<FindPetsByStatusRequestConfig, ThrowOnError>): Promise<RequestResult<FindPetsByStatusResponses, ThrowOnError>> {
  const { client: request = client, ...config } = options

  return request({ method: 'GET', url: '/pet/findByStatus', parser: { response: (data: unknown) => findPetsByStatusResponseSchema.parse(data) }, ...config }) as Promise<RequestResult<FindPetsByStatusResponses, ThrowOnError>>
}

export function findPetsByStatusQueryOptions({ query }: FindPetsByStatusRequestConfig = {}, config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {}) {
  return {
    fetcher: async () => {
      const { data } = await findPetsByStatus({ ...config, query, throwOnError: true })
      return data
    },
  }
}

/**
 * @description Multiple status values can be provided with comma separated strings
 * @summary Finds Pets by status
 * {@link /pet/findByStatus}
 */
export function useFindPetsByStatus({ query }: FindPetsByStatusRequestConfig = {}, options: {
  query?: SWRConfiguration<FindPetsByStatusResponse, ResponseErrorConfig<FindPetsByStatusStatus400>>,
  client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>,
  shouldFetch?: boolean,
  immutable?: boolean
} = {}) {
  const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

  const queryKey = findPetsByStatusQueryKey({ query })

  return useSWR<FindPetsByStatusResponse, ResponseErrorConfig<FindPetsByStatusStatus400>, FindPetsByStatusQueryKey | null>(
   shouldFetch ? queryKey : null,
   {
     ...findPetsByStatusQueryOptions({ query }, config),
     ...(immutable ? {
         revalidateIfStale: false,
         revalidateOnFocus: false,
         revalidateOnReconnect: false
       } : { }),
     ...queryOptions,
   }
  )
}