/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import useSWRMutation from 'swr/mutation'
import type { UploadFileRequestConfig, UploadFileData, UploadFileResponse, UploadFileStatus200 } from '../types/UploadFile.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { SWRMutationConfiguration } from 'swr/mutation'
import type { z } from 'zod'
import { uploadFileResponseSchema, uploadFileDataSchema } from '../zod/uploadFileSchema.ts'

export const uploadFileMutationKey = () => [{ url: '/pet/:petId/uploadImage' }] as const

export type UploadFileMutationKey = ReturnType<typeof uploadFileMutationKey>

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile({ path, query, body }: Omit<UploadFileRequestConfig, 'url'>, config: Partial<RequestConfig<UploadFileData>> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const { petId } = path

  const requestData = uploadFileDataSchema.parse(body)

  const res = await request<UploadFileStatus200, ResponseErrorConfig<Error>, z.input<typeof uploadFileDataSchema>>({ method: 'POST', url: `/pet/${petId}/uploadImage`, query, body: requestData, ...requestConfig, headers: { 'Content-Type': 'application/octet-stream', ...requestConfig.headers } })

  return uploadFileResponseSchema.parse(res.data)
}

export type UploadFileMutationArg = Omit<UploadFileRequestConfig, 'url'>

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export function useUploadFile(options: {
  mutation?: SWRMutationConfiguration<UploadFileResponse, ResponseErrorConfig<Error>, UploadFileMutationKey | null, UploadFileMutationArg> & { throwOnError?: boolean },
  client?: Partial<RequestConfig<UploadFileData>> & { client?: Client },
  shouldFetch?: boolean,
} = {}) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = uploadFileMutationKey()

  return useSWRMutation<UploadFileResponse, ResponseErrorConfig<Error>, UploadFileMutationKey | null, UploadFileMutationArg>(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: { path, query, body } }) => {
      return uploadFile({ path, query, body }, config)
    },
    mutationOptions
  )
}