/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { DeletePetsPetidResponse } from './DeletePetsPetid'
import { http } from 'msw'

export function deletePetsPetidHandlerResponse200(data?: DeletePetsPetidResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
  })
}

export function deletePetsPetidHandler(
  data?: string | number | boolean | null | object | ((info: Parameters<Parameters<typeof http.delete>[1]>[0]) => Response | Promise<Response>),
) {
  return http.delete(`/pets/:petId`, function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data), {
      status: 200,
    })
  })
}
