/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod/mini'
import { electricCarTypeEnumSchema } from './electricCarTypeEnumSchema'
import { vehicleSchema } from './vehicleSchema'

export const electricCarSchema = z.extend(vehicleSchema, {
  type: z.optional(electricCarTypeEnumSchema),
  batteryCapacity: z.optional(z.number()),
})