/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod/mini'
import { sedanTypeEnumSchema } from './sedanTypeEnumSchema.ts'
import { vehicleSchema } from './vehicleSchema.ts'

export const sedanSchema = z.extend(vehicleSchema, {
  type: z.optional(sedanTypeEnumSchema),
  seats: z.optional(z.int()),
})