/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod/mini'
import { SUVTypeEnumSchema } from './SUVTypeEnumSchema.ts'
import { vehicleSchema } from './vehicleSchema.ts'

export const SUVSchema = z.extend(vehicleSchema, {
  type: z.optional(SUVTypeEnumSchema),
  offroadCapability: z.optional(z.boolean()),
})