/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import type { UpdatePetRequestConfig, UpdatePetPathPetId, UpdatePetData, UpdatePetStatus200 } from '../types/UpdatePet.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'

function getUpdatePetUrl({ petId }: { petId: UpdatePetPathPetId }) {
  const pet_id = petId

  const res = { method: 'POST', url: `/pets/${pet_id}` as const }

  return res
}

/**
 * {@link /pets/:pet_id}
 */
export async function updatePet({ path, query, body }: Omit<UpdatePetRequestConfig, 'url'>, config: Partial<RequestConfig<UpdatePetData>> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const mappedParams = query ? { "include_deleted": query.includeDeleted, "request_source": query.requestSource } : undefined

  const requestBody = body

  const res = await request<UpdatePetStatus200, ResponseErrorConfig<Error>, UpdatePetData>({ method: 'POST', url: getUpdatePetUrl(path).url.toString(), query: mappedParams, body: requestBody, ...requestConfig })

  return res.data
}