/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import useSWR from "swr";
import type { Client, RequestConfig, ResponseErrorConfig } from "../.kubb/fetch.ts";
import type { GetInventoryResponse } from "../types/GetInventory.ts";
import type { SWRConfiguration } from "swr";
import { fetch } from "../.kubb/fetch.ts";

export const getInventoryQueryKey = () => [{ url: '/store/inventory' }] as const

type GetInventoryQueryKey = ReturnType<typeof getInventoryQueryKey>

/**
 * @description Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 * {@link /store/inventory}
 */
export async function getInventory(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config




  const res = await request<GetInventoryResponse, ResponseErrorConfig<Error>, unknown>({ method: "GET", url: `/store/inventory`, ...requestConfig })

  return res.data
}

export function getInventoryQueryOptions(config: Partial<RequestConfig> & { client?: Client } = {}) {

        return {
          fetcher: async () => {
            return getInventory(config)
          },
        }

}

/**
 * @description Returns a map of status codes to quantities
 * @summary Returns pet inventories by status
 * {@link /store/inventory}
 */
export function useGetInventory(options: {
  query?: SWRConfiguration<GetInventoryResponse, ResponseErrorConfig<Error>>,
  client?: Partial<RequestConfig> & { client?: Client },
  shouldFetch?: boolean,
  immutable?: boolean
} = {}) {

         const { query: queryOptions, client: config = {}, shouldFetch = true, immutable } = options ?? {}

         const queryKey = getInventoryQueryKey()

         return useSWR<GetInventoryResponse, ResponseErrorConfig<Error>, GetInventoryQueryKey | null>(
          shouldFetch ? queryKey : null,
          {
            ...getInventoryQueryOptions(config),
            ...(immutable ? {
                revalidateIfStale: false,
                revalidateOnFocus: false,
                revalidateOnReconnect: false
              } : { }),
            ...queryOptions,
          }
         )

}