/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { orderStatusEnumSchema } from './orderStatusEnumSchema.ts'

export const orderSchema = z.object({
  id: z.bigint().optional().meta({ examples: [10] }),
  petId: z.bigint().optional().meta({ examples: [198772] }),
  quantity: z.int().optional().meta({ examples: [7] }),
  shipDate: z.iso.datetime().optional(),
  status: orderStatusEnumSchema.optional().describe('Order Status').meta({ examples: ['approved'] }),
  complete: z.boolean().optional(),
})

export type OrderSchemaType = z.infer<typeof orderSchema>