/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { createPetsHandler } from './createPetsHandler'
import { listPetsHandler } from './listPetsHandler'
import { showPetByIdHandler } from './showPetByIdHandler'

export const handlers = [listPetsHandler(), createPetsHandler(), showPetByIdHandler()] as const
