/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { UpdatePetWithFormRequestConfig, UpdatePetWithFormData, UpdatePetWithFormResponse, UpdatePetWithFormStatus200 } from './UpdatePetWithForm'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from 'custom-query'
import type { MaybeRefOrGetter } from 'vue'
import { client } from './.kubb/client'
import { UpdatePetWithFormResponse, UpdatePetWithFormData } from './UpdatePetWithForm'
import { queryOptions, useQuery } from 'custom-query'
import { toValue } from 'vue'

export const updatePetWithFormQueryKey = ({
  path,
  body,
  query,
}: {
  path: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['path']>
  body: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['body']>
  query?: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['query']>
}) => [{ url: '/pet/:petId', params: path }, ...(query ? [query] : []), ...(body ? [body] : [])] as const

export type UpdatePetWithFormQueryKey = ReturnType<typeof updatePetWithFormQueryKey>

/**
 * {@link /pet/:petId}
 */
export async function updatePetWithForm(
  { path, query, body }: Omit<UpdatePetWithFormRequestConfig, 'url'>,
  config: Partial<RequestConfig<UpdatePetWithFormData>> & { client?: Client } = {},
) {
  const { client: request = client, ...requestConfig } = config

  const { petId } = path

  const requestBody = UpdatePetWithFormData.parse(body)

  const res = await request<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, z.input<typeof UpdatePetWithFormData>>({
    method: 'POST',
    url: `/pet/${petId}`,
    query,
    body: requestBody,
    ...requestConfig,
  })

  return UpdatePetWithFormResponse.parse(res.data)
}

export function updatePetWithFormQueryOptions(
  {
    path,
    body,
    query,
  }: {
    path: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['path']>
    body: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['body']>
    query?: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['query']>
  },
  config: Partial<RequestConfig<UpdatePetWithFormData>> & { client?: Client } = {},
) {
  const queryKey = updatePetWithFormQueryKey({ path, body, query })
  return queryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, UpdatePetWithFormStatus200>({
    enabled: () => !!toValue(path),
    queryKey,
    queryFn: async ({ signal }) => {
      return updatePetWithForm({ path: toValue(path), body: toValue(body), query: toValue(query) }, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /pet/:petId}
 */
export function useUpdatePetWithForm<
  TData = UpdatePetWithFormStatus200,
  TQueryData = UpdatePetWithFormStatus200,
  TQueryKey extends QueryKey = UpdatePetWithFormQueryKey,
>(
  {
    path,
    body,
    query,
  }: {
    path: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['path']>
    body: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['body']>
    query?: MaybeRefOrGetter<Omit<UpdatePetWithFormRequestConfig, 'url'>['query']>
  },
  options: {
    query?: Partial<UseQueryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig<UpdatePetWithFormData>> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? updatePetWithFormQueryKey({ path, body, query })

  const result = useQuery(
    {
      ...updatePetWithFormQueryOptions({ path, body, query }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseQueryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, TData, UpdatePetWithFormStatus200, TQueryKey>,
    toValue(queryClient),
  ) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  result.queryKey = queryKey as TQueryKey

  return result
}
