/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import type { RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { UpdatePetWithFormOptions, UpdatePetWithFormStatus200 } from './UpdatePetWithForm'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from 'custom-query'
import type { MaybeRefOrGetter } from 'vue'
import { updatePetWithForm } from './clients/updatePetWithForm'
import { queryOptions, useQuery } from 'custom-query'
import { toValue } from 'vue'

export const updatePetWithFormQueryKey = ({
  path,
  body,
  query,
}: {
  path: MaybeRefOrGetter<Omit<UpdatePetWithFormOptions, 'headers'>['path']>
  body: MaybeRefOrGetter<Omit<UpdatePetWithFormOptions, 'headers'>['body']>
  query?: MaybeRefOrGetter<Omit<UpdatePetWithFormOptions, 'headers'>['query']>
}) => [{ url: '/pet/:petId', params: path }, ...(query ? [query] : []), ...(body ? [body] : [])] as const

export type UpdatePetWithFormQueryKey = ReturnType<typeof updatePetWithFormQueryKey>

export function updatePetWithFormQueryOptions(
  {
    path,
    body,
    query,
  }: {
    path: MaybeRefOrGetter<UpdatePetWithFormOptions['path']>
    body: MaybeRefOrGetter<UpdatePetWithFormOptions['body']>
    query?: MaybeRefOrGetter<UpdatePetWithFormOptions['query']>
  },
  config: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>> = {},
) {
  const queryKey = updatePetWithFormQueryKey({ path, body, query })
  return queryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, UpdatePetWithFormStatus200>({
    queryKey,
    queryFn: async ({ signal }) => {
      const { data } = await updatePetWithForm({
        ...config,
        path: toValue(path),
        query: toValue(query),
        body: toValue(body),
        signal: config.signal ?? signal,
        throwOnError: true,
      })
      return data
    },
  })
}

/**
 * {@link /pet/:petId}
 */
export function useUpdatePetWithForm<
  TData = UpdatePetWithFormStatus200,
  TQueryData = UpdatePetWithFormStatus200,
  TQueryKey extends QueryKey = UpdatePetWithFormQueryKey,
>(
  {
    path,
    body,
    query,
  }: {
    path: MaybeRefOrGetter<UpdatePetWithFormOptions['path']>
    body: MaybeRefOrGetter<UpdatePetWithFormOptions['body']>
    query?: MaybeRefOrGetter<UpdatePetWithFormOptions['query']>
  },
  options: {
    query?: Partial<UseQueryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey =
    (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? updatePetWithFormQueryKey({ path, body, query })

  const queryResult = useQuery(
    {
      ...updatePetWithFormQueryOptions({ path, body, query }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseQueryOptions<UpdatePetWithFormStatus200, ResponseErrorConfig<Error>, TData, UpdatePetWithFormStatus200, TQueryKey>,
    toValue(queryClient),
  ) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
