export { Client } from './components/Client.tsx'
export { classClientGenerator } from './generators/classClientGenerator.tsx'
export { clientGenerator } from './generators/clientGenerator.tsx'
export { groupedClientGenerator } from './generators/groupedClientGenerator.tsx'
export { operationsGenerator } from './generators/operationsGenerator.tsx'
export { staticClassClientGenerator } from './generators/staticClassClientGenerator.tsx'
export { default, pluginClient, pluginClientName } from './plugin.ts'
export { resolverClient } from './resolvers/resolverClient.ts'
export type { ClientImportPath, PluginClient, ResolverClient } from './types.ts'
export * as axiosClient from './clients/axios.ts'
export * as fetchClient from './clients/fetch.ts'
