/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { addPetHandler } from './addPetHandler'
import { deletePetHandler } from './deletePetHandler'
import { findPetsByStatusHandler } from './findPetsByStatusHandler'
import { getInventoryHandler } from './getInventoryHandler'
import { getPetByIdHandler } from './getPetByIdHandler'
import { placeOrderHandler } from './placeOrderHandler'
import { uploadFileHandler } from './uploadFileHandler'

export function createHandlers(options?: { baseURL?: string }) {
  return [addPetHandler(undefined, options), findPetsByStatusHandler(undefined, options), getPetByIdHandler(undefined, options), deletePetHandler(undefined, options), uploadFileHandler(undefined, options), getInventoryHandler(undefined, options), placeOrderHandler(undefined, options)] as const
}

export const handlers = createHandlers()
