/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { addPetHandler } from "./addPetHandler.ts";
import { createUserHandler } from "./createUserHandler.ts";
import { createUsersWithListInputHandler } from "./createUsersWithListInputHandler.ts";
import { deleteOrderHandler } from "./deleteOrderHandler.ts";
import { deletePetHandler } from "./deletePetHandler.ts";
import { deleteUserHandler } from "./deleteUserHandler.ts";
import { findPetsByStatusHandler } from "./findPetsByStatusHandler.ts";
import { findPetsByTagsHandler } from "./findPetsByTagsHandler.ts";
import { getInventoryHandler } from "./getInventoryHandler.ts";
import { getOrderByIdHandler } from "./getOrderByIdHandler.ts";
import { getPetByIdHandler } from "./getPetByIdHandler.ts";
import { getUserByNameHandler } from "./getUserByNameHandler.ts";
import { loginUserHandler } from "./loginUserHandler.ts";
import { logoutUserHandler } from "./logoutUserHandler.ts";
import { placeOrderHandler } from "./placeOrderHandler.ts";
import { updatePetHandler } from "./updatePetHandler.ts";
import { updatePetWithFormHandler } from "./updatePetWithFormHandler.ts";
import { updateUserHandler } from "./updateUserHandler.ts";
import { uploadFileHandler } from "./uploadFileHandler.ts";

export const handlers = [updatePetHandler(),addPetHandler(),findPetsByStatusHandler(),findPetsByTagsHandler(),getPetByIdHandler(),updatePetWithFormHandler(),deletePetHandler(),uploadFileHandler(),getInventoryHandler(),placeOrderHandler(),getOrderByIdHandler(),deleteOrderHandler(),createUserHandler(),createUsersWithListInputHandler(),loginUserHandler(),logoutUserHandler(),getUserByNameHandler(),updateUserHandler(),deleteUserHandler()] as const