/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { addPetHandler } from './addPetHandler'
import { deletePetHandler } from './deletePetHandler'
import { findPetsByStatusHandler } from './findPetsByStatusHandler'
import { getInventoryHandler } from './getInventoryHandler'
import { getPetByIdHandler } from './getPetByIdHandler'
import { placeOrderHandler } from './placeOrderHandler'
import { uploadFileHandler } from './uploadFileHandler'

export const handlers = [addPetHandler(),findPetsByStatusHandler(),getPetByIdHandler(),deletePetHandler(),uploadFileHandler(),getInventoryHandler(),placeOrderHandler()] as const