/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletePetRequestConfig, DeletePetResponse } from '../types/DeletePet.ts'

export function deletePet({ path, headers }: DeletePetRequestConfig, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<DeletePetResponse> {
  return cy.request<DeletePetResponse>({
    method: 'DELETE',
    url: `/pet/${path.petId}`,
    headers: headers ? { "api_key": headers.apiKey } : headers,
    ...options
  }).then((res) => res.body)
}