/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetPetByIdPathPetId, GetPetByIdResponse } from "../types/GetPetById.ts";
import type { Pet } from "../types/Pet.ts";

export function getPetById(petId: GetPetByIdPathPetId, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<GetPetByIdResponse> {
  return cy.request<GetPetByIdResponse>({
    method: 'GET',
    url: `/pet/${petId}`,
    ...options
  }).then((res) => res.body)
}