/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiResponse } from '../types/ApiResponse.ts'
import type { UploadFileRequestConfig } from '../types/UploadFile.ts'

export function uploadFile({ path, query, body }: UploadFileRequestConfig, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<ApiResponse> {
  return cy.request<ApiResponse>({
    method: 'POST',
    url: `/pet/${path.petId}/uploadImage`,
    qs: query,
    body,
    ...options
  }).then((res) => res.body)
}