/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ClientConfig } from '../.kubb/client.ts'
import { PetClient } from './petClient.ts'
import { StoreClient } from './storeClient.ts'

export class PetStore {
  readonly pet: PetClient
  readonly store: StoreClient

  constructor(config: ClientConfig = {}) {
    this.pet = new PetClient(config)
    this.store = new StoreClient(config)
  }
}