/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Config } from '../Config.ts'
import type { ConfigCreate } from '../ConfigCreate.ts'

/**
 * @type object
*/
export type CreateConfigV20250RequestConfig = {
    body: ConfigCreate;
    path?: never;
    query?: never;
    headers?: never;
};

/**
 * @type object
*/
export type CreateConfigV20250Responses = {
    "201": Config;
};

/**
 * @description Union of all possible responses
*/
export type CreateConfigV20250Response = Config;