/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NotificationTypeA } from './NotificationTypeA.ts'
import type { NotificationTypeB } from './NotificationTypeB.ts'

/**
 * @type array
*/
export type GetNotificationsStatus200 = (NotificationTypeA | NotificationTypeB)[];

/**
 * @type object
*/
export type GetNotificationsRequestConfig = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
    /**
     * @type string
    */
    url: "/notifications";
};

/**
 * @type object
*/
export type GetNotificationsResponses = {
    "200": GetNotificationsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetNotificationsResponse = GetNotificationsStatus200;