/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { NotificationTypeAParamsChannelEnumKey } from "./NotificationTypeAParamsChannelEnum.ts";

/**
 * @type object
*/
export type NotificationTypeB = {
    /**
     * @type string
    */
    type: string;
    /**
     * @type object
    */
    params: {
        channel: NotificationTypeAParamsChannelEnumKey;
        /**
         * @type string
        */
        messageB: string;
    };
};