/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeleteUserResponse, DeleteUserPathUsername, DeleteUserStatus400, DeleteUserStatus404 } from "../types/DeleteUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { MaybeRefOrGetter } from "vue";
import { deleteUser } from "../clients/deleteUser.ts";
import { useMutation } from "@tanstack/vue-query";

export const deleteUserMutationKey = () => [{ url: '/user/:username' }] as const

export type DeleteUserMutationKey = ReturnType<typeof deleteUserMutationKey>

/**
 * @description This can only be done by the logged in user.
 * @summary Delete user
 * {@link /user/:username}
 */
export function useDeleteUser<TContext>(options: {
  mutation?: MutationObserverOptions<DeleteUserResponse, ResponseErrorConfig<DeleteUserStatus400 | DeleteUserStatus404>, {username: MaybeRefOrGetter<DeleteUserPathUsername>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
} = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? deleteUserMutationKey()

          return useMutation<DeleteUserResponse, ResponseErrorConfig<DeleteUserStatus400 | DeleteUserStatus404>, {username: DeleteUserPathUsername}, TContext>({
            mutationFn: async({ username }) => {
              return deleteUser(username, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)

}