/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { DeletePetRequestConfig, DeletePetResponse, DeletePetStatus400 } from '../types/DeletePet.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { deletePet } from '../clients/deletePet.ts'
import { useMutation } from '@tanstack/vue-query'

export const deletePetMutationKey = () => [{ url: '/pet/:petId' }] as const

/**
 * @description delete a pet
 * @summary Deletes a pet
 * {@link /pet/:petId}
 */
export function useDeletePet<TContext>(options: {
  mutation?: MutationObserverOptions<DeletePetResponse, ResponseErrorConfig<DeletePetStatus400>, Omit<DeletePetRequestConfig, 'url'>, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig> & { client?: Client },
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? deletePetMutationKey()

  return useMutation<DeletePetResponse, ResponseErrorConfig<DeletePetStatus400>, Omit<DeletePetRequestConfig, 'url'>, TContext>({
    mutationFn: async({ path, headers }) => {
      return deletePet({ path, headers }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}