/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ApiResponse } from '../types/ApiResponse.ts'
import type { UploadFileResponse } from '../types/UploadFile.ts'
import { createApiResponse } from './createApiResponse.ts'
import { fakerDE as faker } from '@faker-js/faker'

export function createUploadFilePathPetId(data?: bigint): bigint {
  return data ?? faker.number.bigInt()
}

export function createUploadFileQueryAdditionalMetadata(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createUploadFileStatus200(data?: Partial<ApiResponse>): ApiResponse {
  return createApiResponse(data) as ApiResponse
}

export function createUploadFileData(data?: Blob): Blob {
  return data ?? faker.image.url() as unknown as Blob
}

export function createUploadFileResponse(data?: Partial<UploadFileResponse>): UploadFileResponse {
  return createUploadFileStatus200(data) as UploadFileResponse
}