/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetUserByNameResponse, GetUserByNameStatus200, GetUserByNameStatus200Json, GetUserByNameStatus200Xml, GetUserByNameStatus400, GetUserByNameStatus404 } from '../types/GetUserByName.ts'
import { createUser } from './createUser.ts'
import { fakerDE as faker } from '@faker-js/faker'

export function createGetUserByNamePathUsername(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createGetUserByNameStatus200Json(data?: Partial<GetUserByNameStatus200Json>): GetUserByNameStatus200Json {
  return createUser(data) as GetUserByNameStatus200Json
}

/**
 * @description successful operation
 */
export function createGetUserByNameStatus200Xml(data?: Partial<GetUserByNameStatus200Xml>): GetUserByNameStatus200Xml {
  return createUser(data) as GetUserByNameStatus200Xml
}

/**
 * @description successful operation
 */
export function createGetUserByNameStatus200(_data?: GetUserByNameStatus200): GetUserByNameStatus200 {
  return faker.helpers.arrayElement<any>([createGetUserByNameStatus200Json(), createGetUserByNameStatus200Xml()])
}

/**
 * @description Invalid username supplied
 */
export function createGetUserByNameStatus400() {
  return undefined
}

/**
 * @description User not found
 */
export function createGetUserByNameStatus404() {
  return undefined
}

export function createGetUserByNameResponse(_data?: GetUserByNameResponse): GetUserByNameResponse {
  return faker.helpers.arrayElement<any>([createGetUserByNameStatus200(), createGetUserByNameStatus400(), createGetUserByNameStatus404()])
}