/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Order } from "../types/Order.ts";
import { fakerDE as faker } from "@faker-js/faker";

export function createOrder(data?: Partial<Order>): Required<Order>
{
  const defaultFakeData = {"id": faker.number.bigInt(),"petId": faker.number.bigInt(),"quantity": faker.number.int(),"shipDate": faker.date.anytime().toISOString(),"status": faker.helpers.arrayElement<(NonNullable<Order> & Record<"status", unknown>)["status"]>(["placed", "approved", "delivered"]),"complete": faker.datatype.boolean()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<Order>
}