/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { AddPetBody, AddPetBodyFormUrlEncoded, AddPetBodyJson, AddPetBodyXml, AddPetResponse, AddPetStatus200, AddPetStatus200Json, AddPetStatus200Xml, AddPetStatus405 } from '../types/AddPet.ts'
import { createAddPetRequest } from './createAddPetRequest.ts'
import { createPet } from './createPet.ts'
import { fakerDE as faker } from '@faker-js/faker'

/**
 * @description Successful operation
 */
export function createAddPetStatus200Json(data?: Partial<AddPetStatus200Json>): AddPetStatus200Json {
  return createPet(data) as AddPetStatus200Json
}

/**
 * @description Successful operation
 */
export function createAddPetStatus200Xml(data?: Partial<AddPetStatus200Xml>): AddPetStatus200Xml {
  return createPet(data) as AddPetStatus200Xml
}

/**
 * @description Successful operation
 */
export function createAddPetStatus200(_data?: AddPetStatus200): AddPetStatus200 {
  return faker.helpers.arrayElement([createAddPetStatus200Json(), createAddPetStatus200Xml()])
}

/**
 * @description Invalid input
 */
export function createAddPetStatus405() {
  return undefined
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyJson(data?: Partial<AddPetBodyJson>): AddPetBodyJson {
  return createAddPetRequest(data) as AddPetBodyJson
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyXml(data?: Partial<AddPetBodyXml>): AddPetBodyXml {
  return createPet(data) as AddPetBodyXml
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBodyFormUrlEncoded(data?: Partial<AddPetBodyFormUrlEncoded>): AddPetBodyFormUrlEncoded {
  return createPet(data) as AddPetBodyFormUrlEncoded
}

/**
 * @description Create a new pet in the store
 */
export function createAddPetBody(_data?: AddPetBody): AddPetBody {
  return faker.helpers.arrayElement([createAddPetBodyJson(), createAddPetBodyXml(), createAddPetBodyFormUrlEncoded()])
}

export function createAddPetResponse(_data?: AddPetResponse): AddPetResponse {
  return faker.helpers.arrayElement([createAddPetStatus200(), createAddPetStatus405()])
}