/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { LoginUserResponse, LoginUserStatus200, LoginUserStatus400 } from '../types/LoginUser.ts'
import { fakerDE as faker } from '@faker-js/faker'

export function createLoginUserQueryUsername(data?: string): string {
  return data ?? faker.string.alpha()
}

export function createLoginUserQueryPassword(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createLoginUserStatus200Xml(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createLoginUserStatus200Json(data?: string): string {
  return data ?? faker.string.alpha()
}

/**
 * @description successful operation
 */
export function createLoginUserStatus200(_data?: LoginUserStatus200): LoginUserStatus200 {
  return faker.helpers.arrayElement<any>([createLoginUserStatus200Xml(), createLoginUserStatus200Json()])
}

/**
 * @description Invalid username/password supplied
 */
export function createLoginUserStatus400() {
  return undefined
}

export function createLoginUserResponse(_data?: LoginUserResponse): LoginUserResponse {
  return faker.helpers.arrayElement<any>([createLoginUserStatus200(), createLoginUserStatus400()])
}