/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlaceOrderBody, PlaceOrderBodyFormUrlEncoded, PlaceOrderBodyJson, PlaceOrderBodyXml, PlaceOrderResponse, PlaceOrderStatus200, PlaceOrderStatus405 } from '../types/PlaceOrder'
import { createOrder } from './createOrder'
import { fakerDE as faker } from '@faker-js/faker'

/**
 * @description successful operation
 */
export function createPlaceOrderStatus200(data?: Partial<PlaceOrderStatus200>): PlaceOrderStatus200 {
  return createOrder(data) as PlaceOrderStatus200
}

/**
 * @description Invalid input
 */
export function createPlaceOrderStatus405() {
  return undefined
}

export function createPlaceOrderBodyJson(data?: Partial<PlaceOrderBodyJson>): PlaceOrderBodyJson {
  return createOrder(data) as PlaceOrderBodyJson
}

export function createPlaceOrderBodyXml(data?: Partial<PlaceOrderBodyXml>): PlaceOrderBodyXml {
  return createOrder(data) as PlaceOrderBodyXml
}

export function createPlaceOrderBodyFormUrlEncoded(data?: Partial<PlaceOrderBodyFormUrlEncoded>): PlaceOrderBodyFormUrlEncoded {
  return createOrder(data) as PlaceOrderBodyFormUrlEncoded
}

export function createPlaceOrderBody(data?: Partial<PlaceOrderBody>): PlaceOrderBody {
  const defaultFakeData: unknown = faker.helpers.arrayElement([createPlaceOrderBodyJson(), createPlaceOrderBodyXml(), createPlaceOrderBodyFormUrlEncoded()])
  if (data && defaultFakeData && typeof defaultFakeData === 'object' && !Array.isArray(defaultFakeData)) {
    return { ...defaultFakeData, ...data } as PlaceOrderBody
  }
  return (data ?? defaultFakeData) as PlaceOrderBody
}

export function createPlaceOrderResponse(data?: Partial<PlaceOrderResponse>): PlaceOrderResponse {
  const defaultFakeData: unknown = faker.helpers.arrayElement([createPlaceOrderStatus200(), createPlaceOrderStatus405()])
  if (data && defaultFakeData && typeof defaultFakeData === 'object' && !Array.isArray(defaultFakeData)) {
    return { ...defaultFakeData, ...data } as PlaceOrderResponse
  }
  return (data ?? defaultFakeData) as PlaceOrderResponse
}
