/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { fakerDE } from "@faker-js/faker";

const faker = fakerDE

export function deletePetHeaderApiKey(data?: string): string {
  return data ?? faker.string.alpha()
}

export function deletePetPathPetId(data?: number): number {
  return data ?? faker.number.int()
}

/**
 * @description Invalid pet value
 */
export function deletePetStatus400() {
  return undefined
}

export function deletePetResponse() {
  return undefined
}