/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Order } from "../types/Order.ts";
import { fakerDE } from "@faker-js/faker";

const faker = fakerDE

export function order(data?: Partial<Order>): Required<Order>
{
  const defaultFakeData = {"id": faker.number.int(),"petId": faker.number.int(),"quantity": faker.number.int(),"shipDate": faker.date.anytime().toISOString(),"status": faker.helpers.arrayElement<NonNullable<Order>["status"]>(["placed", "approved", "delivered"]),"complete": faker.datatype.boolean()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<Order>
}