/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Pet } from "../types/Pet.ts";
import { category } from "./category.ts";
import { tag } from "./tag.ts";
import { fakerDE } from "@faker-js/faker";

const faker = fakerDE

export function pet(data?: Partial<Pet>): Required<Pet>
{
  const defaultFakeData = {"id": faker.number.int(),"name": faker.string.alpha(),"log": faker.helpers.fromRegExp("^[A-Za-z0-9()\[\]'"][-A-Za-z0-9_. \/()\[\]]{0,40}[A-Za-z0-9()\[\]'"]$"),"category": category(),"photoUrls": faker.helpers.multiple(() => (faker.string.alpha())),"tags": faker.helpers.multiple(() => (tag())),"status": faker.helpers.arrayElement<NonNullable<Pet>["status"]>(["available", "pending", "sold"])}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<Pet>
}