/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Tag } from "../types/Tag.ts";
import { fakerDE as faker } from "@faker-js/faker";

export function tag(data?: Partial<Tag>): Required<Tag>
{
  const defaultFakeData = {"id": faker.number.bigInt(),"name": faker.string.alpha()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<Tag>
}