/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from "../types/User.ts";
import { fakerDE } from "@faker-js/faker";

const faker = fakerDE

export function user(data?: Partial<User>): Required<User>
{
  const defaultFakeData = {"id": faker.number.int(),"username": faker.string.alpha(),"firstName": faker.string.alpha(),"lastName": faker.string.alpha(),"email": faker.string.alpha(),"password": faker.string.alpha(),"phone": faker.string.alpha(),"userStatus": faker.number.int()}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<User>
}