/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UserArray } from "../types/UserArray.ts";
import { user } from "./user.ts";
import { fakerDE } from "@faker-js/faker";

const faker = fakerDE

export function userArray(data?: UserArray): UserArray {
  return [
    ...faker.helpers.multiple(() => (user())),
    ...(data || [])
  ]
}