/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ClientConfig, ClientInstance, Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { AddPetOptionsSchemaType, AddPetResponsesSchemaType } from '../zod/addPetSchema'
import type { DeletePetOptionsSchemaType, DeletePetResponsesSchemaType } from '../zod/deletePetSchema'
import type { FindPetsByStatusOptionsSchemaType, FindPetsByStatusResponsesSchemaType } from '../zod/findPetsByStatusSchema'
import type { GetPetByIdOptionsSchemaType, GetPetByIdResponsesSchemaType } from '../zod/getPetByIdSchema'
import type { UploadFileOptionsSchemaType, UploadFileResponsesSchemaType } from '../zod/uploadFileSchema'
import { createClient, withUnwrap } from '../.kubb/client'
import { addPetResponseSchema } from '../zod/addPetSchema'
import { deletePetResponseSchema } from '../zod/deletePetSchema'
import { findPetsByStatusResponseSchema } from '../zod/findPetsByStatusSchema'
import { getPetByIdResponseSchema } from '../zod/getPetByIdSchema'
import { uploadFileResponseSchema } from '../zod/uploadFileSchema'

export class PetClient {
  private readonly client: ClientInstance

  constructor(config: ClientConfig = {}) {
    this.client = createClient(config)
  }

/**
   * @description Add a new pet to the store
   * @summary Add a new pet to the store
   * {@link /pet}
   */
    public addPet<ThrowOnError extends boolean = true>(options: Options<AddPetOptionsSchemaType, ThrowOnError>): Unwrappable<RequestResult<AddPetResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'POST', url: '/pet', security: [{ type: 'oauth2' }], validator: { response: addPetResponseSchema }, ...config }) as Promise<RequestResult<AddPetResponsesSchemaType, ThrowOnError>>)
  }

/**
   * @description Multiple status values can be provided with comma separated strings
   * @summary Finds Pets by status
   * {@link /pet/findByStatus}
   */
    public findPetsByStatus<ThrowOnError extends boolean = true>(options: Options<FindPetsByStatusOptionsSchemaType, ThrowOnError> = {}): Unwrappable<RequestResult<FindPetsByStatusResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'GET', url: '/pet/findByStatus', security: [{ type: 'oauth2' }], validator: { response: findPetsByStatusResponseSchema }, ...config }) as Promise<RequestResult<FindPetsByStatusResponsesSchemaType, ThrowOnError>>)
  }

/**
   * @description Returns a single pet
   * @summary Find pet by ID
   * {@link /pet/:petId}
   */
    public getPetById<ThrowOnError extends boolean = true>(options: Options<GetPetByIdOptionsSchemaType, ThrowOnError>): Unwrappable<RequestResult<GetPetByIdResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'GET', url: '/pet/{petId}', security: [{ type: 'apiKey', name: 'api_key', in: 'header' }, { type: 'oauth2' }], validator: { response: getPetByIdResponseSchema }, ...config }) as Promise<RequestResult<GetPetByIdResponsesSchemaType, ThrowOnError>>)
  }

/**
   * @description delete a pet
   * @summary Deletes a pet
   * {@link /pet/:petId}
   */
    public deletePet<ThrowOnError extends boolean = true>(options: Options<DeletePetOptionsSchemaType, ThrowOnError>): Unwrappable<RequestResult<DeletePetResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'DELETE', url: '/pet/{petId}', security: [{ type: 'oauth2' }], validator: { response: deletePetResponseSchema }, ...config }) as Promise<RequestResult<DeletePetResponsesSchemaType, ThrowOnError>>)
  }

/**
   * @summary uploads an image
   * {@link /pet/:petId/uploadImage}
   */
    public uploadFile<ThrowOnError extends boolean = true>(options: Options<UploadFileOptionsSchemaType, ThrowOnError>): Unwrappable<RequestResult<UploadFileResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'POST', url: '/pet/{petId}/uploadImage', security: [{ type: 'oauth2' }], validator: { response: uploadFileResponseSchema }, ...config }) as Promise<RequestResult<UploadFileResponsesSchemaType, ThrowOnError>>)
  }
}
