/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { ClientConfig, ClientInstance, Options, Unwrappable, RequestResult } from '../.kubb/client'
import type { GetInventoryOptionsSchemaType, GetInventoryResponsesSchemaType } from '../zod/getInventorySchema'
import type { PlaceOrderOptionsSchemaType, PlaceOrderResponsesSchemaType } from '../zod/placeOrderSchema'
import { createClient, withUnwrap } from '../.kubb/client'
import { getInventoryResponseSchema } from '../zod/getInventorySchema'
import { placeOrderResponseSchema } from '../zod/placeOrderSchema'

export class StoreClient {
  private readonly client: ClientInstance

  constructor(config: ClientConfig = {}) {
    this.client = createClient(config)
  }

/**
   * @description Returns a map of status codes to quantities
   * @summary Returns pet inventories by status
   * {@link /store/inventory}
   */
    public getInventory<ThrowOnError extends boolean = true>(options: Options<GetInventoryOptionsSchemaType, ThrowOnError> = {}): Unwrappable<RequestResult<GetInventoryResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'GET', url: '/store/inventory', security: [{ type: 'apiKey', name: 'api_key', in: 'header' }], validator: { response: getInventoryResponseSchema }, ...config })) as Unwrappable<RequestResult<GetInventoryResponsesSchemaType, ThrowOnError>>
  }

/**
   * @description Place a new order in the store
   * @summary Place an order for a pet
   * {@link /store/order}
   */
    public placeOrder<ThrowOnError extends boolean = true>(options: Options<PlaceOrderOptionsSchemaType, ThrowOnError>): Unwrappable<RequestResult<PlaceOrderResponsesSchemaType, ThrowOnError>> {
    const { client: request = this.client, ...config } = options

    return withUnwrap(request({ method: 'POST', url: '/store/order', validator: { response: placeOrderResponseSchema }, ...config })) as Unwrappable<RequestResult<PlaceOrderResponsesSchemaType, ThrowOnError>>
  }
}
