/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { userSchema } from "../userSchema.ts";

export const createUsersWithListInputStatus200SchemaJson = userSchema

export const createUsersWithListInputStatus200SchemaXml = userSchema

export const createUsersWithListInputStatus200Schema = z.union([createUsersWithListInputStatus200SchemaJson, createUsersWithListInputStatus200SchemaXml])

export const createUsersWithListInputStatusDefaultSchema = z.any()

export const createUsersWithListInputResponseSchema = z.union([createUsersWithListInputStatus200Schema, createUsersWithListInputStatusDefaultSchema])

export const createUsersWithListInputDataSchema = z.array(userSchema).optional()