/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @type object
*/
export type PetUpdate = {
    /**
     * @type string
    */
    name: string;
    /**
     * @type string | undefined
    */
    description?: string;
};