/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'

export const notificationTypeSchema = z.enum(["PING", "ORDER_CREATED", "ORDER_CANCELLED"]).describe("Notification type: PING — test, ORDER_CREATED — new order, ORDER_CANCELLED — order cancelled")