/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { PlaceOrderResponse, PlaceOrderStatus405, PlaceOrderData } from '../types/PlaceOrder.ts'
import type { HttpResponseResolver } from 'msw'
import { http } from 'msw'

export function placeOrderHandlerResponse200(data: PlaceOrderResponse) {
  return new Response(JSON.stringify(data), {
    status: 200,
      headers: {
      'Content-Type': 'application/json'
    },
  })
}

export function placeOrderHandlerResponse405(data?: PlaceOrderStatus405) {
  return new Response(JSON.stringify(data), {
    status: 405,

  })
}

export function placeOrderHandler(data?: PlaceOrderResponse | HttpResponseResolver<Record<string, string>, PlaceOrderData, any>) {
  return http.post<Record<string, string>, PlaceOrderData, any>(`http://localhost:3000/store/order`, function handler(info) {
      if(typeof data === 'function') return data(info)

      return new Response(JSON.stringify(data), {
        status: 200,
          headers: {
          'Content-Type': 'application/json'
        },
      })
    })
}