/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import type { ApiError } from './types/ApiError'
import { faker } from '@faker-js/faker'

export function createApiError(data?: Partial<ApiError>): ApiError {
  const defaultFakeData: unknown = faker.helpers.arrayElement([
    {
      error: faker.helpers.arrayElement<(NonNullable<ApiError> & Record<'error', unknown>)['error']>(['not_found']),
    },
    {
      error: faker.helpers.arrayElement<(NonNullable<ApiError> & Record<'error', unknown>)['error']>(['rate_limited']),
    },
  ])
  if (data && defaultFakeData && typeof defaultFakeData === 'object' && !Array.isArray(defaultFakeData)) {
    return { ...defaultFakeData, ...data } as ApiError
  }
  return (data ?? defaultFakeData) as ApiError
}
