/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod'

export const dateFieldSchema = z.iso.datetime().transform((value) => new Date(value))

export const dateFieldInputSchema = z.date().transform((value) => value.toISOString())
