/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import client from 'axios'
import type { FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsStatus200 } from './FindPetsByTags'
import type { QueryKey, QueryClient, QueryObserverOptions, UseQueryResult } from '@tanstack/react-query'
import type { Client, RequestConfig, ResponseErrorConfig } from 'axios'
import { FindPetsByTagsResponse } from './FindPetsByTags'
import { queryOptions, useQuery } from '@tanstack/react-query'

export const findPetsByTagsQueryKey = ({ query }: Omit<FindPetsByTagsRequestConfig, 'url'> = {}) =>
  [{ url: '/pet/findByTags' }, ...(query ? [query] : [])] as const

type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTags({ query }: Omit<FindPetsByTagsRequestConfig, 'url'> = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, query, ...requestConfig })

  return FindPetsByTagsResponse.parse(res.data)
}

export function findPetsByTagsQueryOptions(
  { query }: Omit<FindPetsByTagsRequestConfig, 'url'> = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = findPetsByTagsQueryKey({ query })
  return queryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, FindPetsByTagsStatus200, typeof queryKey>({
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByTags({ query }, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags<TData = FindPetsByTagsStatus200, TQueryData = FindPetsByTagsStatus200, TQueryKey extends QueryKey = FindPetsByTagsQueryKey>(
  { query }: Omit<FindPetsByTagsRequestConfig, 'url'> = {},
  options: {
    query?: Partial<QueryObserverOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = resolvedOptions?.queryKey ?? findPetsByTagsQueryKey({ query })

  const result = useQuery(
    {
      ...findPetsByTagsQueryOptions({ query }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as QueryObserverOptions,
    queryClient,
  ) as UseQueryResult<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  result.queryKey = queryKey as TQueryKey

  return result
}
