/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import * as z from 'zod'

export const petAndOwnerSchema = z
  .object({
    petName: z.string(),
  })
  .extend({
    ownerName: z.string(),
  })
