/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from "@kubb/plugin-client/clients/axios";
import type { Pet } from "../types/Pet.ts";
import type { PetUpdate } from "../types/PetUpdate.ts";
import type { UpdatePetPathPetId, UpdatePetQueryIncludeDeleted, UpdatePetQueryRequestSource } from "../types/UpdatePet.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { MaybeRefOrGetter } from "vue";
import { useMutation } from "@tanstack/vue-query";

export const updatePetMutationKey = () => [{ url: '/pets/:pet_id' }] as const

/**
 * {@link /pets/:pet_id}
 */
export async function updatePet(petId: UpdatePetPathPetId, data: PetUpdate, params?: { includeDeleted?: UpdatePetQueryIncludeDeleted; requestSource?: UpdatePetQueryRequestSource }, config: Partial<RequestConfig<PetUpdate>> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config


  const pet_id = petId


  const mappedParams = params ? { "include_deleted": params.includeDeleted, "request_source": params.requestSource } : undefined


  const requestData = data


  const res = await request<Pet, ResponseErrorConfig<Error>, PetUpdate>({ method: "POST", url: `/pets/${pet_id}`, params: mappedParams, data: requestData, ...requestConfig })

  return res.data
}

/**
 * {@link /pets/:pet_id}
 */
export function useUpdatePet<TContext>(options: {
  mutation?: MutationObserverOptions<Pet, ResponseErrorConfig<Error>, {petId: MaybeRefOrGetter<UpdatePetPathPetId>, data: MaybeRefOrGetter<PetUpdate>, params?: MaybeRefOrGetter<{ includeDeleted?: UpdatePetQueryIncludeDeleted; requestSource?: UpdatePetQueryRequestSource }>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<PetUpdate>> & { client?: Client },
} = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? updatePetMutationKey()

          return useMutation<Pet, ResponseErrorConfig<Error>, {petId: UpdatePetPathPetId, data: PetUpdate, params?: { includeDeleted?: UpdatePetQueryIncludeDeleted; requestSource?: UpdatePetQueryRequestSource }}, TContext>({
            mutationFn: async({ petId, data, params }) => {
              return updatePet(petId, data, params, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)

}