/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { electricCarTypeEnumSchema } from './electricCarTypeEnumSchema.ts'
import { vehicleSchema } from './vehicleSchema.ts'

export const electricCarSchema = vehicleSchema.strict().extend({
  type: electricCarTypeEnumSchema.optional(),
  batteryCapacity: z.number().optional().describe('Battery capacity in kWh'),
})