/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { SUVTypeEnumSchema } from './SUVTypeEnumSchema'
import { vehicleSchema } from './vehicleSchema'

export const SUVSchema = vehicleSchema.strict().extend({
  type: SUVTypeEnumSchema.optional(),
  offroadCapability: z.boolean().optional().describe('Can handle offroad terrain'),
})