/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { GetPetsRequestConfig, GetPetsResponse } from './GetPets'

export function getPets(
  { query, headers }: Omit<GetPetsRequestConfig, 'url'>,
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<GetPetsResponse> {
  return cy
    .request<GetPetsResponse>({
      method: 'GET',
      url: `/pets`,
      qs: query ? { page_size: query.pageSize } : undefined,
      headers: headers ? { 'x-api-key': headers.xApiKey } : undefined,
      ...options,
    })
    .then((res) => res.body)
}
