/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export const enum EnumNamesType {
  available = 'available',
  pending = 'pending',
  sold = 'sold',
}
