/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { LogoutUserResponse } from "../types/LogoutUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";

function getLogoutUserUrl() {
  const res = { method: 'GET', url: `/user/logout` as const }

  return res
}

/**
 * @summary Logs out current logged in user session
 * {@link /user/logout}
 */
export async function logoutUser(config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config




  const res = await request<LogoutUserResponse, ResponseErrorConfig<Error>, unknown>({ method: "GET", url: getLogoutUserUrl().url.toString(), ...requestConfig })

  return res.data
}