/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { userSchema } from './userSchema.ts'

export const createUserStatusDefaultSchemaJson = userSchema

export type CreateUserStatusDefaultSchemaJsonType = z.infer<typeof createUserStatusDefaultSchemaJson>

export const createUserStatusDefaultSchemaXml = userSchema

export type CreateUserStatusDefaultSchemaXmlType = z.infer<typeof createUserStatusDefaultSchemaXml>

export const createUserStatusDefaultSchema = z.union([createUserStatusDefaultSchemaJson, createUserStatusDefaultSchemaXml])

export type CreateUserStatusDefaultSchemaType = z.infer<typeof createUserStatusDefaultSchema>

export const createUserResponseSchema = createUserStatusDefaultSchema

export type CreateUserResponseSchemaType = z.infer<typeof createUserResponseSchema>

export const createUserDataSchemaJson = userSchema.optional().describe('Created user object')

export type CreateUserDataSchemaJsonType = z.infer<typeof createUserDataSchemaJson>

export const createUserDataSchemaXml = userSchema.optional().describe('Created user object')

export type CreateUserDataSchemaXmlType = z.infer<typeof createUserDataSchemaXml>

export const createUserDataSchemaFormUrlEncoded = userSchema.optional().describe('Created user object')

export type CreateUserDataSchemaFormUrlEncodedType = z.infer<typeof createUserDataSchemaFormUrlEncoded>

export const createUserDataSchema = z.union([createUserDataSchemaJson, createUserDataSchemaXml, createUserDataSchemaFormUrlEncoded])

export type CreateUserDataSchemaType = z.infer<typeof createUserDataSchema>
