/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { petNotFoundSchema } from './petNotFoundSchema'

export const createPetsPathUuidSchema = z.string().describe('UUID')

export type CreatePetsPathUuidSchemaType = z.infer<typeof createPetsPathUuidSchema>

export const createPetsQueryOffsetSchema = z.int().optional().describe('Offset')

export type CreatePetsQueryOffsetSchemaType = z.infer<typeof createPetsQueryOffsetSchema>

export const createPetsHeaderXEXAMPLESchema = z.enum(['ONE', 'TWO', 'THREE']).describe('Header parameters')

export type CreatePetsHeaderXEXAMPLESchemaType = z.infer<typeof createPetsHeaderXEXAMPLESchema>

export const createPetsStatus201Schema = z.unknown()

export type CreatePetsStatus201SchemaType = z.infer<typeof createPetsStatus201Schema>

export const createPetsStatusDefaultSchema = petNotFoundSchema.describe('Pet not found')

export type CreatePetsStatusDefaultSchemaType = z.infer<typeof createPetsStatusDefaultSchema>

export const createPetsResponseSchema = createPetsStatus201Schema

export type CreatePetsResponseSchemaType = z.infer<typeof createPetsResponseSchema>

export const createPetsErrorSchema = createPetsStatusDefaultSchema

export type CreatePetsErrorSchemaType = z.infer<typeof createPetsErrorSchema>

export const createPetsBodySchema = z.object({
  name: z.string(),
  tag: z.string(),
})

export type CreatePetsBodySchemaType = z.infer<typeof createPetsBodySchema>

export const createPetsPathSchema = z.object({
  uuid: z.string().describe('UUID'),
})

export type CreatePetsPathSchemaType = z.infer<typeof createPetsPathSchema>

export const createPetsQuerySchema = z.object({
  offset: z.int().optional().describe('Offset'),
})

export type CreatePetsQuerySchemaType = z.infer<typeof createPetsQuerySchema>

export const createPetsHeadersSchema = z.object({
  'X-EXAMPLE': z.enum(['ONE', 'TWO', 'THREE']).describe('Header parameters'),
})

export type CreatePetsHeadersSchemaType = z.infer<typeof createPetsHeadersSchema>

export const createPetsOptionsSchema = z.object({
  body: createPetsBodySchema,
  path: createPetsPathSchema,
  query: createPetsQuerySchema.optional(),
  headers: createPetsHeadersSchema,
})

export type CreatePetsOptionsSchemaType = z.infer<typeof createPetsOptionsSchema>
