/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { petNotFoundSchema } from './petNotFoundSchema.ts'

export const createPetsPathUuidSchema = z.string().describe('UUID')

export type CreatePetsPathUuidSchemaType = z.infer<typeof createPetsPathUuidSchema>

export const createPetsQueryOffsetSchema = z.int().optional().describe('Offset')

export type CreatePetsQueryOffsetSchemaType = z.infer<typeof createPetsQueryOffsetSchema>

export const createPetsHeaderXEXAMPLESchema = z.enum(['ONE', 'TWO', 'THREE']).describe('Header parameters')

export type CreatePetsHeaderXEXAMPLESchemaType = z.infer<typeof createPetsHeaderXEXAMPLESchema>

export const createPetsStatus201Schema = z.unknown()

export type CreatePetsStatus201SchemaType = z.infer<typeof createPetsStatus201Schema>

export const createPetsStatusDefaultSchema = petNotFoundSchema.describe('Pet not found')

export type CreatePetsStatusDefaultSchemaType = z.infer<typeof createPetsStatusDefaultSchema>

export const createPetsResponseSchema = createPetsStatus201Schema

export type CreatePetsResponseSchemaType = z.infer<typeof createPetsResponseSchema>

export const createPetsErrorSchema = createPetsStatusDefaultSchema

export type CreatePetsErrorSchemaType = z.infer<typeof createPetsErrorSchema>

export const createPetsBodySchema = z.object({
  name: z.string(),
  tag: z.string(),
})

export type CreatePetsBodySchemaType = z.infer<typeof createPetsBodySchema>
