/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'

export const deletePetHeaderApiKeySchema = z.string().optional()

export type DeletePetHeaderApiKeySchema = z.infer<typeof deletePetHeaderApiKeySchema>

export const deletePetPathPetIdSchema = z.int().describe('Pet id to delete')

export type DeletePetPathPetIdSchema = z.infer<typeof deletePetPathPetIdSchema>

export const deletePetStatus400Schema = z.any()

export type DeletePetStatus400Schema = z.infer<typeof deletePetStatus400Schema>

export const deletePetResponseSchema = deletePetStatus400Schema

export type DeletePetResponseSchema = z.infer<typeof deletePetResponseSchema>
