/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "../../zod.ts";
import { petSchema } from "./petSchema.ts";

export const findPetsByTagsQueryTagsSchema = z.array(z.string()).optional().describe("Tags to filter by")

export type FindPetsByTagsQueryTagsSchema = z.infer<typeof findPetsByTagsQueryTagsSchema>

export const findPetsByTagsQueryPageSchema = z.string().optional().describe("to request with required page number or pagination")

export type FindPetsByTagsQueryPageSchema = z.infer<typeof findPetsByTagsQueryPageSchema>

export const findPetsByTagsQueryPageSizeSchema = z.string().optional().describe("to request with required page size")

export type FindPetsByTagsQueryPageSizeSchema = z.infer<typeof findPetsByTagsQueryPageSizeSchema>

export const findPetsByTagsHeaderXEXAMPLESchema = z.enum(["ONE", "TWO", "THREE"]).describe("Header parameters")

export type FindPetsByTagsHeaderXEXAMPLESchema = z.infer<typeof findPetsByTagsHeaderXEXAMPLESchema>

export const findPetsByTagsStatus200Schema = z.array(petSchema)

export type FindPetsByTagsStatus200Schema = z.infer<typeof findPetsByTagsStatus200Schema>

export const findPetsByTagsStatus400Schema = z.any()

export type FindPetsByTagsStatus400Schema = z.infer<typeof findPetsByTagsStatus400Schema>