export type { AddPetRequestSchemaType } from './addPetRequestSchema.ts'
export type { AddPetDataSchemaFormUrlEncodedType, AddPetDataSchemaJsonType, AddPetDataSchemaType, AddPetDataSchemaXmlType, AddPetErrorSchemaType, AddPetResponseSchemaType, AddPetStatus200SchemaJsonType, AddPetStatus200SchemaType, AddPetStatus200SchemaXmlType, AddPetStatus405SchemaType } from './addPetSchema.ts'
export type { ApiResponseSchemaType } from './apiResponseSchema.ts'
export type { CategorySchemaType } from './categorySchema.ts'
export type { CreatePetsDataSchemaType, CreatePetsErrorSchemaType, CreatePetsHeaderXEXAMPLESchemaType, CreatePetsPathUuidSchemaType, CreatePetsQueryOffsetSchemaType, CreatePetsResponseSchemaType, CreatePetsStatus201SchemaType, CreatePetsStatusDefaultSchemaType } from './createPetsSchema.ts'
export type { DeleteOrderErrorSchemaType, DeleteOrderPathOrderIdSchemaType, DeleteOrderResponseSchemaType, DeleteOrderStatus400SchemaType, DeleteOrderStatus404SchemaType } from './deleteOrderSchema.ts'
export type { DeletePetErrorSchemaType, DeletePetHeaderApiKeySchemaType, DeletePetPathPetIdSchemaType, DeletePetResponseSchemaType, DeletePetStatus400SchemaType } from './deletePetSchema.ts'
export type { FindPetsByStatusErrorSchemaType, FindPetsByStatusQueryStatusSchemaType, FindPetsByStatusResponseSchemaType, FindPetsByStatusStatus200SchemaJsonType, FindPetsByStatusStatus200SchemaType, FindPetsByStatusStatus200SchemaXmlType, FindPetsByStatusStatus400SchemaType } from './findPetsByStatusSchema.ts'
export type { FindPetsByTagsErrorSchemaType, FindPetsByTagsHeaderXEXAMPLESchemaType, FindPetsByTagsQueryPageSchemaType, FindPetsByTagsQueryPageSizeSchemaType, FindPetsByTagsQueryTagsSchemaType, FindPetsByTagsResponseSchemaType, FindPetsByTagsStatus200SchemaJsonType, FindPetsByTagsStatus200SchemaType, FindPetsByTagsStatus200SchemaXmlType, FindPetsByTagsStatus400SchemaType } from './findPetsByTagsSchema.ts'
export type { GetInventoryResponseSchemaType, GetInventoryStatus200SchemaType } from './getInventorySchema.ts'
export type { GetOrderByIdErrorSchemaType, GetOrderByIdPathOrderIdSchemaType, GetOrderByIdResponseSchemaType, GetOrderByIdStatus200SchemaJsonType, GetOrderByIdStatus200SchemaType, GetOrderByIdStatus200SchemaXmlType, GetOrderByIdStatus400SchemaType, GetOrderByIdStatus404SchemaType } from './getOrderByIdSchema.ts'
export type { GetPetByIdErrorSchemaType, GetPetByIdPathPetIdSchemaType, GetPetByIdResponseSchemaType, GetPetByIdStatus200SchemaJsonType, GetPetByIdStatus200SchemaType, GetPetByIdStatus200SchemaXmlType, GetPetByIdStatus400SchemaType, GetPetByIdStatus404SchemaType } from './getPetByIdSchema.ts'
export type { GetThingsErrorSchemaType, GetThingsQueryLimitSchemaType, GetThingsQuerySkipSchemaType, GetThingsResponseSchemaType, GetThingsStatus201SchemaType, GetThingsStatusDefaultSchemaType } from './getThingsSchema.ts'
export type { OrderSchemaType } from './orderSchema.ts'
export type { PetNotFoundSchemaType } from './petNotFoundSchema.ts'
export type { PetSchemaType } from './petSchema.ts'
export type { PhoneNumberSchemaType } from './phoneNumberSchema.ts'
export type { PhoneWithMaxLengthExplicitSchemaType } from './phoneWithMaxLengthExplicitSchema.ts'
export type { PhoneWithMaxLengthSchemaType } from './phoneWithMaxLengthSchema.ts'
export type { PlaceOrderPatchDataSchemaFormUrlEncodedType, PlaceOrderPatchDataSchemaJsonType, PlaceOrderPatchDataSchemaType, PlaceOrderPatchDataSchemaXmlType, PlaceOrderPatchErrorSchemaType, PlaceOrderPatchResponseSchemaType, PlaceOrderPatchStatus200SchemaType, PlaceOrderPatchStatus405SchemaType } from './placeOrderPatchSchema.ts'
export type { PlaceOrderDataSchemaFormUrlEncodedType, PlaceOrderDataSchemaJsonType, PlaceOrderDataSchemaType, PlaceOrderDataSchemaXmlType, PlaceOrderErrorSchemaType, PlaceOrderResponseSchemaType, PlaceOrderStatus200SchemaType, PlaceOrderStatus405SchemaType } from './placeOrderSchema.ts'
export type { TagSchemaType } from './tagSchema.ts'
export type { UpdatePetDataSchemaFormUrlEncodedType, UpdatePetDataSchemaJsonType, UpdatePetDataSchemaType, UpdatePetDataSchemaXmlType, UpdatePetErrorSchemaType, UpdatePetResponseSchemaType, UpdatePetStatus200SchemaJsonType, UpdatePetStatus200SchemaType, UpdatePetStatus200SchemaXmlType, UpdatePetStatus400SchemaType, UpdatePetStatus404SchemaType, UpdatePetStatus405SchemaType } from './updatePetSchema.ts'
export type { UpdatePetWithFormErrorSchemaType, UpdatePetWithFormPathPetIdSchemaType, UpdatePetWithFormQueryNameSchemaType, UpdatePetWithFormQueryStatusSchemaType, UpdatePetWithFormResponseSchemaType, UpdatePetWithFormStatus405SchemaType } from './updatePetWithFormSchema.ts'
export type { UploadFileDataSchemaType, UploadFilePathPetIdSchemaType, UploadFileQueryAdditionalMetadataSchemaType, UploadFileResponseSchemaType, UploadFileStatus200SchemaType } from './uploadFileSchema.ts'
export { addPetRequestSchema } from './addPetRequestSchema.ts'
export { addPetDataSchema, addPetDataSchemaFormUrlEncoded, addPetDataSchemaJson, addPetDataSchemaXml, addPetErrorSchema, addPetResponseSchema, addPetStatus200Schema, addPetStatus200SchemaJson, addPetStatus200SchemaXml, addPetStatus405Schema } from './addPetSchema.ts'
export { apiResponseSchema } from './apiResponseSchema.ts'
export { categorySchema } from './categorySchema.ts'
export { createPetsDataSchema, createPetsErrorSchema, createPetsHeaderXEXAMPLESchema, createPetsPathUuidSchema, createPetsQueryOffsetSchema, createPetsResponseSchema, createPetsStatus201Schema, createPetsStatusDefaultSchema } from './createPetsSchema.ts'
export { deleteOrderErrorSchema, deleteOrderPathOrderIdSchema, deleteOrderResponseSchema, deleteOrderStatus400Schema, deleteOrderStatus404Schema } from './deleteOrderSchema.ts'
export { deletePetErrorSchema, deletePetHeaderApiKeySchema, deletePetPathPetIdSchema, deletePetResponseSchema, deletePetStatus400Schema } from './deletePetSchema.ts'
export { findPetsByStatusErrorSchema, findPetsByStatusQueryStatusSchema, findPetsByStatusResponseSchema, findPetsByStatusStatus200Schema, findPetsByStatusStatus200SchemaJson, findPetsByStatusStatus200SchemaXml, findPetsByStatusStatus400Schema } from './findPetsByStatusSchema.ts'
export { findPetsByTagsErrorSchema, findPetsByTagsHeaderXEXAMPLESchema, findPetsByTagsQueryPageSchema, findPetsByTagsQueryPageSizeSchema, findPetsByTagsQueryTagsSchema, findPetsByTagsResponseSchema, findPetsByTagsStatus200Schema, findPetsByTagsStatus200SchemaJson, findPetsByTagsStatus200SchemaXml, findPetsByTagsStatus400Schema } from './findPetsByTagsSchema.ts'
export { getInventoryResponseSchema, getInventoryStatus200Schema } from './getInventorySchema.ts'
export { getOrderByIdErrorSchema, getOrderByIdPathOrderIdSchema, getOrderByIdResponseSchema, getOrderByIdStatus200Schema, getOrderByIdStatus200SchemaJson, getOrderByIdStatus200SchemaXml, getOrderByIdStatus400Schema, getOrderByIdStatus404Schema } from './getOrderByIdSchema.ts'
export { getPetByIdErrorSchema, getPetByIdPathPetIdSchema, getPetByIdResponseSchema, getPetByIdStatus200Schema, getPetByIdStatus200SchemaJson, getPetByIdStatus200SchemaXml, getPetByIdStatus400Schema, getPetByIdStatus404Schema } from './getPetByIdSchema.ts'
export { getThingsErrorSchema, getThingsQueryLimitSchema, getThingsQuerySkipSchema, getThingsResponseSchema, getThingsStatus201Schema, getThingsStatusDefaultSchema } from './getThingsSchema.ts'
export { OperationSchema, OperationsMap, operations, paths } from './operationsSchema.ts'
export { orderSchema } from './orderSchema.ts'
export { petNotFoundSchema } from './petNotFoundSchema.ts'
export { petSchema } from './petSchema.ts'
export { phoneNumberSchema } from './phoneNumberSchema.ts'
export { phoneWithMaxLengthExplicitSchema } from './phoneWithMaxLengthExplicitSchema.ts'
export { phoneWithMaxLengthSchema } from './phoneWithMaxLengthSchema.ts'
export { placeOrderPatchDataSchema, placeOrderPatchDataSchemaFormUrlEncoded, placeOrderPatchDataSchemaJson, placeOrderPatchDataSchemaXml, placeOrderPatchErrorSchema, placeOrderPatchResponseSchema, placeOrderPatchStatus200Schema, placeOrderPatchStatus405Schema } from './placeOrderPatchSchema.ts'
export { placeOrderDataSchema, placeOrderDataSchemaFormUrlEncoded, placeOrderDataSchemaJson, placeOrderDataSchemaXml, placeOrderErrorSchema, placeOrderResponseSchema, placeOrderStatus200Schema, placeOrderStatus405Schema } from './placeOrderSchema.ts'
export { tagSchema } from './tagSchema.ts'
export { updatePetDataSchema, updatePetDataSchemaFormUrlEncoded, updatePetDataSchemaJson, updatePetDataSchemaXml, updatePetErrorSchema, updatePetResponseSchema, updatePetStatus200Schema, updatePetStatus200SchemaJson, updatePetStatus200SchemaXml, updatePetStatus400Schema, updatePetStatus404Schema, updatePetStatus405Schema } from './updatePetSchema.ts'
export { updatePetWithFormErrorSchema, updatePetWithFormPathPetIdSchema, updatePetWithFormQueryNameSchema, updatePetWithFormQueryStatusSchema, updatePetWithFormResponseSchema, updatePetWithFormStatus405Schema } from './updatePetWithFormSchema.ts'
export { uploadFileDataSchema, uploadFilePathPetIdSchema, uploadFileQueryAdditionalMetadataSchema, uploadFileResponseSchema, uploadFileStatus200Schema } from './uploadFileSchema.ts'