/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from "../../zod.ts";

export const logoutUserStatusDefaultSchema = z.any()

export type LogoutUserStatusDefaultSchema = z.infer<typeof logoutUserStatusDefaultSchema>