/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { z } from '../../zod.ts'
import { addPetDataSchema, addPetResponseSchema, addPetStatus200Schema, addPetStatus405Schema } from './addPetSchema.ts'
import { createPetsDataSchema, createPetsHeaderXEXAMPLESchema, createPetsPathUuidSchema, createPetsQueryOffsetSchema, createPetsResponseSchema, createPetsStatus201Schema } from './createPetsSchema.ts'
import { createUserDataSchema, createUserResponseSchema } from './createUserSchema.ts'
import { createUsersWithListInputDataSchema, createUsersWithListInputResponseSchema, createUsersWithListInputStatus200Schema } from './createUsersWithListInputSchema.ts'
import { deleteOrderPathOrderIdSchema, deleteOrderResponseSchema, deleteOrderStatus400Schema, deleteOrderStatus404Schema } from './deleteOrderSchema.ts'
import { deletePetHeaderApiKeySchema, deletePetPathPetIdSchema, deletePetResponseSchema, deletePetStatus400Schema } from './deletePetSchema.ts'
import { deleteUserPathUsernameSchema, deleteUserResponseSchema, deleteUserStatus400Schema, deleteUserStatus404Schema } from './deleteUserSchema.ts'
import { findPetsByStatusQueryStatusSchema, findPetsByStatusResponseSchema, findPetsByStatusStatus200Schema, findPetsByStatusStatus400Schema } from './findPetsByStatusSchema.ts'
import { findPetsByTagsHeaderXEXAMPLESchema, findPetsByTagsQueryTagsSchema, findPetsByTagsResponseSchema, findPetsByTagsStatus200Schema, findPetsByTagsStatus400Schema } from './findPetsByTagsSchema.ts'
import { getInventoryResponseSchema, getInventoryStatus200Schema } from './getInventorySchema.ts'
import { getOrderByIdPathOrderIdSchema, getOrderByIdResponseSchema, getOrderByIdStatus200Schema, getOrderByIdStatus400Schema, getOrderByIdStatus404Schema } from './getOrderByIdSchema.ts'
import { getPetByIdPathPetIdSchema, getPetByIdResponseSchema, getPetByIdStatus200Schema, getPetByIdStatus400Schema, getPetByIdStatus404Schema } from './getPetByIdSchema.ts'
import { getThingsQueryLimitSchema, getThingsResponseSchema, getThingsStatus201Schema } from './getThingsSchema.ts'
import { getUserByNamePathUsernameSchema, getUserByNameResponseSchema, getUserByNameStatus200Schema, getUserByNameStatus400Schema, getUserByNameStatus404Schema } from './getUserByNameSchema.ts'
import { loginUserQueryUsernameSchema, loginUserResponseSchema, loginUserStatus200Schema, loginUserStatus400Schema } from './loginUserSchema.ts'
import { logoutUserResponseSchema } from './logoutUserSchema.ts'
import { placeOrderPatchDataSchema, placeOrderPatchResponseSchema, placeOrderPatchStatus200Schema, placeOrderPatchStatus405Schema } from './placeOrderPatchSchema.ts'
import { placeOrderDataSchema, placeOrderResponseSchema, placeOrderStatus200Schema, placeOrderStatus405Schema } from './placeOrderSchema.ts'
import { updatePetDataSchema, updatePetResponseSchema, updatePetStatus200Schema, updatePetStatus400Schema, updatePetStatus404Schema, updatePetStatus405Schema } from './updatePetSchema.ts'
import { updatePetWithFormPathPetIdSchema, updatePetWithFormQueryNameSchema, updatePetWithFormResponseSchema, updatePetWithFormStatus405Schema } from './updatePetWithFormSchema.ts'
import { updateUserDataSchema, updateUserPathUsernameSchema, updateUserResponseSchema } from './updateUserSchema.ts'
import { uploadFileDataSchema, uploadFilePathPetIdSchema, uploadFileQueryAdditionalMetadataSchema, uploadFileResponseSchema, uploadFileStatus200Schema } from './uploadFileSchema.ts'

export type OperationSchema = {
  readonly request: z.ZodTypeAny | undefined;
  readonly parameters: {
        readonly path: z.ZodTypeAny | undefined;
        readonly query: z.ZodTypeAny | undefined;
        readonly header: z.ZodTypeAny | undefined;
  };
  readonly responses: {
        readonly [status: number]: z.ZodTypeAny;
        readonly default: z.ZodTypeAny;
  };
  readonly errors: {
        readonly [status: number]: z.ZodTypeAny;
  };
}

export type OperationsMap = Record<string, OperationSchema>

export const operations = {"getThings": {
        request: null,
parameters: {
        path: null,
query: getThingsQueryLimitSchema,
header: null
      },
responses: {
        201: getThingsStatus201Schema,
default: getThingsResponseSchema
      },
errors: {

      }
      },
"createPets": {
        request: createPetsDataSchema,
parameters: {
        path: createPetsPathUuidSchema,
query: createPetsQueryOffsetSchema,
header: createPetsHeaderXEXAMPLESchema
      },
responses: {
        201: createPetsStatus201Schema,
default: createPetsResponseSchema
      },
errors: {

      }
      },
"updatePet": {
        request: updatePetDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: updatePetStatus200Schema,
400: updatePetStatus400Schema,
404: updatePetStatus404Schema,
405: updatePetStatus405Schema,
default: updatePetResponseSchema
      },
errors: {
        400: updatePetStatus400Schema,
404: updatePetStatus404Schema,
405: updatePetStatus405Schema
      }
      },
"addPet": {
        request: addPetDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: addPetStatus200Schema,
405: addPetStatus405Schema,
default: addPetResponseSchema
      },
errors: {
        405: addPetStatus405Schema
      }
      },
"findPetsByStatus": {
        request: null,
parameters: {
        path: null,
query: findPetsByStatusQueryStatusSchema,
header: null
      },
responses: {
        200: findPetsByStatusStatus200Schema,
400: findPetsByStatusStatus400Schema,
default: findPetsByStatusResponseSchema
      },
errors: {
        400: findPetsByStatusStatus400Schema
      }
      },
"findPetsByTags": {
        request: null,
parameters: {
        path: null,
query: findPetsByTagsQueryTagsSchema,
header: findPetsByTagsHeaderXEXAMPLESchema
      },
responses: {
        200: findPetsByTagsStatus200Schema,
400: findPetsByTagsStatus400Schema,
default: findPetsByTagsResponseSchema
      },
errors: {
        400: findPetsByTagsStatus400Schema
      }
      },
"getPetById": {
        request: null,
parameters: {
        path: getPetByIdPathPetIdSchema,
query: null,
header: null
      },
responses: {
        200: getPetByIdStatus200Schema,
400: getPetByIdStatus400Schema,
404: getPetByIdStatus404Schema,
default: getPetByIdResponseSchema
      },
errors: {
        400: getPetByIdStatus400Schema,
404: getPetByIdStatus404Schema
      }
      },
"updatePetWithForm": {
        request: null,
parameters: {
        path: updatePetWithFormPathPetIdSchema,
query: updatePetWithFormQueryNameSchema,
header: null
      },
responses: {
        405: updatePetWithFormStatus405Schema,
default: updatePetWithFormResponseSchema
      },
errors: {
        405: updatePetWithFormStatus405Schema
      }
      },
"deletePet": {
        request: null,
parameters: {
        path: deletePetPathPetIdSchema,
query: null,
header: deletePetHeaderApiKeySchema
      },
responses: {
        400: deletePetStatus400Schema,
default: deletePetResponseSchema
      },
errors: {
        400: deletePetStatus400Schema
      }
      },
"uploadFile": {
        request: uploadFileDataSchema,
parameters: {
        path: uploadFilePathPetIdSchema,
query: uploadFileQueryAdditionalMetadataSchema,
header: null
      },
responses: {
        200: uploadFileStatus200Schema,
default: uploadFileResponseSchema
      },
errors: {

      }
      },
"getInventory": {
        request: null,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: getInventoryStatus200Schema,
default: getInventoryResponseSchema
      },
errors: {

      }
      },
"placeOrder": {
        request: placeOrderDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: placeOrderStatus200Schema,
405: placeOrderStatus405Schema,
default: placeOrderResponseSchema
      },
errors: {
        405: placeOrderStatus405Schema
      }
      },
"placeOrderPatch": {
        request: placeOrderPatchDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: placeOrderPatchStatus200Schema,
405: placeOrderPatchStatus405Schema,
default: placeOrderPatchResponseSchema
      },
errors: {
        405: placeOrderPatchStatus405Schema
      }
      },
"getOrderById": {
        request: null,
parameters: {
        path: getOrderByIdPathOrderIdSchema,
query: null,
header: null
      },
responses: {
        200: getOrderByIdStatus200Schema,
400: getOrderByIdStatus400Schema,
404: getOrderByIdStatus404Schema,
default: getOrderByIdResponseSchema
      },
errors: {
        400: getOrderByIdStatus400Schema,
404: getOrderByIdStatus404Schema
      }
      },
"deleteOrder": {
        request: null,
parameters: {
        path: deleteOrderPathOrderIdSchema,
query: null,
header: null
      },
responses: {
        400: deleteOrderStatus400Schema,
404: deleteOrderStatus404Schema,
default: deleteOrderResponseSchema
      },
errors: {
        400: deleteOrderStatus400Schema,
404: deleteOrderStatus404Schema
      }
      },
"createUser": {
        request: createUserDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        default: createUserResponseSchema
      },
errors: {

      }
      },
"createUsersWithListInput": {
        request: createUsersWithListInputDataSchema,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        200: createUsersWithListInputStatus200Schema,
default: createUsersWithListInputResponseSchema
      },
errors: {

      }
      },
"loginUser": {
        request: null,
parameters: {
        path: null,
query: loginUserQueryUsernameSchema,
header: null
      },
responses: {
        200: loginUserStatus200Schema,
400: loginUserStatus400Schema,
default: loginUserResponseSchema
      },
errors: {
        400: loginUserStatus400Schema
      }
      },
"logoutUser": {
        request: null,
parameters: {
        path: null,
query: null,
header: null
      },
responses: {
        default: logoutUserResponseSchema
      },
errors: {

      }
      },
"getUserByName": {
        request: null,
parameters: {
        path: getUserByNamePathUsernameSchema,
query: null,
header: null
      },
responses: {
        200: getUserByNameStatus200Schema,
400: getUserByNameStatus400Schema,
404: getUserByNameStatus404Schema,
default: getUserByNameResponseSchema
      },
errors: {
        400: getUserByNameStatus400Schema,
404: getUserByNameStatus404Schema
      }
      },
"updateUser": {
        request: updateUserDataSchema,
parameters: {
        path: updateUserPathUsernameSchema,
query: null,
header: null
      },
responses: {
        default: updateUserResponseSchema
      },
errors: {

      }
      },
"deleteUser": {
        request: null,
parameters: {
        path: deleteUserPathUsernameSchema,
query: null,
header: null
      },
responses: {
        400: deleteUserStatus400Schema,
404: deleteUserStatus404Schema,
default: deleteUserResponseSchema
      },
errors: {
        400: deleteUserStatus400Schema,
404: deleteUserStatus404Schema
      }
      }} as const

export const paths = {"/pets/{uuid}": {
        GET: operations["getThings"],
POST: operations["createPets"]
      },
"/pet": {
        PUT: operations["updatePet"],
POST: operations["addPet"]
      },
"/pet/findByStatus": {
        GET: operations["findPetsByStatus"]
      },
"/pet/findByTags": {
        GET: operations["findPetsByTags"]
      },
"/pet/{petId}": {
        GET: operations["getPetById"],
POST: operations["updatePetWithForm"],
DELETE: operations["deletePet"]
      },
"/pet/{petId}/uploadImage": {
        POST: operations["uploadFile"]
      },
"/store/inventory": {
        GET: operations["getInventory"]
      },
"/store/order": {
        POST: operations["placeOrder"],
PATCH: operations["placeOrderPatch"]
      },
"/store/order/{orderId}": {
        GET: operations["getOrderById"],
DELETE: operations["deleteOrder"]
      },
"/user": {
        POST: operations["createUser"]
      },
"/user/createWithList": {
        POST: operations["createUsersWithListInput"]
      },
"/user/login": {
        GET: operations["loginUser"]
      },
"/user/logout": {
        GET: operations["logoutUser"]
      },
"/user/{username}": {
        GET: operations["getUserByName"],
PUT: operations["updateUser"],
DELETE: operations["deleteUser"]
      }} as const