/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { phoneNumberSchema } from './phoneNumberSchema.ts'

export const phoneWithMaxLengthExplicitSchema = phoneNumberSchema.max(15)

export type PhoneWithMaxLengthExplicitSchemaType = z.infer<typeof phoneWithMaxLengthExplicitSchema>
