/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { z } from '../../zod.ts'
import { orderSchema } from './orderSchema.ts'

export const placeOrderStatus200Schema = orderSchema

export type PlaceOrderStatus200SchemaType = z.infer<typeof placeOrderStatus200Schema>

export const placeOrderStatus405Schema = z.any()

export type PlaceOrderStatus405SchemaType = z.infer<typeof placeOrderStatus405Schema>

export const placeOrderResponseSchema = placeOrderStatus200Schema

export type PlaceOrderResponseSchemaType = z.infer<typeof placeOrderResponseSchema>

export const placeOrderErrorSchema = placeOrderStatus405Schema

export type PlaceOrderErrorSchemaType = z.infer<typeof placeOrderErrorSchema>

export const placeOrderDataSchemaJson = orderSchema.optional()

export type PlaceOrderDataSchemaJsonType = z.infer<typeof placeOrderDataSchemaJson>

export const placeOrderDataSchemaXml = orderSchema.optional()

export type PlaceOrderDataSchemaXmlType = z.infer<typeof placeOrderDataSchemaXml>

export const placeOrderDataSchemaFormUrlEncoded = orderSchema.optional()

export type PlaceOrderDataSchemaFormUrlEncodedType = z.infer<typeof placeOrderDataSchemaFormUrlEncoded>

export const placeOrderDataSchema = z.union([placeOrderDataSchemaJson, placeOrderDataSchemaXml, placeOrderDataSchemaFormUrlEncoded])

export type PlaceOrderDataSchemaType = z.infer<typeof placeOrderDataSchema>