/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'
import { orderSchema } from './orderSchema.ts'

export const placeOrderPatchStatus200Schema = orderSchema

export type PlaceOrderPatchStatus200SchemaType = z.infer<typeof placeOrderPatchStatus200Schema>

export const placeOrderPatchStatus405Schema = z.any()

export type PlaceOrderPatchStatus405SchemaType = z.infer<typeof placeOrderPatchStatus405Schema>

export const placeOrderPatchResponseSchema = z.union([placeOrderPatchStatus200Schema, placeOrderPatchStatus405Schema])

export type PlaceOrderPatchResponseSchemaType = z.infer<typeof placeOrderPatchResponseSchema>

export const placeOrderPatchDataSchemaJson = orderSchema.optional()

export type PlaceOrderPatchDataSchemaJsonType = z.infer<typeof placeOrderPatchDataSchemaJson>

export const placeOrderPatchDataSchemaXml = orderSchema.optional()

export type PlaceOrderPatchDataSchemaXmlType = z.infer<typeof placeOrderPatchDataSchemaXml>

export const placeOrderPatchDataSchemaFormUrlEncoded = orderSchema.optional()

export type PlaceOrderPatchDataSchemaFormUrlEncodedType = z.infer<typeof placeOrderPatchDataSchemaFormUrlEncoded>

export const placeOrderPatchDataSchema = z.union([placeOrderPatchDataSchemaJson, placeOrderPatchDataSchemaXml, placeOrderPatchDataSchemaFormUrlEncoded])

export type PlaceOrderPatchDataSchemaType = z.infer<typeof placeOrderPatchDataSchema>
