/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { z } from '../../zod.ts'

export const uploadFilePathPetIdSchema = z.bigint().describe('ID of pet to update')

export type UploadFilePathPetIdSchema = z.infer<typeof uploadFilePathPetIdSchema>

export const uploadFileQueryAdditionalMetadataSchema = z.string().optional().describe('Additional Metadata')

export type UploadFileQueryAdditionalMetadataSchema = z.infer<typeof uploadFileQueryAdditionalMetadataSchema>

export const uploadFileDataSchema = z.instanceof(File).optional()

export type UploadFileDataSchema = z.infer<typeof uploadFileDataSchema>
