/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import type { RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { SetPropertyOptions, SetPropertyStatus200 } from './SetProperty'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import { setProperty } from './clients/setProperty'
import { useMutation } from '@tanstack/vue-query'
import { toValue } from 'vue'

export const setPropertyMutationKey = () => [{ url: '/properties' }] as const

/**
 * {@link /properties}
 */
export function useSetProperty<TContext>(
  options: {
    mutation?: MutationObserverOptions<SetPropertyStatus200, ResponseErrorConfig<Error>, SetPropertyOptions, TContext> & { client?: QueryClient }
    client?: Partial<Omit<RequestConfig, 'path' | 'query' | 'body' | 'headers' | 'url'>>
  } = {},
) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation
  const mutationKey = mutationOptions?.mutationKey ?? setPropertyMutationKey()

  return useMutation<SetPropertyStatus200, ResponseErrorConfig<Error>, SetPropertyOptions, TContext>(
    {
      mutationFn: async ({ body }) => {
        return setProperty({ ...config, body: toValue<SetPropertyOptions['body']>(body), throwOnError: true }).unwrap()
      },
      mutationKey,
      ...mutationOptions,
    },
    queryClient,
  )
}
