/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { FindPetsByTagsRequestConfig, FindPetsByTagsResponse, FindPetsByTagsStatus200 } from './FindPetsByTags'
import type { QueryKey, QueryClient, UseQueryOptions, UseQueryReturnType } from '@tanstack/react-query'
import type { MaybeRefOrGetter } from 'vue'
import { client } from './.kubb/client'
import { FindPetsByTagsResponse } from './FindPetsByTags'
import { queryOptions, useQuery } from '@tanstack/react-query'
import { toValue } from 'vue'

export const findPetsByTagsQueryKey = ({ query }: { query?: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url'>['query']> } = {}) =>
  ['findPetsByTags', { url: '/pet/findByTags' }, ...(query ? [query] : [])] as const

export type FindPetsByTagsQueryKey = ReturnType<typeof findPetsByTagsQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTags({ query }: Omit<FindPetsByTagsRequestConfig, 'url'> = {}, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, query, ...requestConfig })

  return FindPetsByTagsResponse.parse(res.data)
}

export function findPetsByTagsQueryOptions(
  { query }: { query?: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url'>['query']> } = {},
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const queryKey = findPetsByTagsQueryKey({ query })
  return queryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, FindPetsByTagsStatus200>({
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByTags({ query: toValue(query) }, { ...config, signal: config.signal ?? signal })
    },
  })
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTags<TData = FindPetsByTagsStatus200, TQueryData = FindPetsByTagsStatus200, TQueryKey extends QueryKey = FindPetsByTagsQueryKey>(
  { query }: { query?: MaybeRefOrGetter<Omit<FindPetsByTagsRequestConfig, 'url'>['query']> } = {},
  options: {
    query?: Partial<UseQueryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, TData, TQueryData, TQueryKey>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? findPetsByTagsQueryKey({ query })

  const queryResult = useQuery(
    {
      ...findPetsByTagsQueryOptions({ query }, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseQueryOptions<FindPetsByTagsStatus200, ResponseErrorConfig<Error>, TData, FindPetsByTagsStatus200, TQueryKey>,
    toValue(queryClient),
  ) as UseQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  queryResult.queryKey = queryKey as TQueryKey

  return queryResult
}
