/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import type { GetThingPath, GetThingStatus200 } from './types/GetThing'
import { createGetThingResponse } from './createGetThingResponse'
import { faker } from '@faker-js/faker'

export function createGetThingPath(data?: Partial<GetThingPath>): GetThingPath {
  const defaultFakeData = {
    id: faker.number.int(),
  }
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as GetThingPath
}

/**
 * @description The requested thing
 */
export function createGetThingStatus200(data?: Partial<GetThingStatus200>): GetThingStatus200 {
  return createGetThingResponse(data) as GetThingStatus200
}
