/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import type { GetBestSellersOptions, GetBestSellersResponse } from './GetBestSellers'

export function getBestSellers(
  { query }: GetBestSellersOptions = {},
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<GetBestSellersResponse> {
  return cy
    .request<GetBestSellersResponse>({
      method: 'GET',
      url: `/lists/best-sellers`,
      qs: query,
      ...options,
    })
    .then((res) => res.body)
}
