/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { User } from '../User.ts'

/**
 * @type object
 */
export type CreateUsersWithListInputStatus200 = User

/**
 * @type any
 */
export type CreateUsersWithListInputStatusDefault = any

/**
 * @type object
 */
export type CreateUsersWithListInputRequestConfig = {
  data?: never
  pathParams?: never
  queryParams?: never
  headerParams?: never
  /**
   * @type string
   */
  url: '/user/createWithList'
}

/**
 * @type object
 */
export type CreateUsersWithListInputResponses = {
  '200': CreateUsersWithListInputStatus200
  default: CreateUsersWithListInputStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type CreateUsersWithListInputResponse = CreateUsersWithListInputStatus200 | CreateUsersWithListInputStatusDefault
