/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { addPetRequestSchema } from '../addPetRequestSchema'
import { petSchema } from '../petSchema'

export const addPetStatus200SchemaJson = petSchema

export const addPetStatus200SchemaXml = petSchema

export const addPetStatus200Schema = z.union([addPetStatus200SchemaJson, addPetStatus200SchemaXml])

export const addPetStatus405Schema = z.any()

export const addPetResponseSchema = addPetStatus200Schema

export const addPetErrorSchema = addPetStatus405Schema

export const addPetBodySchemaJson = addPetRequestSchema.describe('Create a new pet in the store')

export const addPetBodySchemaXml = petSchema.describe('Create a new pet in the store')

export const addPetBodySchemaFormUrlEncoded = petSchema.describe('Create a new pet in the store')

export const addPetBodySchema = z.union([addPetBodySchemaJson, addPetBodySchemaXml, addPetBodySchemaFormUrlEncoded])