/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { findPetsByStatusStatusSchema } from '../findPetsByStatusStatusSchema.ts'
import { petSchema } from '../petSchema.ts'

export const findPetsByStatusQueryStatusSchema = findPetsByStatusStatusSchema.optional().default('available').describe('Status values that need to be considered for filter')

export const findPetsByStatusStatus200SchemaJson = z.array(petSchema)

export const findPetsByStatusStatus200SchemaXml = z.array(petSchema)

export const findPetsByStatusStatus200Schema = z.union([findPetsByStatusStatus200SchemaJson, findPetsByStatusStatus200SchemaXml])

export const findPetsByStatusStatus400Schema = z.any()

export const findPetsByStatusResponseSchema = findPetsByStatusStatus200Schema

export const findPetsByStatusErrorSchema = findPetsByStatusStatus400Schema