/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { apiResponseSchema } from '../apiResponseSchema.ts'

export const uploadFilePathPetIdSchema = z.bigint().describe('ID of pet to update')

export const uploadFileQueryAdditionalMetadataSchema = z.string().optional().describe('Additional Metadata')

export const uploadFileStatus200Schema = apiResponseSchema

export const uploadFileResponseSchema = uploadFileStatus200Schema

export const uploadFileBodySchema = z.instanceof(File).optional()