/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/fetch'
import type { FindPetsByTagsResponse, FindPetsByTagsQueryTags, FindPetsByTagsQueryPageSize } from './FindPetsByTags'
import type { InfiniteData, QueryKey, QueryClient, UseInfiniteQueryOptions, UseInfiniteQueryReturnType } from '@tanstack/react-query'
import type { MaybeRefOrGetter } from 'vue'
import { fetch } from './.kubb/fetch'
import { infiniteQueryOptions, useInfiniteQuery } from '@tanstack/react-query'
import { toValue } from 'vue'

export const findPetsByTagsInfiniteQueryKey = (params: MaybeRefOrGetter<unknown>) => [{ url: '/pet/findByTags' }, ...(params ? [params] : [])] as const

export type FindPetsByTagsInfiniteQueryKey = ReturnType<typeof findPetsByTagsInfiniteQueryKey>

/**
 * {@link /pet/findByTags}
 */
export async function findPetsByTagsInfinite(
  params: { tags: FindPetsByTagsQueryTags; pageSize?: FindPetsByTagsQueryPageSize },
  config: Partial<RequestConfig> & { client?: Client } = {},
) {
  const { client: request = fetch, ...requestConfig } = config

  const res = await request<FindPetsByTagsResponse, ResponseErrorConfig<Error>, unknown>({ method: 'GET', url: `/pet/findByTags`, params, ...requestConfig })
}

export function findPetsByTagsInfiniteQueryOptions(params: MaybeRefOrGetter<unknown>, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const queryKey = findPetsByTagsInfiniteQueryKey(params)
  return infiniteQueryOptions<FindPetsByTagsResponse, ResponseErrorConfig<Error>, InfiniteData<FindPetsByTagsResponse>, typeof queryKey, number>({
    enabled: !!params,
    queryKey,
    queryFn: async ({ signal }) => {
      return findPetsByTagsInfinite(toValue(params), { ...config, signal: config.signal ?? signal })
    },
    initialPageParam: 0,
    getNextPageParam: (lastPage) => lastPage['cursor'],
    getPreviousPageParam: (firstPage) => firstPage['cursor'],
  })
}

/**
 * {@link /pet/findByTags}
 */
export function useFindPetsByTagsInfinite<
  TData = InfiniteData<FindPetsByTagsResponse>,
  TQueryData = FindPetsByTagsResponse,
  TQueryKey extends QueryKey = FindPetsByTagsInfiniteQueryKey,
>(
  params: MaybeRefOrGetter<unknown>,
  options: {
    query?: Partial<UseInfiniteQueryOptions<FindPetsByTagsResponse, ResponseErrorConfig<Error>, TQueryData, TQueryKey, TQueryData>> & { client?: QueryClient }
    client?: Partial<RequestConfig> & { client?: Client }
  } = {},
) {
  const { query: queryConfig = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...resolvedOptions } = queryConfig
  const queryKey = (resolvedOptions && 'queryKey' in resolvedOptions ? toValue(resolvedOptions.queryKey) : undefined) ?? findPetsByTagsInfiniteQueryKey(params)

  const query = useInfiniteQuery(
    {
      ...findPetsByTagsInfiniteQueryOptions(params, config),
      ...resolvedOptions,
      queryKey,
    } as unknown as UseInfiniteQueryOptions<FindPetsByTagsResponse, ResponseErrorConfig<Error>, FindPetsByTagsResponse, TQueryKey, FindPetsByTagsResponse>,
    toValue(queryClient),
  ) as UseInfiniteQueryReturnType<TData, ResponseErrorConfig<Error>> & { queryKey: TQueryKey }

  query.queryKey = queryKey as TQueryKey

  return query
}
