/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { AddPetData, AddPetStatus200, AddPetStatus405 } from '../types/AddPet.ts'
import { client } from '../.kubb/client.ts'

function getAddPetUrl() {
  const res = { method: 'POST', url: `https://api.example.com/v1/pet` as const }

  return res
}

/**
 * @description Add a new pet to the store
 * @summary Add a new pet to the store
 * {@link /pet}
 */
export async function addPet(data: AddPetData, config: Partial<RequestConfig<AddPetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = 'application/json', ...requestConfig } = config

  const requestData = data

  const res = await request<AddPetStatus200, ResponseErrorConfig<AddPetStatus405>, AddPetData>({ method: 'POST', url: getAddPetUrl().url.toString(), data: requestData, contentType, ...requestConfig })

  return res.data
}