/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import useSWRMutation from 'swr/mutation'
import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { UpdatePetData, UpdatePetStatus200, UpdatePetStatus400, UpdatePetStatus404, UpdatePetStatus405 } from '../types/UpdatePet.ts'
import type { SWRMutationConfiguration } from 'swr/mutation'
import { client } from '../.kubb/client.ts'

export const updatePetMutationKey = () => [{ url: '/pet' }] as const

export type UpdatePetMutationKey = ReturnType<typeof updatePetMutationKey>

/**
 * @description Update an existing pet by Id
 * @summary Update an existing pet
 * {@link /pet}
 */
export async function updatePet(data: UpdatePetData, config: Partial<RequestConfig<UpdatePetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = 'application/json', ...requestConfig } = config

  const requestData = data

  const res = await request<UpdatePetStatus200 | UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405, ResponseErrorConfig<UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405>, UpdatePetData>({ method: 'PUT', url: `/pet`, data: requestData, contentType, ...requestConfig })

  return res as ({ status: 200; data: UpdatePetStatus200; statusText: string } | { status: 400; data: UpdatePetStatus400; statusText: string } | { status: 404; data: UpdatePetStatus404; statusText: string } | { status: 405; data: UpdatePetStatus405; statusText: string })
}

export type UpdatePetMutationArg = { data: UpdatePetData }

/**
 * @description Update an existing pet by Id
 * @summary Update an existing pet
 * {@link /pet}
 */
export function useUpdatePet(options: {
  mutation?: SWRMutationConfiguration<({ status: 200; data: UpdatePetStatus200; statusText: string } | { status: 400; data: UpdatePetStatus400; statusText: string } | { status: 404; data: UpdatePetStatus404; statusText: string } | { status: 405; data: UpdatePetStatus405; statusText: string }), ResponseErrorConfig<UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405>, UpdatePetMutationKey | null, UpdatePetMutationArg> & { throwOnError?: boolean },
  client?: Partial<RequestConfig<UpdatePetData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" },
  shouldFetch?: boolean,
} = {}) {
  const { mutation: mutationOptions, client: config = {}, shouldFetch = true } = options ?? {}
  const mutationKey = updatePetMutationKey()

  return useSWRMutation<({ status: 200; data: UpdatePetStatus200; statusText: string } | { status: 400; data: UpdatePetStatus400; statusText: string } | { status: 404; data: UpdatePetStatus404; statusText: string } | { status: 405; data: UpdatePetStatus405; statusText: string }), ResponseErrorConfig<UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405>, UpdatePetMutationKey | null, UpdatePetMutationArg>(
    shouldFetch ? mutationKey : null,
    async (_url, { arg: { data } }) => {
      return updatePet(data, config)
    },
    mutationOptions
  )
}