/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { FindPetsByStatusRequestConfig, FindPetsByStatusResponse } from '../models.ts'

export function findPetsByStatus(
  { query }: FindPetsByStatusRequestConfig = {},
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<FindPetsByStatusResponse> {
  return cy
    .request<FindPetsByStatusResponse>({
      method: 'GET',
      url: `http://localhost:3000/pet/findByStatus`,
      qs: query,
      ...options,
    })
    .then((res) => res.body)
}
