/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { PlaceOrderOptions, PlaceOrderResponse } from '../models'

export function placeOrder({ body }: PlaceOrderOptions, options: Partial<Cypress.RequestOptions> = {}): Cypress.Chainable<PlaceOrderResponse> {
  return cy
    .request<PlaceOrderResponse>({
      method: 'POST',
      url: `http://localhost:3000/store/order`,
      body,
      ...options,
    })
    .then((res) => res.body)
}
