/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { UpdatePetWithFormOptions, UpdatePetWithFormResponse } from '../models'

export function updatePetWithForm(
  { path, query }: UpdatePetWithFormOptions,
  options: Partial<Cypress.RequestOptions> = {},
): Cypress.Chainable<UpdatePetWithFormResponse> {
  return cy
    .request<UpdatePetWithFormResponse>({
      method: 'POST',
      url: `http://localhost:3000/pet/${path.petId}`,
      qs: query,
      ...options,
    })
    .then((res) => res.body)
}
