/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { addPetRequestSchema } from "./addPetRequestSchema.ts";
import { petSchema } from "./petSchema.ts";

export const addPetStatus200Schema = petSchema

export type AddPetStatus200Schema = v.InferOutput<typeof addPetStatus200Schema>

export const addPetStatus405Schema = v.any()

export type AddPetStatus405Schema = v.InferOutput<typeof addPetStatus405Schema>

export const addPetResponseSchema = v.union([addPetStatus200Schema, addPetStatus405Schema])

export type AddPetResponseSchema = v.InferOutput<typeof addPetResponseSchema>

export const addPetDataSchema = v.pipe(addPetRequestSchema, v.description("Create a new pet in the store"))

export type AddPetDataSchema = v.InferOutput<typeof addPetDataSchema>