/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";
import { petSchema } from "./petSchema.ts";

export const findPetsByTagsQueryTagsSchema = v.pipe(v.optional(v.array(v.string())), v.description("Tags to filter by"))

export type FindPetsByTagsQueryTagsSchema = v.InferOutput<typeof findPetsByTagsQueryTagsSchema>

export const findPetsByTagsStatus200Schema = v.array(petSchema)

export type FindPetsByTagsStatus200Schema = v.InferOutput<typeof findPetsByTagsStatus200Schema>

export const findPetsByTagsStatus400Schema = v.any()

export type FindPetsByTagsStatus400Schema = v.InferOutput<typeof findPetsByTagsStatus400Schema>

export const findPetsByTagsResponseSchema = v.union([findPetsByTagsStatus200Schema, findPetsByTagsStatus400Schema])

export type FindPetsByTagsResponseSchema = v.InferOutput<typeof findPetsByTagsResponseSchema>