/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as v from "valibot";

export const loginUserQueryUsernameSchema = v.pipe(v.optional(v.string()), v.description("The user name for login"))

export type LoginUserQueryUsernameSchema = v.InferOutput<typeof loginUserQueryUsernameSchema>

export const loginUserQueryPasswordSchema = v.pipe(v.optional(v.string()), v.description("The password for login in clear text"))

export type LoginUserQueryPasswordSchema = v.InferOutput<typeof loginUserQueryPasswordSchema>

export const loginUserStatus200Schema = v.string()

export type LoginUserStatus200Schema = v.InferOutput<typeof loginUserStatus200Schema>

export const loginUserStatus400Schema = v.any()

export type LoginUserStatus400Schema = v.InferOutput<typeof loginUserStatus400Schema>

export const loginUserResponseSchema = v.union([loginUserStatus200Schema, loginUserStatus400Schema])

export type LoginUserResponseSchema = v.InferOutput<typeof loginUserResponseSchema>