/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

/**
 * @type string
 */
export type GetEnterpriseConfigurationsIdV20250PathEnterpriseId = string

/**
 * @type object
 */
export type GetEnterpriseConfigurationsIdV20250Status200 = object

/**
 * @type object
 */
export type GetEnterpriseConfigurationsIdV20250RequestConfig = {
  body?: never
  /**
   * @type object | undefined
   */
  path?: {
    enterprise_id: GetEnterpriseConfigurationsIdV20250PathEnterpriseId
  }
  query?: never
  headers?: never
  /**
   * @type string
   */
  url: `/enterprise_configurations/${string}`
}

/**
 * @type object
 */
export type GetEnterpriseConfigurationsIdV20250Responses = {
  '200': GetEnterpriseConfigurationsIdV20250Status200
}

/**
 * @description Union of all possible responses
 */
export type GetEnterpriseConfigurationsIdV20250Response = GetEnterpriseConfigurationsIdV20250Status200
