/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Item } from './Item'

export type GetItemPath = {
    /**
     * @description
     * Format: `int64`
     * @type integer
    */
    id: bigint;
};

export type GetItemStatus200 = Item;

export type GetItemOptions = {
    body?: never;
    path: GetItemPath;
    query?: never;
    headers?: never;
};

export type GetItemResponses = {
    "200": GetItemStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetItemResponse = GetItemStatus200;