/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @type object
*/
export type Item = {
    /**
     * @description
     * Format: `int64`
     * @type integer
    */
    id: bigint;
    /**
     * @type string
    */
    name: string;
    /**
     * @description
     * Format: `int32`
     * @type integer | undefined
    */
    count?: number;
};