/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

import { showPetByIdHandler } from './showPetById'
import { showPetByIdPathPetIdSchema, showPetByIdStatus200Schema } from './showPetByIdSchema'
import { McpServer } from '@modelcontextprotocol/sdk/server/mcp.js'
import { StdioServerTransport } from '@modelcontextprotocol/sdk/server/stdio.js'
import { z } from 'zod'

export function getServer() {
  const server = new McpServer({
    name: 'server',
    version: '0.0.0',
  })

  server.registerTool(
    'showPetById',
    {
      description: 'Make a GET request to /pets/{petId}',
      outputSchema: { data: showPetByIdStatus200Schema },
      inputSchema: { path: z.object({ petId: showPetByIdPathPetIdSchema }) },
    },
    async ({ path }, request) => {
      return showPetByIdHandler({ path }, request)
    },
  )

  return server
}

export const server = getServer()

export async function startServer() {
  try {
    const transport = new StdioServerTransport()
    await server.connect(transport)
  } catch (error) {
    console.error('Failed to start server:', error)
    process.exit(1)
  }
}
