/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePetData, UpdatePetFormUrlEncodedData, UpdatePetJsonData, UpdatePetResponse, UpdatePetStatus200, UpdatePetStatus200Json, UpdatePetStatus200Xml, UpdatePetStatus400, UpdatePetStatus404, UpdatePetStatus405, UpdatePetXmlData } from "../types/UpdatePet.ts";
import { createPet } from "./createPet.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Successful operation
 */
export function createUpdatePetStatus200Json(data?: Partial<UpdatePetStatus200Json>): UpdatePetStatus200Json {
  return createPet(data) as UpdatePetStatus200Json
}

/**
 * @description Successful operation
 */
export function createUpdatePetStatus200Xml(data?: Partial<UpdatePetStatus200Xml>): UpdatePetStatus200Xml {
  return createPet(data) as UpdatePetStatus200Xml
}

/**
 * @description Successful operation
 */
export function createUpdatePetStatus200(_data?: UpdatePetStatus200): UpdatePetStatus200 {
  return faker.helpers.arrayElement<any>([createUpdatePetStatus200Json(), createUpdatePetStatus200Xml()])
}

/**
 * @description Invalid ID supplied
 */
export function createUpdatePetStatus400() {
  return undefined
}

/**
 * @description Pet not found
 */
export function createUpdatePetStatus404() {
  return undefined
}

/**
 * @description Validation exception
 */
export function createUpdatePetStatus405() {
  return undefined
}

/**
 * @description Update an existent pet in the store
 */
export function createUpdatePetJsonData(data?: Partial<UpdatePetJsonData>): UpdatePetJsonData {
  return createPet(data) as UpdatePetJsonData
}

/**
 * @description Update an existent pet in the store
 */
export function createUpdatePetXmlData(data?: Partial<UpdatePetXmlData>): UpdatePetXmlData {
  return createPet(data) as UpdatePetXmlData
}

/**
 * @description Update an existent pet in the store
 */
export function createUpdatePetFormUrlEncodedData(data?: Partial<UpdatePetFormUrlEncodedData>): UpdatePetFormUrlEncodedData {
  return createPet(data) as UpdatePetFormUrlEncodedData
}

/**
 * @description Update an existent pet in the store
 */
export function createUpdatePetData(_data?: UpdatePetData): UpdatePetData {
  return faker.helpers.arrayElement<any>([createUpdatePetJsonData(), createUpdatePetXmlData(), createUpdatePetFormUrlEncodedData()])
}

export function createUpdatePetResponse(_data?: UpdatePetResponse): UpdatePetResponse {
  return faker.helpers.arrayElement<any>([createUpdatePetStatus200(), createUpdatePetStatus400(), createUpdatePetStatus404(), createUpdatePetStatus405()])
}