/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod";
import { petSchema } from "./petSchema.ts";

export const getPetByIdPathPetIdSchema = z.int().describe("ID of pet to return")

export const getPetByIdStatus200Schema = petSchema

export const getPetByIdStatus400Schema = z.any()

export const getPetByIdStatus404Schema = z.any()

export const getPetByIdResponseSchema = z.union([getPetByIdStatus200Schema, getPetByIdStatus400Schema, getPetByIdStatus404Schema])