/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from 'zod'
import { animalSchema } from './animalSchema'

export const catSchema = animalSchema.extend({
  huntingSkill: z.string().optional(),
})