/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { User } from './User.ts'

/**
 * @type object
*/
export type GetMeRequestConfig = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

/**
 * @type object
*/
export type GetMeResponses = {
    "200": User;
};