/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { addPetHandler } from "./addPet.ts";
import { deletePetHandler } from "./deletePet.ts";
import { findPetsByStatusHandler } from "./findPetsByStatus.ts";
import { findPetsByTagsHandler } from "./findPetsByTags.ts";
import { getPetByIdHandler } from "./getPetById.ts";
import { updatePetHandler } from "./updatePet.ts";
import { updatePetWithFormHandler } from "./updatePetWithForm.ts";
import { uploadFileHandler } from "./uploadFile.ts";
import { addPetDataSchema, addPetStatus200Schema } from "../zod/addPetSchema.ts";
import { deletePetHeaderApiKeySchema, deletePetPathPetIdSchema } from "../zod/deletePetSchema.ts";
import { findPetsByStatusQueryStatusSchema, findPetsByStatusStatus200Schema } from "../zod/findPetsByStatusSchema.ts";
import { findPetsByTagsQueryTagsSchema, findPetsByTagsStatus200Schema } from "../zod/findPetsByTagsSchema.ts";
import { getPetByIdPathPetIdSchema, getPetByIdStatus200Schema } from "../zod/getPetByIdSchema.ts";
import { updatePetDataSchema, updatePetStatus200Schema } from "../zod/updatePetSchema.ts";
import { updatePetWithFormPathPetIdSchema, updatePetWithFormQueryNameSchema, updatePetWithFormQueryStatusSchema } from "../zod/updatePetWithFormSchema.ts";
import { uploadFileDataSchema, uploadFilePathPetIdSchema, uploadFileQueryAdditionalMetadataSchema, uploadFileStatus200Schema } from "../zod/uploadFileSchema.ts";
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio";
import { z } from "zod";

export const server = 
          new McpServer({
  name: 'Swagger PetStore - OpenAPI 3.0',
  version: '1.0.11',
})
          

server.registerTool("updatePet", {
  title: "Update an existing pet",
  description: "Update an existing pet by Id",
  outputSchema: { data: updatePetStatus200Schema },
  inputSchema: { data: updatePetDataSchema },
}, async ({ data }) => {
  return updatePetHandler({ data })
})
          

server.registerTool("addPet", {
  title: "Add a new pet to the store",
  description: "Add a new pet to the store",
  outputSchema: { data: addPetStatus200Schema },
  inputSchema: { data: addPetDataSchema },
}, async ({ data }) => {
  return addPetHandler({ data })
})
          

server.registerTool("findPetsByStatus", {
  title: "Finds Pets by status",
  description: "Multiple status values can be provided with comma separated strings",
  outputSchema: { data: findPetsByStatusStatus200Schema },
  inputSchema: { params: z.object({ "status": findPetsByStatusQueryStatusSchema }) },
}, async ({ params }) => {
  return findPetsByStatusHandler({ params })
})
          

server.registerTool("findPetsByTags", {
  title: "Finds Pets by tags",
  description: "Multiple tags can be provided with comma separated strings. Use tag1, tag2, tag3 for testing.",
  outputSchema: { data: findPetsByTagsStatus200Schema },
  inputSchema: { params: z.object({ "tags": findPetsByTagsQueryTagsSchema }) },
}, async ({ params }) => {
  return findPetsByTagsHandler({ params })
})
          

server.registerTool("getPetById", {
  title: "Find pet by ID",
  description: "Returns a single pet",
  outputSchema: { data: getPetByIdStatus200Schema },
  inputSchema: { petId: getPetByIdPathPetIdSchema },
}, async ({ petId }) => {
  return getPetByIdHandler({ petId })
})
          

server.registerTool("updatePetWithForm", {
  title: "Updates a pet in the store with form data",
  description: "Make a POST request to /pet/{petId}",
  inputSchema: { petId: updatePetWithFormPathPetIdSchema, params: z.object({ "name": updatePetWithFormQueryNameSchema, "status": updatePetWithFormQueryStatusSchema }) },
}, async ({ petId, params }) => {
  return updatePetWithFormHandler({ petId, params })
})
          

server.registerTool("deletePet", {
  title: "Deletes a pet",
  description: "delete a pet",
  inputSchema: { petId: deletePetPathPetIdSchema, headers: z.object({ "api_key": deletePetHeaderApiKeySchema }) },
}, async ({ petId, headers }) => {
  return deletePetHandler({ petId, headers })
})
          

server.registerTool("uploadFile", {
  title: "uploads an image",
  description: "Make a POST request to /pet/{petId}/uploadImage",
  outputSchema: { data: uploadFileStatus200Schema },
  inputSchema: { petId: uploadFilePathPetIdSchema, data: uploadFileDataSchema, params: z.object({ "additionalMetadata": uploadFileQueryAdditionalMetadataSchema }) },
}, async ({ petId, data, params }) => {
  return uploadFileHandler({ petId, data, params })
})
          
export async function startServer() {
  try {
      const transport = new StdioServerTransport()
      await server.connect(transport)

    } catch (error) {
      console.error('Failed to start server:', error)
      process.exit(1)
    }
}