/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import fetch from "@kubb/plugin-client/clients/axios";
import type { UpdateUserData, UpdateUserResponse, UpdateUserPathUsername } from "../types/UpdateUser.ts";
import type { Client, RequestConfig, ResponseErrorConfig } from "@kubb/plugin-client/clients/axios";
import type { MutationObserverOptions, QueryClient } from "@tanstack/vue-query";
import type { MaybeRefOrGetter } from "vue";
import { updateUserResponseSchema, updateUserDataSchema } from "../zod/updateUserSchema.ts";
import { useMutation } from "@tanstack/vue-query";

export const updateUserMutationKey = () => [{ url: '/user/:username' }] as const

/**
 * @description This can only be done by the logged in user.
 * @summary Update user
 * {@link /user/:username}
 */
export async function updateUser(username: UpdateUserPathUsername, data?: UpdateUserData, config: Partial<RequestConfig<UpdateUserData>> & { client?: Client } = {}) {
  const { client: request = fetch, ...requestConfig } = config


  const requestData = updateUserDataSchema.parse(data)


  const res = await request<UpdateUserResponse, ResponseErrorConfig<Error>, UpdateUserData>({ method: "PUT", url: `/user/${username}`, data: requestData, ...requestConfig })

  return updateUserResponseSchema.parse(res.data)
}

/**
 * @description This can only be done by the logged in user.
 * @summary Update user
 * {@link /user/:username}
 */
export function useUpdateUser<TContext>(options: {
  mutation?: MutationObserverOptions<UpdateUserResponse, ResponseErrorConfig<Error>, {username: MaybeRefOrGetter<UpdateUserPathUsername>, data?: MaybeRefOrGetter<UpdateUserData>}, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UpdateUserData>> & { client?: Client },
} = {}) {

          const { mutation = {}, client: config = {} } = options ?? {}
          const { client: queryClient, ...mutationOptions } = mutation;
          const mutationKey = mutationOptions?.mutationKey ?? updateUserMutationKey()

          return useMutation<UpdateUserResponse, ResponseErrorConfig<Error>, {username: UpdateUserPathUsername, data?: UpdateUserData}, TContext>({
            mutationFn: async({ username, data }) => {
              return updateUser(username, data, config)
            },
            mutationKey,
            ...mutationOptions
          }, queryClient)

}