/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import type { UploadFileRequestConfig, UploadFileData, UploadFileStatus200 } from '../types/UploadFile.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'
import type { MutationObserverOptions, QueryClient } from '@tanstack/vue-query'
import type { z } from 'zod'
import { uploadFileResponseSchema, uploadFileDataSchema } from '../zod/uploadFileSchema.ts'
import { useMutation } from '@tanstack/vue-query'

export const uploadFileMutationKey = () => [{ url: '/pet/:petId/uploadImage' }] as const

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export async function uploadFile({ path, query, body }: Omit<UploadFileRequestConfig, 'url'>, config: Partial<RequestConfig<UploadFileData>> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const { petId } = path

  const requestBody = uploadFileDataSchema.parse(body)

  const res = await request<UploadFileStatus200, ResponseErrorConfig<Error>, z.input<typeof uploadFileDataSchema>>({ method: 'POST', url: `/pet/${petId}/uploadImage`, query, body: requestBody, ...requestConfig, headers: { 'Content-Type': 'application/octet-stream', ...requestConfig.headers } })

  return uploadFileResponseSchema.parse(res.data)
}

/**
 * @summary uploads an image
 * {@link /pet/:petId/uploadImage}
 */
export function useUploadFile<TContext>(options: {
  mutation?: MutationObserverOptions<UploadFileStatus200, ResponseErrorConfig<Error>, Omit<UploadFileRequestConfig, 'url'>, TContext> & { client?: QueryClient },
  client?: Partial<RequestConfig<UploadFileData>> & { client?: Client },
} = {}) {
  const { mutation = {}, client: config = {} } = options ?? {}
  const { client: queryClient, ...mutationOptions } = mutation;
  const mutationKey = mutationOptions?.mutationKey ?? uploadFileMutationKey()

  return useMutation<UploadFileStatus200, ResponseErrorConfig<Error>, Omit<UploadFileRequestConfig, 'url'>, TContext>({
    mutationFn: async({ path, query, body }) => {
      return uploadFile({ path, query, body }, config)
    },
    mutationKey,
    ...mutationOptions
  }, queryClient)
}