/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Order } from '../Order.ts'

/**
 * @type any
 */
export type PlaceOrderStatus405 = any

/**
 * @description Order description
 * @type object | undefined
 */
export type PlaceOrderJsonData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderXmlData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderFormUrlEncodedData = Order | undefined

export type PlaceOrderData = PlaceOrderJsonData | PlaceOrderXmlData | PlaceOrderFormUrlEncodedData

/**
 * @type object
 */
export type PlaceOrderRequestConfig = {
  body: PlaceOrderData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type PlaceOrderResponses = {
  '200': Order
  '405': PlaceOrderStatus405
}

/**
 * @description Union of all possible responses
 */
export type PlaceOrderResponse = Order | PlaceOrderStatus405
