/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Order } from "./Order.ts";

/**
 * @type object
*/
export type CreateOrderStatus201 = Order;

/**
 * @type object
*/
export type CreateOrderRequestConfig = {
    data?: never;
    pathParams?: never;
    queryParams?: never;
    headerParams?: never;
    /**
     * @type string
    */
    url: "/orders";
};

/**
 * @type object
*/
export type CreateOrderResponses = {
    "201": CreateOrderStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateOrderResponse = CreateOrderStatus201;