/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { OrderSchema } from './OrderSchema.ts'

/**
 * @type object
*/
export type CreateOrderStatus201 = OrderSchema;

/**
 * @description Order request body
 * @type object | undefined
*/
export type CreateOrderBody = {
    /**
     * @type string | undefined
    */
    userId?: string;
    /**
     * @type array | undefined
    */
    productIds?: string[];
} | undefined;

/**
 * @type object
*/
export type CreateOrderRequestConfig = {
    body: CreateOrderBody;
    path?: never;
    query?: never;
    headers?: never;
};

/**
 * @type object
*/
export type CreateOrderResponses = {
    "201": CreateOrderStatus201;
};

/**
 * @description Union of all possible responses
*/
export type CreateOrderResponse = CreateOrderStatus201;