/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Variant } from './Variant'

export type GetVariantsStatus200 = Variant;

export type GetVariantsOptions = {
    body?: never;
    path?: never;
    query?: never;
    headers?: never;
};

export type GetVariantsResponses = {
    "200": GetVariantsStatus200;
};

/**
 * @description Union of all possible responses
*/
export type GetVariantsResponse = GetVariantsStatus200;