/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { VariantTypeEnumKey } from './VariantTypeEnum'

export type Variant = {
    id?: string;
    name?: string;
    type?: VariantTypeEnumKey;
};