/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import { paymentMethodUnionSchema } from './paymentMethodUnionSchema.ts'

export const extendedPaymentMethodUnionSchema = paymentMethodUnionSchema