/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

export const orderParamsStatusEnum = {
  placed: 'placed',
  approved: 'approved',
  delivered: 'delivered',
} as const

export type OrderParamsStatusEnumenumType = (typeof orderParamsStatusEnum)[keyof typeof orderParamsStatusEnum]

export const orderStatus = {
  accepted: 'accepted',
} as const

export type OrderStatusenumType = (typeof orderStatus)[keyof typeof orderStatus]

export const orderHttpStatusEnum = {
  '200': 200,
  '400': 400,
  '500': 500,
} as const

export type OrderHttpStatusEnumenumType = (typeof orderHttpStatusEnum)[keyof typeof orderHttpStatusEnum]

export const customerParamsStatusEnum = {
  placed: 'placed',
  approved: 'approved',
  delivered: 'delivered',
} as const

export type CustomerParamsStatusEnumenumType = (typeof customerParamsStatusEnum)[keyof typeof customerParamsStatusEnum]

export const petTypeEnum = {
  dog: 'dog',
  cat: 'cat',
} as const

export type PetTypeEnumenumType = (typeof petTypeEnum)[keyof typeof petTypeEnum]

export const petStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type PetStatusEnumenumType = (typeof petStatusEnum)[keyof typeof petStatusEnum]

export const addPetRequestStatusEnum = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
  'in store': 'in store',
} as const

export type AddPetRequestStatusEnumenumType = (typeof addPetRequestStatusEnum)[keyof typeof addPetRequestStatusEnum]

export const findPetsByStatusStatus = {
  available: 'available',
  pending: 'pending',
  sold: 'sold',
} as const

export type FindPetsByStatusStatusenumType = (typeof findPetsByStatusStatus)[keyof typeof findPetsByStatusStatus]

export const deletePetStatus200Enum = {
  TYPE1: 'TYPE1',
  TYPE2: 'TYPE2',
  TYPE3: 'TYPE3',
} as const

export type DeletePetStatus200EnumenumType = (typeof deletePetStatus200Enum)[keyof typeof deletePetStatus200Enum]

/**
 * @type object
 */
export type Order = {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @description
   * Format: `int64`
   * @example 198772
   * @type integer | undefined
   */
  petId?: bigint
  /**
   * @type object | undefined
   */
  params?: {
    /**
     * @description Order Status
     * @example approved
     */
    status: OrderParamsStatusEnumenumType
    /**
     * @type string
     */
    type: string
  }
  /**
   * @description
   * Format: `int32`
   * @example 7
   * @type integer | undefined
   */
  quantity?: number
  /**
   * @description
   * Format: `date-time`
   * @type string | undefined
   */
  shipDate?: string
  /**
   * @description Order Status
   */
  status?: OrderStatusenumType | string
  /**
   * @description HTTP Status
   * @example 200
   */
  http_status?: OrderHttpStatusEnumenumType
  /**
   * @type boolean | undefined
   */
  complete?: boolean
}

/**
 * @type object
 */
export type Address = {
  /**
   * @type string | undefined
   */
  streetName?: string
  /**
   * @type string | undefined
   */
  streetNumber?: string
  /**
   * @example Palo Alto
   * @type string | undefined
   */
  city?: string
  /**
   * @example CA
   * @type string | undefined
   */
  state?: string
  /**
   * @example 94301
   * @type string | undefined
   */
  zip?: string
}

/**
 * @type object
 */
export type Customer = {
  /**
   * @description
   * Format: `int64`
   * @example 100000
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @type object | undefined
   */
  params?: {
    /**
     * @description Order Status
     * @example approved
     */
    status: CustomerParamsStatusEnumenumType
    /**
     * @type string
     */
    type: string
  }
  /**
   * @example fehguy
   * @type string | undefined
   */
  username?: string
  /**
   * @type array | undefined
   */
  address?: Array<Address>
}

export type HappyCustomer = Customer & {
  /**
   * @type boolean | undefined
   */
  isHappy?: true
}

export type UnhappyCustomer = Customer & {
  /**
   * @type string | undefined
   */
  reasonToBeUnhappy?: string
  /**
   * @type boolean | undefined
   */
  isHappy?: false
}

/**
 * @type object
 */
export type Category = {
  /**
   * @description
   * Format: `int64`
   * @example 1
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @example Dogs
   * @type string | undefined
   */
  name?: string
}

/**
 * @type object
 */
export type Tag = {
  /**
   * @description
   * Format: `int64`
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @type string | undefined
   */
  name?: string
}

/**
 * @type object
 */
export type Dog = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  readonly type?: string
  /**
   * @type string | undefined
   */
  bark?: string
}

/**
 * @type object
 */
export type Cat = {
  /**
   * @minLength 1
   * @type string | undefined
   */
  readonly type?: string
  /**
   * @type string | undefined
   */
  name?: string
}

export type Pet = (
  | (Dog & {
      /**
       * @type string
       */
      readonly type: 'dog'
    })
  | (Cat & {
      /**
       * @type string
       */
      readonly type: 'cat'
    })
) & {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  readonly type: PetTypeEnumenumType
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category
  /**
   * @type array
   */
  photoUrls: Array<string>
  /**
   * @type array | undefined
   */
  readonly tags?: Array<Tag>
  /**
   * @description pet status in the store
   */
  status?: PetStatusEnumenumType
}

export type FullAddress = Address & {
  /**
   * @type string
   */
  streetNumber: string
} & {
  /**
   * @type string
   */
  streetName: string
}

/**
 * @type object
 */
export type AddPetRequest = {
  /**
   * @description
   * Format: `int64`
   * @example 10
   * @type integer | undefined
   */
  id?: bigint
  /**
   * @example doggie
   * @type string
   */
  name: string
  /**
   * @type object | undefined
   */
  category?: Category
  /**
   * @type array
   */
  photoUrls: Array<string>
  /**
   * @type array | undefined
   */
  tags?: Array<Tag>
  /**
   * @description pet status in the store
   */
  status?: AddPetRequestStatusEnumenumType
}

/**
 * @type object
 */
export type ApiResponse = {
  /**
   * @description
   * Format: `int32`
   * @type integer | undefined
   */
  code?: number
  /**
   * @type string | undefined
   */
  type?: string
  /**
   * @type string | undefined
   */
  message?: string
}

/**
 * @type object
 */
export type PetNotFound = {
  /**
   * @description
   * Format: `int32`
   * @type integer | undefined
   */
  code?: number
  /**
   * @type string | undefined
   */
  message?: string
}

export type UpdatePetStatus200Json = Pet

export type UpdatePetStatus200Xml = Pet

export type UpdatePetStatus200 = UpdatePetStatus200Json | UpdatePetStatus200Xml

/**
 * @type unknown
 */
export type UpdatePetStatus400 = unknown

/**
 * @type unknown
 */
export type UpdatePetStatus404 = unknown

/**
 * @type unknown
 */
export type UpdatePetStatus405 = unknown

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetJsonData = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetXmlData = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @description Update an existent pet in the store
 */
export type UpdatePetFormUrlEncodedData = Omit<NonNullable<Pet>, 'type' | 'tags'>

export type UpdatePetData = UpdatePetJsonData | UpdatePetXmlData | UpdatePetFormUrlEncodedData

/**
 * @type object
 */
export type UpdatePetRequestConfig = {
  body: UpdatePetData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type UpdatePetResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: UpdatePetStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: UpdatePetStatus200Xml
      }
  '400': UpdatePetStatus400
  '404': UpdatePetStatus404
  '405': UpdatePetStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetResponse = UpdatePetStatus200 | UpdatePetStatus400 | UpdatePetStatus404 | UpdatePetStatus405

export type AddPetStatus200Json = Pet

export type AddPetStatus200Xml = Pet

export type AddPetStatus200 = AddPetStatus200Json | AddPetStatus200Xml

/**
 * @type object
 */
export type AddPetStatus405 = {
  /**
   * @description
   * Format: `int32`
   * @type integer | undefined
   */
  code?: number
  /**
   * @type string | undefined
   */
  message?: string
}

/**
 * @description Create a new pet in the store
 * @type object
 */
export type AddPetJsonData = AddPetRequest

/**
 * @description Create a new pet in the store
 */
export type AddPetXmlData = Omit<NonNullable<Pet>, 'type' | 'tags'>

/**
 * @description Create a new pet in the store
 */
export type AddPetFormUrlEncodedData = Omit<NonNullable<Pet>, 'type' | 'tags'>

export type AddPetData = AddPetJsonData | AddPetXmlData | AddPetFormUrlEncodedData

/**
 * @type object
 */
export type AddPetRequestConfig = {
  body: AddPetData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type AddPetResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: AddPetStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: AddPetStatus200Xml
      }
  '405': AddPetStatus405
}

/**
 * @description Union of all possible responses
 */
export type AddPetResponse = AddPetStatus200 | AddPetStatus405

/**
 * @description Status values that need to be considered for filter
 * @default available
 */
export type FindPetsByStatusQueryStatus = FindPetsByStatusStatusenumType | undefined

/**
 * @type array
 */
export type FindPetsByStatusStatus200Json = Array<Pet>

/**
 * @type array
 */
export type FindPetsByStatusStatus200Xml = Array<Pet>

export type FindPetsByStatusStatus200 = FindPetsByStatusStatus200Json | FindPetsByStatusStatus200Xml

/**
 * @type unknown
 */
export type FindPetsByStatusStatus400 = unknown

/**
 * @type object
 */
export type FindPetsByStatusRequestConfig = {
  body?: never
  path?: never
  /**
   * @type object | undefined
   */
  query?: {
    status?: FindPetsByStatusQueryStatus
  }
  headers?: never
}

/**
 * @type object
 */
export type FindPetsByStatusResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: FindPetsByStatusStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: FindPetsByStatusStatus200Xml
      }
  '400': FindPetsByStatusStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByStatusResponse = FindPetsByStatusStatus200 | FindPetsByStatusStatus400

/**
 * @description Tags to filter by
 * @type array | undefined
 */
export type FindPetsByTagsQueryTags = Array<string> | undefined

/**
 * @description to request with required page number or pagination
 * @type string | undefined
 */
export type FindPetsByTagsQueryPage = string | undefined

/**
 * @description to request with required page size
 * @type string | undefined
 */
export type FindPetsByTagsQueryPageSize = string | undefined

/**
 * @type array
 */
export type FindPetsByTagsStatus200Json = Array<Pet>

/**
 * @type array
 */
export type FindPetsByTagsStatus200Xml = Array<Pet>

export type FindPetsByTagsStatus200 = FindPetsByTagsStatus200Json | FindPetsByTagsStatus200Xml

/**
 * @type unknown
 */
export type FindPetsByTagsStatus400 = unknown

/**
 * @type object
 */
export type FindPetsByTagsRequestConfig = {
  body?: never
  path?: never
  /**
   * @type object | undefined
   */
  query?: {
    tags?: FindPetsByTagsQueryTags
    page?: FindPetsByTagsQueryPage
    pageSize?: FindPetsByTagsQueryPageSize
  }
  headers?: never
}

/**
 * @type object
 */
export type FindPetsByTagsResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: FindPetsByTagsStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: FindPetsByTagsStatus200Xml
      }
  '400': FindPetsByTagsStatus400
}

/**
 * @description Union of all possible responses
 */
export type FindPetsByTagsResponse = FindPetsByTagsStatus200 | FindPetsByTagsStatus400

/**
 * @description ID of pet to return
 *
 * Format: `int64`
 * @type integer
 */
export type GetPetByIdPathPetId = bigint

export type GetPetByIdStatus200Json = Pet

export type GetPetByIdStatus200Xml = Pet

export type GetPetByIdStatus200 = GetPetByIdStatus200Json | GetPetByIdStatus200Xml

/**
 * @type unknown
 */
export type GetPetByIdStatus400 = unknown

/**
 * @type unknown
 */
export type GetPetByIdStatus404 = unknown

/**
 * @type object
 */
export type GetPetByIdRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    petId: GetPetByIdPathPetId
  }
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type GetPetByIdResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: GetPetByIdStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: GetPetByIdStatus200Xml
      }
  '400': GetPetByIdStatus400
  '404': GetPetByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetPetByIdResponse = GetPetByIdStatus200 | GetPetByIdStatus400 | GetPetByIdStatus404

/**
 * @description ID of pet that needs to be updated
 *
 * Format: `int64`
 * @type integer
 */
export type UpdatePetWithFormPathPetId = bigint

/**
 * @description Name of pet that needs to be updated
 * @type string | undefined
 */
export type UpdatePetWithFormQueryName = string | undefined

/**
 * @description Status of pet that needs to be updated
 * @type string | undefined
 */
export type UpdatePetWithFormQueryStatus = string | undefined

/**
 * @type unknown
 */
export type UpdatePetWithFormStatus405 = unknown

/**
 * @type object
 */
export type UpdatePetWithFormRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    petId: UpdatePetWithFormPathPetId
  }
  /**
   * @type object | undefined
   */
  query?: {
    name?: UpdatePetWithFormQueryName
    status?: UpdatePetWithFormQueryStatus
  }
  headers?: never
}

/**
 * @type object
 */
export type UpdatePetWithFormResponses = {
  '405': UpdatePetWithFormStatus405
}

/**
 * @description Union of all possible responses
 */
export type UpdatePetWithFormResponse = UpdatePetWithFormStatus405

/**
 * @type string | undefined
 */
export type DeletePetHeaderApiKey = string | undefined

/**
 * @description Pet id to delete
 *
 * Format: `int64`
 * @type integer
 */
export type DeletePetPathPetId = bigint

/**
 * @type array
 */
export type DeletePetStatus200 = Array<DeletePetStatus200EnumenumType>

/**
 * @type unknown
 */
export type DeletePetStatus400 = unknown

/**
 * @type object
 */
export type DeletePetRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    petId: DeletePetPathPetId
  }
  query?: never
  /**
   * @type object | undefined
   */
  headers?: {
    apiKey?: DeletePetHeaderApiKey
  }
}

/**
 * @type object
 */
export type DeletePetResponses = {
  '200': DeletePetStatus200
  '400': DeletePetStatus400
}

/**
 * @description Union of all possible responses
 */
export type DeletePetResponse = DeletePetStatus200 | DeletePetStatus400

/**
 * @description ID of pet to update
 *
 * Format: `int64`
 * @type integer
 */
export type UploadFilePathPetId = bigint

/**
 * @description Additional Metadata
 * @type string | undefined
 */
export type UploadFileQueryAdditionalMetadata = string | undefined

/**
 * @type object
 */
export type UploadFileStatus200 = ApiResponse

/**
 * @description
 * Format: `binary`
 * @type string | undefined
 */
export type UploadFileData = Blob | undefined

/**
 * @type object
 */
export type UploadFileRequestConfig = {
  body: UploadFileData
  /**
   * @type object
   */
  path: {
    petId: UploadFilePathPetId
  }
  /**
   * @type object | undefined
   */
  query?: {
    additionalMetadata?: UploadFileQueryAdditionalMetadata
  }
  headers?: never
}

/**
 * @type object
 */
export type UploadFileResponses = {
  '200': UploadFileStatus200
}

/**
 * @description Union of all possible responses
 */
export type UploadFileResponse = UploadFileStatus200

/**
 * @type object
 */
export type GetInventoryStatus200 = {
  [key: string]: number
}

/**
 * @type object
 */
export type GetInventoryRequestConfig = {
  body?: never
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type GetInventoryResponses = {
  '200': GetInventoryStatus200
}

/**
 * @description Union of all possible responses
 */
export type GetInventoryResponse = GetInventoryStatus200

/**
 * @type object
 */
export type PlaceOrderStatus200 = Order

/**
 * @type unknown
 */
export type PlaceOrderStatus405 = unknown

/**
 * @description Order description
 * @type object | undefined
 */
export type PlaceOrderJsonData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderXmlData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderFormUrlEncodedData = Order | undefined

export type PlaceOrderData = PlaceOrderJsonData | PlaceOrderXmlData | PlaceOrderFormUrlEncodedData

/**
 * @type object
 */
export type PlaceOrderRequestConfig = {
  body: PlaceOrderData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type PlaceOrderResponses = {
  '200': PlaceOrderStatus200
  '405': PlaceOrderStatus405
}

/**
 * @description Union of all possible responses
 */
export type PlaceOrderResponse = PlaceOrderStatus200 | PlaceOrderStatus405

/**
 * @type object
 */
export type PlaceOrderPatchStatus200 = Order

/**
 * @type unknown
 */
export type PlaceOrderPatchStatus405 = unknown

/**
 * @type object | undefined
 */
export type PlaceOrderPatchJsonData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderPatchXmlData = Order | undefined

/**
 * @type object | undefined
 */
export type PlaceOrderPatchFormUrlEncodedData = Order | undefined

export type PlaceOrderPatchData = PlaceOrderPatchJsonData | PlaceOrderPatchXmlData | PlaceOrderPatchFormUrlEncodedData

/**
 * @type object
 */
export type PlaceOrderPatchRequestConfig = {
  body: PlaceOrderPatchData
  path?: never
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type PlaceOrderPatchResponses = {
  '200': PlaceOrderPatchStatus200
  '405': PlaceOrderPatchStatus405
}

/**
 * @description Union of all possible responses
 */
export type PlaceOrderPatchResponse = PlaceOrderPatchStatus200 | PlaceOrderPatchStatus405

/**
 * @description ID of order that needs to be fetched
 *
 * Format: `int64`
 * @type integer
 */
export type GetOrderByIdPathOrderId = bigint

/**
 * @type object
 */
export type GetOrderByIdStatus200Json = Order

/**
 * @type object
 */
export type GetOrderByIdStatus200Xml = Order

export type GetOrderByIdStatus200 = GetOrderByIdStatus200Json | GetOrderByIdStatus200Xml

/**
 * @type unknown
 */
export type GetOrderByIdStatus400 = unknown

/**
 * @type unknown
 */
export type GetOrderByIdStatus404 = unknown

/**
 * @type object
 */
export type GetOrderByIdRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    orderId: GetOrderByIdPathOrderId
  }
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type GetOrderByIdResponses = {
  '200':
    | {
        contentType: 'application/json'
        data: GetOrderByIdStatus200Json
      }
    | {
        contentType: 'application/xml'
        data: GetOrderByIdStatus200Xml
      }
  '400': GetOrderByIdStatus400
  '404': GetOrderByIdStatus404
}

/**
 * @description Union of all possible responses
 */
export type GetOrderByIdResponse = GetOrderByIdStatus200 | GetOrderByIdStatus400 | GetOrderByIdStatus404

/**
 * @description ID of the order that needs to be deleted
 *
 * Format: `int64`
 * @type integer
 */
export type DeleteOrderPathOrderId = bigint

/**
 * @type unknown
 */
export type DeleteOrderStatus400 = unknown

/**
 * @type unknown
 */
export type DeleteOrderStatus404 = unknown

/**
 * @type object
 */
export type DeleteOrderRequestConfig = {
  body?: never
  /**
   * @type object
   */
  path: {
    orderId: DeleteOrderPathOrderId
  }
  query?: never
  headers?: never
}

/**
 * @type object
 */
export type DeleteOrderResponses = {
  '400': DeleteOrderStatus400
  '404': DeleteOrderStatus404
}

/**
 * @description Union of all possible responses
 */
export type DeleteOrderResponse = DeleteOrderStatus400 | DeleteOrderStatus404
