/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { CreatePetsResponse, CreatePetsData } from './CreatePets'
import type { HttpResponseResolver } from 'msw'
import { createPetsResponse } from './createPets'
import { http } from 'msw'

export function createPetsHandlerResponse201(data?: CreatePetsResponse) {
  return new Response(JSON.stringify(data), {
    status: 201,
  })
}

export function createPetsHandler(data?: CreatePetsResponse | HttpResponseResolver<Record<string, string>, CreatePetsData, any>) {
  return http.post<Record<string, string>, CreatePetsData, any>('/pets', function handler(info) {
    if (typeof data === 'function') return data(info)

    return new Response(JSON.stringify(data || createPetsResponse(data)), {
      status: 201,
    })
  })
}
