/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

/**
 * @type object
*/
export type ApiResponse = {
    /**
     * @description Format: `int32`
     * @type integer | undefined
    */
    code?: number;
    /**
     * @type string | undefined
    */
    type?: string;
    /**
     * @type string | undefined
    */
    message?: string;
};