/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import { faker } from '@faker-js/faker'
import { error, pet } from '../updatePet'

export function updatePetPathParams(data?: Partial<UpdatePetPathParams>): typeof _defaults & Omit<UpdatePetPathParams, keyof typeof _defaults> {
  const _defaults = { petId: faker.number.int() }
  const result = { ..._defaults, ...(data || {}) } as typeof _defaults & Omit<UpdatePetPathParams, keyof typeof _defaults>
  return result
}

/**
 * @description Pet updated
 */
export function updatePet200(data?: Partial<UpdatePet200>): UpdatePet200 {
  return pet(data)
}

/**
 * @description unexpected error
 */
export function updatePetError(data?: Partial<UpdatePetError>): UpdatePetError {
  return error(data)
}

export function updatePetMutationRequest(data?: Partial<UpdatePetMutationRequest>): UpdatePetMutationRequest {
  return pet(data)
}

export function updatePetMutationResponse(data?: Partial<UpdatePetMutationResponse>): UpdatePetMutationResponse {
  return data || faker.helpers.arrayElement<any>([updatePet200()])
}
