/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { UpdatePetData, UpdatePetResponse, UpdatePetStatus200 } from "../../types/UpdatePet.ts";
import { pet } from "../pet.ts";
import { faker } from "@faker-js/faker";

/**
 * @description Successful operation
 */
export function updatePetStatus200(data?: Partial<UpdatePetStatus200>): UpdatePetStatus200 {

  return pet(data)
}

/**
 * @description Invalid ID supplied
 */
export function updatePetStatus400() {

  return undefined
}

/**
 * @description Pet not found
 */
export function updatePetStatus404() {

  return undefined
}

/**
 * @description Validation exception
 */
export function updatePetStatus405() {

  return undefined
}

/**
 * @description Update an existent pet in the store
 */
export function updatePetData(data?: Partial<UpdatePetData>): UpdatePetData {

  return pet(data)
}

export function updatePetResponse(_data?: UpdatePetResponse): UpdatePetResponse {

  return faker.helpers.arrayElement<any>([updatePetStatus200(), updatePetStatus400(), updatePetStatus404(), updatePetStatus405()])
}