/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

/**
 * @type object
 */
export type ListUploadsQuery = {
  /**
   * @type integer | undefined
   */
  'max-uploads'?: number
  /**
   * @type string | undefined
   */
  prefix?: string
}

/**
 * @type object
 */
export type ListUploadsStatus200 = object

/**
 * @type object
 */
export type ListUploadsOptions = {
  body?: never
  path?: never
  query?: ListUploadsQuery
  headers?: never
}

/**
 * @type object
 */
export type ListUploadsResponses = {
  '200': ListUploadsStatus200
}

/**
 * @description Union of all possible responses
 */
export type ListUploadsResponse = ListUploadsStatus200
