/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { Client, RequestConfig, ResponseErrorConfig } from '../.kubb/client.ts'
import type { GetUserByNamePathUsername, GetUserByNameStatus200, GetUserByNameStatus400, GetUserByNameStatus404 } from '../types/GetUserByName.ts'
import { client } from '../.kubb/client.ts'

function getGetUserByNameUrl(username: GetUserByNamePathUsername) {
  const res = { method: 'GET', url: `/user/${username}` as const }

  return res
}

/**
 * @summary Get user by user name
 * {@link /user/:username}
 */
export async function getUserByName(username: GetUserByNamePathUsername, config: Partial<RequestConfig> & { client?: Client } = {}) {
  const { client: request = client, ...requestConfig } = config

  const res = await request<GetUserByNameStatus200 | GetUserByNameStatus400 | GetUserByNameStatus404, ResponseErrorConfig<GetUserByNameStatus400 | GetUserByNameStatus404>, unknown>({ method: 'GET', url: getGetUserByNameUrl(username).url.toString(), ...requestConfig })

  return res as ({ status: 200; data: GetUserByNameStatus200; statusText: string } | { status: 400; data: GetUserByNameStatus400; statusText: string } | { status: 404; data: GetUserByNameStatus404; statusText: string })
}