/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import client from '@kubb/plugin-client/clients/axios'
import type { UpdateUserPathUsername, UpdateUserData, UpdateUserStatusDefault } from '../types/UpdateUser.ts'
import type { Client, RequestConfig, ResponseErrorConfig } from '@kubb/plugin-client/clients/axios'

function getUpdateUserUrl(username: UpdateUserPathUsername) {
  const res = { method: 'PUT', url: `/user/${username}` as const }

  return res
}

/**
 * @description This can only be done by the logged in user.
 * @summary Update user
 * {@link /user/:username}
 */
export async function updateUser(username: UpdateUserPathUsername, data?: UpdateUserData, config: Partial<RequestConfig<UpdateUserData>> & { client?: Client; contentType?: "application/json" | "application/xml" | "application/x-www-form-urlencoded" } = {}) {
  const { client: request = client, contentType = 'application/json', ...requestConfig } = config

  const requestData = data

  const res = await request<UpdateUserStatusDefault, ResponseErrorConfig<Error>, UpdateUserData>({ method: 'PUT', url: getUpdateUserUrl(username).url.toString(), data: requestData, contentType, ...requestConfig })

  return res as { status: number; data: UpdateUserStatusDefault; statusText: string }
}