/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 * Source: text content
 */

export type ShowPetByIdPath = {
  petId: string
}

export type ShowPetByIdStatus200 = object

export type ShowPetByIdStatusDefault = object

export type ShowPetByIdOptions = {
  body?: never
  path: ShowPetByIdPath
  query?: never
  headers?: never
}

export type ShowPetByIdResponses = {
  '200': ShowPetByIdStatus200
  default: ShowPetByIdStatusDefault
}

/**
 * @description Union of all possible responses
 */
export type ShowPetByIdResponse = ShowPetByIdStatus200 | ShowPetByIdStatusDefault
