/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import type { GetInventoryResponse, GetInventoryStatus200 } from "../types/GetInventory.ts";

/**
   * @description successful operation
   */
  export function getInventoryStatus200(data?: Partial<GetInventoryStatus200>): Required<GetInventoryStatus200>
{
  const defaultFakeData = {}
  return {
    ...defaultFakeData,
    ...(data || {}),
  } as Required<GetInventoryStatus200>
}

export function getInventoryResponse(data?: Partial<GetInventoryResponse>): GetInventoryResponse {
  return getInventoryStatus200(data)
}