/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import type { Client, RequestConfig, ResponseErrorConfig } from './.kubb/client'
import type { GetPetPathPetId, GetPetStatus200 } from './GetPet'
import { client, mergeConfig } from './.kubb/client'
import { transformGetPetStatus200 } from './transformers/GetPet'

export class Pet {
  #config: Partial<RequestConfig> & { client?: Client }

  constructor(config: Partial<RequestConfig> & { client?: Client } = {}) {
    this.#config = config
  }

  /**
   * {@link /pet/:petId}
   */
  async getPet(petId: GetPetPathPetId, config: Partial<RequestConfig> & { client?: Client } = {}) {
    const { client: request = client, ...requestConfig } = mergeConfig(this.#config, config)
    const res = await request<GetPetStatus200, ResponseErrorConfig<Error>, unknown>({ ...requestConfig, method: 'GET', url: `/pet/${petId}` })
    return transformGetPetStatus200(res.data)
  }
}
