/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { addPetRequestSchema } from './addPetRequestSchema.ts'
import { petSchema } from './petSchema.ts'

export const addPetStatus200SchemaJson = z.lazy(() => petSchema)

export const addPetStatus200SchemaXml = z.lazy(() => petSchema)

export const addPetStatus200Schema = z.union([addPetStatus200SchemaJson, addPetStatus200SchemaXml])

export const addPetStatus405Schema = z.object({
  code: z.optional(z.int()),
  message: z.optional(z.string()),
})

export const addPetResponseSchema = addPetStatus200Schema

export const addPetErrorSchema = addPetStatus405Schema

export const addPetBodySchemaJson = addPetRequestSchema

export const addPetBodySchemaXml = z.lazy(() => petSchema)

export const addPetBodySchemaFormUrlEncoded = z.lazy(() => petSchema)

export const addPetBodySchema = z.union([addPetBodySchemaJson, addPetBodySchemaXml, addPetBodySchemaFormUrlEncoded])
