/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { addPetRequestSchema } from './addPetRequestSchema.ts'
import { petSchema } from './petSchema.ts'

export const addPetStatus200SchemaJson = z.lazy(() => petSchema)

export const addPetStatus200SchemaXml = z.lazy(() => petSchema)

export const addPetStatus200Schema = z.union([addPetStatus200SchemaJson, addPetStatus200SchemaXml])

export const addPetStatus405Schema = z.object({
  code: z.optional(z.int()),
  message: z.optional(z.string()),
})

export const addPetResponseSchema = addPetStatus200Schema

export const addPetDataSchemaJson = addPetRequestSchema

export const addPetDataSchemaXml = z.lazy(() => petSchema)

export const addPetDataSchemaFormUrlEncoded = z.lazy(() => petSchema)

export const addPetDataSchema = z.union([addPetDataSchemaJson, addPetDataSchemaXml, addPetDataSchemaFormUrlEncoded])
