/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { petNotFoundSchema } from "./petNotFoundSchema.ts";

export const createPetsPathUuidSchema = z.string()

export const createPetsQueryOffsetSchema = z.optional(z.int())

export const createPetsHeaderXEXAMPLESchema = z.enum(["ONE", "TWO", "THREE"])

export const createPetsStatus201Schema = z.any()

export const createPetsStatusDefaultSchema = petNotFoundSchema

export const createPetsDataSchema = z.object({
    "name": z.string(),
    "tag": z.string()
    })