/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

export const findPetsByTagsQueryTagsSchema = z.optional(z.array(z.string()))

export const findPetsByTagsQueryPageSchema = z.optional(z.string())

export const findPetsByTagsQueryPageSizeSchema = z.optional(z.string())

export const findPetsByTagsHeaderXEXAMPLESchema = z.enum(['ONE', 'TWO', 'THREE'])
