/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { petSchema } from './petSchema'

export const findPetsByStatusQueryStatusSchema = z._default(z.optional(z.enum(['available', 'pending', 'sold'])), 'available')

export const findPetsByStatusStatus200SchemaJson = z.array(z.lazy(() => petSchema))

export const findPetsByStatusStatus200SchemaXml = z.array(z.lazy(() => petSchema))

export const findPetsByStatusStatus200Schema = z.union([findPetsByStatusStatus200SchemaJson, findPetsByStatusStatus200SchemaXml])

export const findPetsByStatusStatus400Schema = z.unknown()

export const findPetsByStatusResponseSchema = findPetsByStatusStatus200Schema

export const findPetsByStatusErrorSchema = findPetsByStatusStatus400Schema
