/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { orderSchema } from './orderSchema.ts'

export const getOrderByIdPathOrderIdSchema = z.bigint()

export const getOrderByIdStatus200SchemaJson = orderSchema

export const getOrderByIdStatus200SchemaXml = orderSchema

export const getOrderByIdStatus200Schema = z.union([getOrderByIdStatus200SchemaJson, getOrderByIdStatus200SchemaXml])

export const getOrderByIdStatus400Schema = z.unknown()

export const getOrderByIdStatus404Schema = z.unknown()

export const getOrderByIdResponseSchema = getOrderByIdStatus200Schema

export const getOrderByIdErrorSchema = z.union([getOrderByIdStatus400Schema, getOrderByIdStatus404Schema])
