/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { phoneNumberSchema } from './phoneNumberSchema'

export const phoneWithMaxLengthSchema = phoneNumberSchema.check(z.maxLength(15))
