/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'
import { userSchema } from './userSchema.ts'

export const updateUserPathUsernameSchema = z.string()

export const updateUserStatusDefaultSchema = z.any()

export const updateUserResponseSchema = updateUserStatusDefaultSchema

export const updateUserDataSchema = z.optional(userSchema)
