/**
 * Generated by Kubb (https://kubb.dev/).
 * Do not edit manually.
 */

import * as z from 'zod/mini'

export const uploadFilePathPetIdSchema = z.bigint()

export const uploadFileQueryAdditionalMetadataSchema = z.optional(z.string())

export const uploadFileDataSchema = z.optional(z.instanceof(File))
