/**
* Generated by Kubb (https://kubb.dev/).
* Do not edit manually.
*/

import * as z from "zod/mini";
import { apiResponseSchema } from "./apiResponseSchema.ts";

export const uploadFilePathPetIdSchema = z.int()

export const uploadFileQueryAdditionalMetadataSchema = z.optional(z.string())

export const uploadFileStatus200Schema = apiResponseSchema

export const uploadFileDataSchema = z.optional(z.instanceof(File))